import {StyleSheet} from 'react-native';
import Colors from '@constants/colors';
import Fonts from '@constants/fonts';
export const styles = StyleSheet.create({
  contentContainerStyle: {
    flexGrow: 1,
  },
  title: {
    fontFamily: Fonts.SemiBoldPoppins,
    fontSize: 16,
    lineHeight: 24,
    display: 'flex',
    alignItems: 'center',
    letterSpacing: 0.01,
    color: '#1D252D',
  },
  subTitle: {
    fontFamily: Fonts.SemiBoldPoppins,
    fontSize: 12,
    lineHeight: 16,
    display: 'flex',
    alignItems: 'center',
    letterSpacing: 0.25,
    color: '#868E96',
    marginVertical: 5,
  },
  button: {
    display: 'flex',
    padding: 12,
    paddingLeft: 16,
    gap: 8,
    backgroundColor: '#fff',
    borderRadius: 10,
    marginVertical: 5,
    marginHorizontal: 2,
  },
  buttonContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginVertical: 5,
  },
  subContainer: {
    flexDirection: 'row',
    width: '80%',
    alignItems: 'center',
  },
  shadowProp: {
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
    elevation: 5,
  },
  bgBlueOrnament: {
    resizeMode: 'cover',
    width: '100%',
    position: 'absolute',
    zIndex: -1,
    backgroundColor: '#F9FCFF',
  },
  cardContainer: {
    marginTop: 16,
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
    padding: 16,
    backgroundColor: Colors.white,
    paddingBottom: 32,
    height: '100%',
  },
  container: {
    paddingBottom: 120,
  },
  topTitle: {
    marginLeft: '1%',
    fontFamily: Fonts.RegularPoppins,
    color: Colors.white,
    marginTop: '2%',
    fontSize: 14,
    lineHeight: 18,
  },
  headerWrapperSecond: {
    flexDirection: 'row',
    paddingHorizontal: 16,
    paddingVertical: 10,
  },
  headerWrapperSecondSubTitle: {
    fontFamily: Fonts.RegularPoppins,
    fontWeight: '400',
    fontSize: 12,
    lineHeight: 16,
    letterSpacing: 0.25,
    color: Colors.white,
  },
  headerWrapperSecondTitle: {
    fontFamily: Fonts.SemiBoldPoppins,
    fontWeight: '600',
    fontSize: 20,
    lineHeight: 28,
    marginTop: 1,
    letterSpacing: 1,
    color: Colors.white,
  },
  iconContainer: {
    width: 50,
    height: 50,
    backgroundColor: Colors.white,
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 100,
  },
  progressContainer: {
    flexDirection: 'column',
  },
  progressSubTitle: {
    fontFamily: Fonts.SemiBoldPoppins,
    fontSize: 12,
    lineHeight: 16,
    letterSpacing: 0.25,
    color: Colors.dark.neutral60,
  },
  progressTitle: {
    fontFamily: Fonts.SemiBoldPoppins,
    fontSize: 14,
    lineHeight: 22,
    letterSpacing: 0.25,
    color: Colors.dark.neutral100,
  },
  rectangle: {
    backgroundColor: Colors.dark.neutral10,
    height: 2,
    marginTop: 8,
    width: '100%',
    padding: 0,
    shadowRadius: 1,
  },
  middleContainer: {
    marginTop: 16,
  },
  bottomContainer: {
    marginVertical: 16,
  },
  bottomTitle: {
    fontFamily: Fonts.SemiBoldPoppins,
    color: Colors.dark.neutral100,
    fontSize: 14,
    lineHeight: 18,
    fontWeight: '600',
    letterSpacing: 0.25,
  },
  progressBarContainer: {
    flex: 1,
    justifyContent: 'center',
    paddingLeft: '20%',
  },
  rightIcon: {
    position: 'absolute',
    right: 20,
    width: 50,
    height: 50,
    color: Colors.dark.neutral50,
  },
});
