import Colors from '@constants/colors';
import {StyleSheet} from 'react-native';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    paddingBottom: 24,
  },
  groupMentorTitle: {
    fontSize: 14,
    lineHeight: 18,
    color: Colors.dark.neutral100,
    fontWeight: '600',
    fontFamily: 'Poppins-SemiBold',
    marginBottom: 8,
  },
  headerContent: {
    width: '100%',
    paddingHorizontal: 16,
    paddingVertical: 12,
    backgroundColor: Colors.primary.light3,
    borderTopLeftRadius: 10,
    borderTopRightRadius: 10,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  leftContentContainer: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  cardContentConnected: {
    backgroundColor: Colors.white,
    elevation: 4,
    borderRadius: 10,
    justifyContent: 'space-between',
  },
  connectedTitle: {
    fontSize: 14,
    lineHeight: 18,
    color: Colors.dark.neutral100,
    fontWeight: '600',
    fontFamily: 'Poppins-SemiBold',
    marginBottom: 2,
  },
  connectedSubtitle: {
    fontSize: 14,
    lineHeight: 16,
    color: Colors.dark.neutral80,
    fontWeight: '400',
    fontFamily: 'Poppins-Regular',
  },
  connectedSubtitleFont12: {
    fontSize: 12,
    lineHeight: 16,
    color: Colors.dark.neutral80,
    fontWeight: '400',
    fontFamily: 'Poppins-Regular',
  },
  subtitleBlue: {
    fontSize: 14,
    lineHeight: 16,
    color: Colors.primary.base,
    fontWeight: '600',
    fontFamily: 'Poppins-SemiBold',
    marginRight: 4,
  },
  connectedButton: {
    width: '40%',
    paddingVertical: 0,
  },
  cardContentNotConnected: {
    width: '100%',
    paddingHorizontal: 16,
    paddingVertical: 12,
    backgroundColor: Colors.primary.light3,
    borderRadius: 10,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  notConnectedTitle: {
    fontSize: 14,
    lineHeight: 18,
    color: Colors.dark.neutral100,
    fontWeight: '600',
    fontFamily: 'Poppins-SemiBold',
    marginBottom: 2,
  },
  notConnectedSubtitle: {
    fontSize: 11,
    lineHeight: 16,
    color: Colors.dark.neutral60,
    width: '80%',
    fontWeight: '400',
    fontFamily: 'Poppins-Regular',
  },
  notConnectedButton: {
    width: '40%',
    paddingVertical: 0,
  },
  imageUser: {
    resizeMode: 'contain',
    width: 32,
    height: 32,
    borderRadius: 100,
    marginRight: 8,
  },
  cardTaskConnected: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingHorizontal: 16,
    paddingVertical: 12,
    alignItems: 'center',
  },
  leftContentConnectedContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
  },
  lineGrey: {
    height: 2,
    backgroundColor: Colors.dark.neutral20,
    marginHorizontal: 16,
  },
});
