import {StyleSheet} from 'react-native';

import Colors from '@constants/colors';

export const styles = StyleSheet.create({
  header: {
    top: 40,
    paddingHorizontal: 16,
  },
  KPRMarginTop: {marginTop: '2%'},
  scrollContainer: {
    flexGrow: 1,
  },
  soalTestContainer: {width: '100%', height: 500, backgroundColor: 'white'},
  soalTestHeaderContainer: {
    width: '100%',
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: '3%',
  },
  soalTestHeaderTextBottom: {
    fontFamily: 'Poppins-SemiBold',
    fontSize: 20,
    lineHeight: 28,
    color: Colors?.dark?.neutral100,
  },
  soalTestInfoButtonText: {
    fontSize: 14,
    fontFamily: 'Poppins-Regular',
    lineHeight: 22,
    letterSpacing: 0.25,
    color: Colors?.primary?.base,
  },
  soalTestRulesContainer: {
    width: '100%',
    marginTop: '5%',
    paddingHorizontal: '5%',
  },
  soalTestSubmitButtonContainer: {
    width: '100%',
    position: 'absolute',
    bottom: 20,
    justifyContent: 'center',
    alignItems: 'center',
  },
  soalTestSubmitButton: {width: '90%'},
  soalTestRulesTitleText: {
    fontFamily: 'Poppins-SemiBold',
    fontSize: 14,
    lineHeight: 22,
    letterSpacing: 0.25,
    color: Colors?.dark?.neutral100,
  },
  soalTestInfoButtonContainer: {
    paddingHorizontal: 10,
    paddingVertical: 5,
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 20,
    backgroundColor: Colors?.primary?.light3,
    marginRight: 4,
  },
  soalTestInfoContainer: {
    width: '100%',
    alignItems: 'center',
    justifyContent: 'center',
    flexDirection: 'row',
    marginTop: '3%',
  },
  soalTestHeaderTextTop: {
    fontFamily: 'Poppins-SemiBold',
    fontSize: 14,
    lineHeight: 18,
    letterSpacing: 0.25,
    color: Colors?.primary?.base,
    marginBottom: 8,
  },
  soalCardTitleContainer: {
    flex: 1,
    justifyContent: 'flex-end',
    marginBottom: 10,
  },
  soalCardTitleContainerKuis: {flex: 5, justifyContent: 'center'},
  soalCardTitleContainerKuis2: {
    flex: 1,
    alignItems: 'flex-end',
    justifyContent: 'center',
  },
  soalCardContainer: {
    width: '100%',
    marginTop: 10,
    paddingVertical: 10,
    paddingHorizontal: '5%',
    borderRadius: 10,
    backgroundColor: 'white',
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
    elevation: 5,
  },
  soalCardContainerKuis: {
    width: '100%',
    marginTop: 12,
    flexDirection: 'row',
    paddingVertical: 10,
    paddingHorizontal: '5%',
    borderRadius: 10,
    backgroundColor: 'white',
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
    elevation: 5,
  },
  kpAskQuestionContainer: {flexDirection: 'row', gap: 12},
  soalCardTitle: {
    fontFamily: 'Poppins-SemiBold',
    fontSize: 16,
    lineHeight: 24,
    color: Colors.dark.neutral100,
    marginLeft: 8,
  },
  soalCardButtonContainer: {flex: 2, flexDirection: 'row'},
  soalCardRightInnerContainer: {
    flexDirection: 'row',
    height: 35,
    width: '90%',
    borderRadius: 20,
    backgroundColor: Colors.primary.light3,
  },
  soalCardButtonRightText: {
    fontFamily: 'Poppins-SemiBold',
    fontSize: 14,
    lineHeight: 22,
    color: Colors.dark.neutral80,
  },
  soalCardButtonRighttextContainer: {
    flex: 1.5,
    justifyContent: 'center',
    alignItems: 'flex-start',
    paddingLeft: '5%',
  },
  soalCardButtonRightIconContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'flex-end',
  },
  soalCardButtonRightContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  soalCardButtonLeftContentContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  soalCardButtonLeftContentButton: {
    flexDirection: 'row',
    height: 35,
    width: '90%',
    borderRadius: 20,
    backgroundColor: Colors.primary.light3,
  },
  soalCardButtonLeftTitle: {
    fontFamily: 'Poppins-SemiBold',
    fontSize: 14,
    lineHeight: 22,
    color: Colors.dark.neutral80,
  },
  soalCardButtonLeftTitleContainer: {
    flex: 2,
    justifyContent: 'center',
    alignItems: 'flex-start',
    paddingLeft: '5%',
  },
  soalCardButtonLeftIconContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'flex-end',
  },
  akmReportButton: {
    width: '100%',
    marginHorizontal: '25%',
    position: 'absolute',
    bottom: '5%',
  },
  literationIconContainer: {
    width: '100%',
    backgroundColor: Colors.secondary.light2,
    borderTopLeftRadius: 10,
    borderTopRightRadius: 10,
  },
  numerationIconContainer: {
    width: '100%',
    backgroundColor: Colors.secondary.light3,
    borderTopLeftRadius: 10,
    borderTopRightRadius: 10,
  },
  literationTypeIconContainer: {
    flex: 2,
    alignItems: 'flex-end',
    justifyContent: 'center',
  },
  literationTypeArrowContainer: {flex: 1, justifyContent: 'center'},
  literationTypeTitle: {
    fontFamily: 'Poppins-SemiBold',
    color: Colors.dark.neutral100,
    fontSize: 16,
    lineHeight: 20,
  },
  literationTypeTitleContainer: {
    flex: 6,
    justifyContent: 'center',
    alignItems: 'flex-start',
    paddingLeft: '5%',
  },
  literationTypeIcon: {
    width: 50,
    height: 50,
    backgroundColor: 'blue',
    borderRadius: 100,
  },
  literationBodyInnerContainer: {
    width: '100%',
    height: 80,
    backgroundColor: 'white',
    flexDirection: 'row',
  },
  literationBodyContainer: {
    width: '100%',
    backgroundColor: Colors.white,
    marginBottom: 10,
    borderBottomRightRadius: 10,
    borderBottomLeftRadius: 10,
  },
  literationIconInnerCOntainer: {width: '100%', alignItems: 'center'},
  literationCardContainer: {
    backgroundColor: Colors.white,
    marginTop: '5%',
    borderRadius: 10,
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 1,
    },
    shadowOpacity: 0.2,
    shadowRadius: 1.41,

    elevation: 2,
  },
  iconContainer: {
    width: 50,
    height: 50,
    backgroundColor: Colors.white,
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 100,
  },
  chooseQuestionTypeContainer: {marginTop: '2%'},
  asesmenTitle: {
    fontFamily: 'Poppins-Regular',
    color: Colors.white,
    fontSize: 14,
    lineHeight: 18,
    letterSpacing: 0.25,
  },
  chooseQueastionType: {
    fontFamily: 'Poppins-SemiBold',
    color: Colors.dark.neutral100,
    fontSize: 16,
    lineHeight: 20,
  },
  chapterPressable: {flexDirection: 'row', marginBottom: 12},
  AKMTitle: {
    fontFamily: 'Poppins-SemiBold',
    fontSize: 24,
    lineHeight: 32,
    color: Colors.white,
    marginVertical: 1,
  },
  KPRTitle: {
    fontFamily: 'Poppins-Regular',
    color: Colors.white,
    fontSize: 14,
    lineHeight: 18,
    letterSpacing: 0.25,
  },
  bgPosition: {position: 'absolute'},
  headerWrapperFirst: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  headerWrapperSecond: {
    flexDirection: 'row',
    gap: 12,
    top: 30,
  },
  headerWrapperSecondIcon: {
    backgroundColor: Colors.white,
    borderRadius: 40,
    padding: 30,
  },
  headerWrapperSecondSubTitle: {
    fontFamily: 'Poppins-Regular',
    fontWeight: '400',
    fontSize: 14,
    lineHeight: 18,
    letterSpacing: 0.25,
    color: Colors.white,
  },
  headerWrapperSecondTitle: {
    fontFamily: 'Poppins-SemiBold',
    fontWeight: '600',
    fontSize: 24,
    lineHeight: 32,
    marginTop: 1,
    letterSpacing: 1,
    color: Colors.white,
  },
  body: {
    flex: 1,
    backgroundColor: Colors.primary.light4,
    padding: 16,
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
  },
});
