import {StyleSheet} from 'react-native';

import Fonts from '@constants/fonts';
import Colors from '@constants/colors';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: Colors.white,
  },
  subContainer: {
    flexGrow: 1,
    padding: 16,
    backgroundColor: Colors.white,
  },
  titleButton: {
    fontWeight: '600',
    fontSize: 16,
    lineHeight: 20,
    textAlign: 'left',
    color: Colors.dark.neutral100,
    letterSpacing: 0.1,
    fontFamily: Fonts.RegularPoppins,
    marginBottom: 8,
  },
  button: {
    paddingVertical: 8,
    paddingHorizontal: 16,
    backgroundColor: Colors.dark.neutral20,
    justifyContent: 'space-between',
    flexDirection: 'row',
    borderRadius: 30,
  },
  inputForm: {
    marginBottom: 24,
  },
  textButton: {
    fontWeight: '600',
    fontSize: 16,
    lineHeight: 24,
    textAlign: 'left',
    color: Colors.dark.neutral50,
    letterSpacing: 0.1,
    fontFamily: Fonts.SemiBoldPoppins,
  },
  swipeUpContainer: {
    paddingHorizontal: 16,
    paddingBottom: 16,
  },
  swipeUpTitle: {
    fontFamily: 'Poppins-SemiBold',
    fontWeight: '600',
    fontSize: 20,
    lineHeight: 28,
    color: Colors.dark.neutral100,
    textAlign: 'center',
    letterSpacing: 0.1,
    marginBottom: 16,
  },
  swipeUpDataContainer: {
    marginBottom: 16,
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  valueSwipeUp: {
    fontFamily: 'Poppins-Regular',
    fontWeight: '400',
    fontSize: 16,
    lineHeight: 24,
    color: Colors.dark.neutral100,
    letterSpacing: 0.1,
  },
  rectangle: {
    height: 4,
    backgroundColor: Colors.dark.neutral10,
    marginTop: -6,
  },
  materialsContainer: {
    marginTop: 16,
  },
  materialsTitle: {
    fontFamily: Fonts.SemiBoldPoppins,
    fontWeight: '600',
    fontSize: 14,
    lineHeight: 18,
    color: Colors.dark.neutral100,
    letterSpacing: 0.25,
    paddingBottom: 8,
  },
  inputText: {
    backgroundColor: Colors.dark.neutral10,
    fontSize: 16,
    lineHeight: 24,
    letterSpacing: 0.1,
    height: 40,
    marginBottom: 24,
  },
  textType: {
    fontWeight: '400',
    fontSize: 12,
    lineHeight: 16,
    textAlign: 'left',
    color: Colors.dark.neutral60,
    letterSpacing: 0.25,
    fontFamily: Fonts.RegularPoppins,
  },
  buttonAddMaterials: {
    alignSelf: 'flex-start',
    paddingHorizontal: 16,
    paddingVertical: 8,
  },
  error: {
    fontWeight: '400',
    fontSize: 12,
    lineHeight: 16,
    textAlign: 'left',
    color: Colors.danger.base,
    letterSpacing: 0.25,
    fontFamily: Fonts.RegularPoppins,
    marginTop: 8,
  },
  titleTopContainer: {
    fontWeight: '400',
    fontSize: 14,
    lineHeight: 18,
    textAlign: 'left',
    color: Colors.dark.neutral60,
    letterSpacing: 0.25,
    fontFamily: Fonts.RegularPoppins,
    width: '35%',
  },
  valueTopContainer: {
    fontWeight: '400',
    fontSize: 14,
    lineHeight: 18,
    color: Colors.dark.neutral100,
    letterSpacing: 0.25,
    fontFamily: Fonts.RegularPoppins,
  },
  topSubContainer: {
    flexDirection: 'row',
    marginBottom: 8,
  },

  headAttachmentFileContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 6,
  },
  titleField: {
    fontWeight: '400',
    fontSize: 14,
    lineHeight: 22,
    color: Colors.dark.neutral100,
    fontFamily: Fonts.RegularPoppins,
    marginBottom: 8,
  },
  uploadTitleField: {
    fontWeight: '400',
    fontSize: 14,
    lineHeight: 22,
    color: Colors.dark.neutral100,
    fontFamily: Fonts.RegularPoppins,
    marginBottom: 4,
  },
  attachmentImageContainer: {
    height: 170,
    width: '100%',
    padding: 8,
    borderRadius: 10,
    justifyContent: 'space-between',
  },
  iconClose: {
    backgroundColor: Colors.dark.neutral10,
    padding: 12,
    borderRadius: 25,
    alignSelf: 'flex-end',
  },
  attachmentResendContainer: {
    backgroundColor: Colors.primary.light3,
    width: 150,
    justifyContent: 'center',
    flexDirection: 'row',
    borderRadius: 30,
    paddingHorizontal: 12,
    paddingVertical: 5,
  },
  attachmentResendTitle: {
    fontWeight: '600',
    fontSize: 14,
    lineHeight: 22,
    color: Colors.primary.base,
    fontFamily: Fonts.SemiBoldPoppins,
  },
  attachmentFileContainer: {
    paddingHorizontal: 16,
    paddingBottom: 16,
    paddingTop: 8,
    borderColor: Colors.dark.neutral20,
    borderRadius: 10,
    borderWidth: 2,
    marginBottom: 12,
  },
  attachmentFileHeadTitle: {
    fontWeight: '400',
    fontSize: 14,
    lineHeight: 18,
    color: Colors.dark.neutral60,
    fontFamily: Fonts.RegularPoppins,
    alignSelf: 'center',
  },
  attachmentDescriptionWrapper: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 8,
  },
  attachmentFileDescriptionTitle: {
    fontSize: 16,
    lineHeight: 20,
    color: Colors.dark.neutral100,
    fontWeight: '600',
    fontFamily: Fonts.SemiBoldPoppins,
    marginLeft: 8,
    width: '90%',
  },
  dateCardContainer: {
    marginBottom: 24,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: Colors.dark.neutral40,
    padding: 16,
  },
  imageBackground: {
    borderRadius: 10,
    resizeMode: 'cover',
    width: '100%',
  },

  uploadButton: {
    backgroundColor: Colors.primary.light3,
    justifyContent: 'center',
    flexDirection: 'row',
    borderRadius: 20,
    paddingVertical: 8,
  },
  uploadTitle: {
    marginLeft: 8,
    fontWeight: '600',
    fontSize: 14,
    lineHeight: 22,
    color: Colors.primary.base,
    fontFamily: Fonts.SemiBoldPoppins,
  },
  swipeUpUpload: {
    padding: 16,
  },
  swipeUpUploadContent: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 16,
  },
  swipeUpUploadHeaderTitle: {
    fontSize: 20,
    lineHeight: 28,
    color: Colors.dark.neutral100,
    fontWeight: '600',
    fontFamily: Fonts.SemiBoldPoppins,
    textAlign: 'center',
    marginBottom: 16,
  },
  swipeUpUploadLabel: {
    fontSize: 16,
    lineHeight: 24,
    color: Colors.dark.neutral100,
    fontWeight: '400',
    fontFamily: Fonts.RegularPoppins,
  },
  dateContainer: {
    marginBottom: 24,
  },
  noteField: {
    fontWeight: '400',
    fontSize: 12,
    lineHeight: 16,
    color: Colors.dark.neutral60,
    fontFamily: Fonts.RegularPoppins,
  },
  errorText: {
    color: Colors.danger.base,
    fontSize: 12,
    lineHeight: 16,
    marginTop: -20,
    marginBottom: 16,
  },
  buttonContainer: {
    marginVertical: 34,
  },
  topColumn: {
    flexDirection: 'column',
    marginBottom: 8,
  },
  containerVideo: {
    marginBottom: 16,
  },
});
