import Colors from '@constants/colors';
import Fonts from '@constants/fonts';
import {StyleSheet} from 'react-native';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    paddingBottom: 24,
  },
  imageOutterContainer: {
    padding: 4,
    width: 80,
    height: 80,
    backgroundColor: Colors.yellow,
    borderRadius: 100,
    alignItems: 'center',
    justifyContent: 'center',
    alignSelf: 'center',
    marginBottom: 10,
  },
  imageInnerContainer: {
    padding: 4,
    width: 72,
    height: 72,
    backgroundColor: Colors.white,
    borderRadius: 100,
    alignItems: 'center',
    justifyContent: 'center',
  },
  imageUser: {
    resizeMode: 'contain',
    width: 70,
    height: 70,
    borderRadius: 100,
  },
  badgeNameContainer: {
    flexDirection: 'row',
    marginBottom: 4,
    alignSelf: 'center',
  },
  badgeName: {
    fontSize: 16,
    lineHeight: 24,
    color: Colors.primary.base,
    fontWeight: '600',
    fontFamily: 'Poppins-SemiBold',
    textAlign: 'center',
    marginRight: 4,
  },
  iconEditContainer: {
    alignItems: 'center',
    justifyContent: 'center',
  },
  badgeClassContainer: {
    flexDirection: 'row',
    alignSelf: 'center',
    backgroundColor: Colors.yellow,
    paddingHorizontal: 10,
    paddingVertical: 2,
    borderRadius: 30,
    marginBottom: 24,
  },
  badgeClassText: {
    fontSize: 16,
    lineHeight: 24,
    color: Colors.primary.base,
    fontWeight: '600',
    fontFamily: 'Poppins-SemiBold',
    textAlign: 'center',
    marginRight: 4,
  },
  leftContentContainer: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  cardContent: {
    width: '100%',
    paddingHorizontal: 16,
    paddingVertical: 12,
    backgroundColor: Colors.primary.light3,
    borderRadius: 10,
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 8,
    justifyContent: 'space-between',
  },
  cardContentNoJustify: {
    width: '100%',
    paddingHorizontal: 16,
    paddingVertical: 12,
    backgroundColor: Colors.primary.light3,
    borderRadius: 10,
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 8,
  },
  cardContentWaiting: {
    width: '100%',
    padding: 16,
    backgroundColor: Colors.white,
    borderRadius: 10,
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 24,
    elevation: 10,
    shadowColor: Colors.black,
    shadowOffset: {
      width: 0,
      height: 3,
    },
    shadowOpacity: 0.15,
    shadowRadius: 5,
    justifyContent: 'space-between',
  },
  leftContentWaiting: {
    flexDirection: 'row',
  },
  imageOutterContainerParent: {
    padding: 4,
    width: 40,
    height: 40,
    backgroundColor: Colors.primary.light2,
    borderRadius: 100,
    alignItems: 'center',
    justifyContent: 'center',
    flexDirection: 'row',
    marginRight: 12,
  },
  imageParent: {
    resizeMode: 'contain',
    width: 40,
    height: 40,
    borderRadius: 100,
  },
  parentBadge: {
    marginTop: 4,
    paddingVertical: 4,
    paddingHorizontal: 8,
    backgroundColor: Colors.dark.neutral10,
    borderRadius: 20,
  },
  parentBadgeTitle: {
    fontSize: 12,
    lineHeight: 16,
    color: Colors.dark.neutral80,
    fontWeight: '400',
    fontFamily: Fonts.RegularPoppins,
  },
  iconMoreGray: {
    alignSelf: 'flex-start',
  },
  parentTitleWaiting: {
    fontSize: 14,
    lineHeight: 22,
    color: Colors.dark.neutral100,
    fontWeight: '600',
    fontFamily: Fonts.SemiBoldPoppins,
  },
  parentSubtitleWaiting: {
    fontSize: 11,
    lineHeight: 16,
    color: Colors.dark.neutral100,
    fontWeight: '400',
    fontFamily: Fonts.RegularPoppins,
  },
  parentTitle: {
    fontSize: 11,
    lineHeight: 16,
    color: Colors.dark.neutral80,
    fontWeight: '400',
    fontFamily: Fonts.RegularPoppins,
  },
  parentSubtitle: {
    fontSize: 14,
    lineHeight: 22,
    color: Colors.dark.neutral100,
    fontWeight: '600',
    fontFamily: Fonts.SemiBoldPoppins,
  },
  imageRankContainer: {
    marginRight: 12,
    width: 40,
    height: 40,
    backgroundColor: Colors.primary.light2,
    borderRadius: 100,
    alignItems: 'center',
    justifyContent: 'center',
  },
  rankIcon: {
    width: 10,
    height: 10,
  },
  rankTitle: {
    fontSize: 14,
    lineHeight: 18,
    color: Colors.primary.base,
    fontWeight: '600',
    fontFamily: Fonts.SemiBoldPoppins,
  },
  trainingReportImageContainer: {
    marginRight: 12,
    width: 40,
    height: 40,
    backgroundColor: Colors.primary.light2,
    borderRadius: 100,
    alignItems: 'center',
    justifyContent: 'center',
  },
  trainingReportIcon: {
    width: 10,
    height: 10,
  },
  trainingReportTitle: {
    fontSize: 14,
    lineHeight: 22,
    color: Colors.dark.neutral100,
    fontWeight: '600',
    fontFamily: Fonts.SemiBoldPoppins,
  },
  cardContentParentNotConnected: {
    width: '100%',
    paddingHorizontal: 16,
    paddingVertical: 12,
    backgroundColor: Colors.primary.light3,
    borderRadius: 10,
    marginBottom: 8,
  },
  parentNotConnectedTitle: {
    fontSize: 14,
    lineHeight: 18,
    color: Colors.dark.neutral100,
    fontWeight: '600',
    fontFamily: Fonts.SemiBoldPoppins,
    marginBottom: 8,
  },
  parentNotConnectedButton: {
    width: '40%',
    paddingVertical: 0,
  },
  parentNotConnectedImage: {
    width: 64,
    height: 64,
    borderBottomRightRadius: 10,
    alignItems: 'center',
    justifyContent: 'center',
    position: 'absolute',
    bottom: 0,
    right: 0,
  },
});
