import Colors from '@constants/colors';
import Fonts from '@constants/fonts';
import {StyleSheet} from 'react-native';

export const styles = StyleSheet.create({
  swipeUpContainer: {
    padding: 16,
  },
  swipeUpContainerAkm: {
    paddingVertical: 16,
    maxHeight: 500,
  },
  swipeUpTitle: {
    fontSize: 20,
    lineHeight: 28,
    color: Colors.dark.neutral100,
    fontWeight: '600',
    fontFamily: Fonts.SemiBoldPoppins,
    marginBottom: 16,
    textAlign: 'center',
  },
  swipeUpContainerStyle: {
    flexGrow: 1,
    paddingHorizontal: 16,
  },
  swipeUpCardCurrentQuestion: {
    padding: 16,
    marginBottom: 16,
    backgroundColor: Colors.white,
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 1,
    },
    shadowOpacity: 0.1,
    shadowRadius: 1.84,
    elevation: 2,
    borderRadius: 10,
    borderColor: Colors.dark.neutral20,
    borderWidth: 1,
  },
  swipeUpCardReviewAnswer: {
    padding: 16,
    marginBottom: 16,
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 1,
    },
    shadowOpacity: 0.1,
    shadowRadius: 1.84,
    elevation: 2,
    borderRadius: 10,
  },
  swipeUpCardTitleCurrentQuestion: {
    fontSize: 12,
    lineHeight: 16,
    color: Colors.dark.neutral100,
    fontWeight: '600',
    fontFamily: Fonts.SemiBoldPoppins,
    marginBottom: 4,
  },
  swipeUpCardMyAnswerTitle: {
    fontSize: 12,
    lineHeight: 16,
    color: Colors.dark.neutral100,
    fontWeight: '600',
    fontFamily: Fonts.SemiBoldPoppins,
    marginBottom: 8,
  },
  contentTitleReview: {
    fontSize: 12,
    lineHeight: 16,
    color: Colors.primary.base,
    fontWeight: '600',
    fontFamily: Fonts.SemiBoldPoppins,
  },
  swipeUpCardDescriptionCardCurrentQuestion: {
    borderColor: Colors.dark.neutral20,
    borderWidth: 1,
    borderRadius: 10,
    paddingHorizontal: 12,
    paddingVertical: 8,
    justifyContent: 'center',
  },
  swipeUpCardDescriptionCardReviewCurrentQuestion: {
    borderColor: Colors.dark.neutral20,
    backgroundColor: Colors.white,
    borderWidth: 1,
    borderRadius: 10,
    paddingHorizontal: 12,
    paddingVertical: 8,
    justifyContent: 'center',
  },
  swipeUpCardDescriptionCurrentQuestion: {
    fontSize: 14,
    lineHeight: 22,
    color: Colors.dark.neutral100,
    fontWeight: '400',
    fontFamily: Fonts.RegularPoppins,
    marginBottom: 8,
  },
  swipeUpCardAnswerCurrentQuestion: {
    fontSize: 14,
    lineHeight: 22,
    color: Colors.dark.neutral100,
    fontWeight: '400',
    fontFamily: Fonts.RegularPoppins,
  },
  swipeUpButtonContainer: {
    paddingTop: 16,
    paddingHorizontal: 16,
  },
  swipeUpDescription: {
    fontSize: 14,
    lineHeight: 22,
    color: Colors.dark.neutral100,
    fontWeight: '400',
    fontFamily: Fonts.RegularPoppins,
    marginBottom: 32,
  },
  swipeUpPauseDescription: {
    fontSize: 14,
    lineHeight: 22,
    color: Colors.dark.neutral100,
    fontWeight: '400',
    fontFamily: Fonts.RegularPoppins,
    textAlign: 'center',
    marginBottom: 32,
  },
  swipeUpGuideTitle: {
    fontSize: 20,
    lineHeight: 28,
    color: Colors.dark.neutral100,
    fontWeight: '600',
    fontFamily: Fonts.SemiBoldPoppins,
    marginBottom: 16,
    textAlign: 'center',
  },
  swipeUpGuideBadgeContainer: {
    justifyContent: 'center',
    flexDirection: 'row',
    marginBottom: 16,
  },
  swipeUpGuideBadgeLabel: {
    paddingHorizontal: 12,
    paddingVertical: 5,
    borderRadius: 20,
    backgroundColor: Colors.primary.light3,
    fontSize: 14,
    lineHeight: 22,
    color: Colors.primary.base,
    fontWeight: '400',
    fontFamily: Fonts.RegularPoppins,
    textAlign: 'center',
  },
  swipeUpGuideHeadDescription: {
    fontSize: 14,
    lineHeight: 22,
    color: Colors.dark.neutral100,
    fontWeight: '600',
    fontFamily: Fonts.SemiBoldPoppins,
    marginBottom: 4,
  },
  swipeUpGuideDescription: {
    fontSize: 14,
    lineHeight: 22,
    color: Colors.dark.neutral100,
    fontWeight: '400',
    fontFamily: Fonts.RegularPoppins,
    paddingLeft: 8,
  },
  swipeUpGuideDescriptionWrapper: {
    flexDirection: 'row',
  },
  swipeUpGuideDescriptionContainer: {
    marginBottom: 32,
  },
  container: {
    flexGrow: 1,
    backgroundColor: Colors.white,
  },
  labelHeader: {
    width: '60%',
    textAlign: 'center',
  },
  finishButtonContainer: {
    borderRadius: 20,
    overflow: 'hidden',
  },
  finishButton: {
    backgroundColor: Colors.success.light1,
    paddingVertical: 3,
    paddingHorizontal: 12,
    color: Colors.white,
    fontSize: 14,
    lineHeight: 22,
    fontWeight: '600',
    fontFamily: Fonts.SemiBoldPoppins,
  },
  contentContainer: {
    paddingHorizontal: 16,
    flex: 1,
    justifyContent: 'space-between',
    paddingVertical: 8,
  },
  scrollViewDescriptionContainer: {
    // maxHeight: 200,
    marginBottom: 16,
  },
  scrollViewDescription: {
    flexGrow: 1,
  },
  contentWrapper: {
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  contentTitle: {
    fontSize: 12,
    lineHeight: 16,
    color: Colors.dark.neutral50,
    fontWeight: '600',
    fontFamily: Fonts.SemiBoldPoppins,
    marginBottom: 4,
  },
  contentMarksContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  contentDescription: {
    fontSize: 14,
    lineHeight: 22,
    color: Colors.dark.neutral100,
    fontWeight: '400',
    fontFamily: Fonts.RegularPoppins,
  },
  explanationContainer: {
    flexDirection: 'row',
    justifyContent: 'center',
  },
  explanationButton: {
    flexDirection: 'row',
    backgroundColor: Colors.white,
    paddingHorizontal: 16,
    paddingVertical: 8,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 30,
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 1,
    },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
    elevation: 5,
  },
  explanationLabel: {
    fontSize: 14,
    lineHeight: 22,
    color: Colors.primary.base,
    fontWeight: '600',
    fontFamily: Fonts.SemiBoldPoppins,
    marginHorizontal: 8,
  },
  buttonContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingVertical: 12,
    alignItems: 'center',
  },
  row: {
    flexDirection: 'row',
  },
  buttonWrapperLeft: {
    backgroundColor: Colors.primary.light3,
    borderRadius: 20,
    paddingHorizontal: 22,
    height: 32,
    alignItems: 'center',
    justifyContent: 'center',
    flexDirection: 'row',
    marginRight: 12,
  },
  buttonWrapper: {
    backgroundColor: Colors.primary.light3,
    borderRadius: 20,
    paddingHorizontal: 22,
    height: 32,
    alignItems: 'center',
    justifyContent: 'center',
    flexDirection: 'row',
  },
  buttonTitle: {
    fontSize: 14,
    lineHeight: 22,
    color: Colors.primary.base,
    fontWeight: '600',
    fontFamily: Fonts.SemiBoldPoppins,
  },
  buttonIcon: {
    marginRight: 8,
  },
  buttonIconMarks: {
    marginRight: 4,
  },
  buttonLeft: {
    width: 48,
    height: 48,
    transform: [{rotate: '180deg'}],
  },
  buttonRight: {
    width: 48,
    height: 48,
  },
  cardContainer: {
    flexDirection: 'row',
    borderRadius: 16,
    borderColor: 'blue',
    borderWidth: 2,
    marginBottom: 16,
  },
  cardImageSvgContainer: {
    borderRadius: 16,
    overflow: 'hidden',
  },
  cardImageSvg: {
    marginRight: 16,
  },
  cardImagePng: {
    borderRadius: 16,
    marginRight: 16,
    width: 88,
    height: 88,
  },
  cardTitle: {
    fontSize: 24,
    lineHeight: 28,
    color: Colors.dark.neutral100,
    fontWeight: '600',
    fontFamily: Fonts.SemiBoldPoppins,
  },
  cardDescription: {
    fontSize: 12,
    lineHeight: 16,
    color: Colors.dark.neutral100,
    fontWeight: '400',
    fontFamily: 'Poppins-SemiBold',
    paddingRight: 12,
  },
  cardTextContainer: {
    justifyContent: 'center',
    flexDirection: 'column',
    paddingVertical: 14,
    flex: 1,
  },

  popableContainer: {
    width: 234,
    borderRadius: 5,
  },
  popableContentContainer: {
    backgroundColor: Colors.white,
    borderRadius: 5,
    paddingVertical: 4,
    paddingHorizontal: 8,
    borderWidth: 1,
    borderColor: Colors.dark.neutral20,
  },
  popableText: {
    fontFamily: 'Poppins-SemiBold',
    fontSize: 14,
    textAlign: 'center',
    color: Colors.danger.base,
  },
  subLabel: {
    fontSize: 11,
    fontFamily: 'Poppins-Regular',
    color: Colors.dark.neutral100,
  },
  subLabelWarning: {
    fontSize: 11,
    fontFamily: 'Poppins-Regular',
    color: Colors.danger.base,
  },
});
