import Colors from '@constants/colors';
import Fonts from '@constants/fonts';
import {StyleSheet} from 'react-native';

export const styles = StyleSheet.create({
  contentContainerStyle: {
    flexGrow: 1,
  },
  rootContainer: {
    flex: 1,
    backgroundColor: Colors.white,
  },
  container: {
    flex: 1,
  },
  content: {
    padding: 16,
  },
  aprrovedContainer: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  card: {
    padding: 16,
    backgroundColor: Colors.primary.light3,
    borderRadius: 10,
    marginBottom: 16,
  },
  cardHeadTitle: {
    fontWeight: '600',
    fontSize: 16,
    lineHeight: 24,
    color: Colors.dark.neutral100,
    fontFamily: Fonts.SemiBoldPoppins,
    marginBottom: 4,
  },
  cardNisTitle: {
    fontWeight: '400',
    fontSize: 12,
    lineHeight: 16,
    color: Colors.dark.neutral80,
    fontFamily: Fonts.SemiBoldPoppins,
    marginBottom: 4,
  },
  cardReasonTitle: {
    fontWeight: '600',
    fontSize: 16,
    lineHeight: 22,
    color: Colors.dark.neutral80,
    fontFamily: Fonts.SemiBoldPoppins,
    marginBottom: 4,
  },
  cardDateContainer: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  cardDateIcon: {
    marginRight: 8,
  },
  cardDateTitle: {
    fontWeight: '400',
    fontSize: 14,
    lineHeight: 22,
    color: Colors.dark.neutral80,
    marginLeft: 8,
    fontFamily: Fonts.RegularPoppins,
  },
  attendanceRequestTitle: {
    fontWeight: '400',
    fontSize: 14,
    lineHeight: 22,
    color: Colors.dark.neutral80,
    fontFamily: Fonts.RegularPoppins,
    marginBottom: 16,
  },
  badgeWaiting: {
    paddingHorizontal: 12,
    paddingVertical: 5,
    borderRadius: 20,
    backgroundColor: Colors.primary.light3,
    marginRight: 8,
  },
  badgeAccepted: {
    paddingHorizontal: 12,
    paddingVertical: 5,
    borderRadius: 20,
    backgroundColor: Colors.success.light2,
    marginRight: 8,
  },
  badgeRejected: {
    paddingHorizontal: 12,
    paddingVertical: 5,
    borderRadius: 20,
    backgroundColor: Colors.danger.light2,
    marginRight: 8,
  },
  titleBadgeWaiting: {
    fontSize: 14,
    lineHeight: 22,
    color: Colors.primary.base,
    fontWeight: '400',
    fontFamily: Fonts.RegularPoppins,
  },
  titleBadgeAccepted: {
    fontSize: 14,
    lineHeight: 22,
    color: Colors.success.base,
    fontWeight: '400',
    fontFamily: Fonts.RegularPoppins,
  },
  titleBadgeRejected: {
    fontSize: 14,
    lineHeight: 22,
    color: Colors.danger.base,
    fontWeight: '400',
    fontFamily: Fonts.RegularPoppins,
  },
  approvedByTitle: {
    width: '70%',
    fontWeight: '400',
    fontSize: 14,
    lineHeight: 22,
    color: Colors.dark.neutral80,
    fontFamily: Fonts.RegularPoppins,
  },
  lineGrey: {
    height: 4,
    width: '100%',
    backgroundColor: Colors.dark.neutral10,
  },
  attachmentHeadTitle: {
    fontWeight: '600',
    fontSize: 16,
    lineHeight: 20,
    color: Colors.dark.neutral100,
    fontFamily: Fonts.SemiBoldPoppins,
    marginBottom: 12,
  },
  attachmentImageContainer: {
    backgroundColor: Colors.dark.neutral20,
    width: '100%',
    height: 185,
    marginBottom: 16,
    borderRadius: 10,
    borderColor: Colors.dark.neutral20,
    borderWidth: 1,
  },
  imageIcon: {
    borderRadius: 10,
    resizeMode: 'cover',
    flex: 1,
  },
  attachmentFileContainer: {
    padding: 16,
    borderColor: Colors.dark.neutral20,
    borderRadius: 10,
    borderWidth: 2,
    marginBottom: 12,
  },
  attachmentFileHeadTitle: {
    fontWeight: '400',
    fontSize: 14,
    lineHeight: 18,
    color: Colors.dark.neutral60,
    fontFamily: Fonts.RegularPoppins,
    marginBottom: 6,
  },
  attachmentDescriptionWrapper: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  attachmentFileDescriptionTitle: {
    fontSize: 16,
    lineHeight: 20,
    color: Colors.dark.neutral100,
    fontWeight: '600',
    fontFamily: Fonts.SemiBoldPoppins,
    marginLeft: 8,
    width: '90%',
  },
  noteHeadTitle: {
    fontWeight: '600',
    fontSize: 16,
    lineHeight: 20,
    color: Colors.dark.neutral100,
    fontFamily: Fonts.SemiBoldPoppins,
    marginBottom: 12,
  },
  noteDescriptionTitle: {
    fontWeight: '400',
    fontSize: 14,
    lineHeight: 22,
    color: Colors.dark.neutral80,
    fontFamily: Fonts.RegularPoppins,
  },
});
