import Colors from '@constants/colors';
import Fonts from '@constants/fonts';
import {StyleSheet} from 'react-native';

export const styles = StyleSheet.create({
  mainContainer: {
    flex: 1,
  },
  RKSContainer: {flex: 1, backgroundColor: 'white'},
  CAAHeader: {fontSize: 5},
  TKSCOntainer: {flex: 1, backgroundColor: 'white'},
  header: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginTop: 10,
    marginBottom: 5,
  },
  PKSContainer: {flex: 1, backgroundColor: 'white'},
  flex04: {flex: 0.4},
  flex01: {flex: 0.1},
  PKSClassNameContainer: {flex: 1, paddingLeft: 15},
  KSEmptyContainer: {marginTop: 50, alignItems: 'center'},
  KSArrowBlueContainer: {flex: 0.1, justifyContent: 'center'},
  KSHistory: {width: '100%', marginTop: 10},
  KSKonfirmasiKehadiranModal: {flex: 1, alignItems: 'center'},
  TKSDescriptionAbsenceContainer: {
    width: '100%',
    paddingHorizontal: '5%',
    marginVertical: 10,
  },
  FilterClassContainer: {marginTop: '5%', paddingHorizontal: '5%'},
  FilterClassTitleContainer: {width: '100%', alignItems: 'center'},
  FilterClassTitle: {
    fontFamily: 'Poppins-SemiBold',
    fontSize: 20,
    lineHeight: 28,
    color: Colors.dark.neutral100,
  },
  UFPContainer: {marginTop: '5%', paddingHorizontal: '5%', minHeight: 300},
  UFPTitle: {
    alignSelf: 'center',
    fontSize: 20,
    fontFamily: 'Poppins-SemiBold',
    color: Colors.dark.neutral100,
    lineHeight: 28,
  },
  UFPSubTitle: {
    fontSize: 14,
    marginTop: 20,
    marginBottom: 10,
    fontFamily: 'Poppins-Regular',
    color: Colors.dark.neutral80,
    lineHeight: 22,
  },
  UFpSubTitle2: {
    fontSize: 14,
    marginTop: 20,
    marginBottom: 10,
    fontFamily: 'Poppins-SemiBold',
    color: Colors.dark.neutral80,
    lineHeight: 22,
  },
  mt30: {
    marginVertical: 30,
  },
  mt15: {marginTop: 15},
  FilterClassClassTitle: {
    fontFamily: 'Poppins-SemiBold',
    fontSize: 14,
    lineHeight: 22,
    color: Colors.dark.neutral60,
  },
  FilterClassNameContainer: {
    marginTop: 10,
    flexDirection: 'row',
    flexWrap: 'wrap',
  },
  FilterClassBottomContainer: {
    flexDirection: 'row',
    marginTop: 30,
    marginBottom: 10,
  },
  FilterClassBottomInnerContainer: {flex: 1, paddingHorizontal: 5},
  FilterClassNameButtonChoosed: {
    paddingHorizontal: 10,
    paddingVertical: 5,
    marginVertical: 7,
    borderRadius: 20,
    backgroundColor: Colors.primary.base,
    marginRight: 10,
  },
  FilterClassNameButton: {
    paddingHorizontal: 10,
    paddingVertical: 5,
    marginVertical: 7,
    borderRadius: 20,
    backgroundColor: Colors.primary.light3,
    marginRight: 10,
  },
  FilterClassTitleChoosed: {
    fontFamily: 'Poppins-Regular',
    fontSize: 14,
    lineHeight: 22,
    color: 'white',
  },
  FilterClassTitleNotChoosed: {
    fontFamily: 'Poppins-Regular',
    fontSize: 14,
    lineHeight: 22,
    color: Colors.primary.base,
  },
  TKSWarningIconContainer: {
    flex: 0.15,
    justifyContent: 'center',
    alignItems: 'center',
  },
  TKSWarningDescriptionContainer: {flex: 1, justifyContent: 'center'},
  TKSWarningDescription: {
    fontFamily: 'Poppins-Regular',
    fontSize: 12,
    lineHeight: 16,
  },
  TKSCalendarContainer: {
    marginTop: 20,
    marginLeft: -13,
  },
  TKSAbsenceCategoryContainer: {
    marginTop: 20,
    flexDirection: 'row',
    paddingHorizontal: '10%',
  },
  TKSAttendContainer: {flex: 1, flexDirection: 'row', alignItems: 'center'},
  TKSAttendDot: {
    width: 8,
    height: 8,
    backgroundColor: Colors.success.base,
    borderRadius: 100,
  },
  TKSAttendLabel: {
    marginLeft: 8,
    fontFamily: 'Poppins-Regular',
    fontSize: 12,
    lineHeight: 18,
    marginTop: 1,
    letterSpacing: 0.25,
    color: Colors.dark.neutral100,
  },
  TKSPermitDot: {
    width: 8,
    height: 8,
    backgroundColor: Colors.orange.base,
    borderRadius: 100,
  },
  TKSPermitLabel: {
    marginLeft: 8,
    fontFamily: 'Poppins-Regular',
    fontSize: 12,
    lineHeight: 18,
    marginTop: 1,
    letterSpacing: 0.25,
    color: Colors.dark.neutral100,
  },
  TKSSickDot: {
    width: 8,
    height: 8,
    backgroundColor: Colors.danger.base,
    borderRadius: 100,
  },
  TKSSickLabel: {
    marginLeft: 8,
    fontFamily: 'Poppins-Regular',
    fontSize: 12,
    lineHeight: 18,
    marginTop: 1,
    color: Colors.dark.neutral100,
    letterSpacing: 0.25,
  },
  TKSAlphaDot: {
    width: 8,
    height: 8,
    backgroundColor: Colors.dark.neutral50,
    borderRadius: 100,
  },
  TKSAlphaLabel: {
    marginLeft: 8,
    fontFamily: 'Poppins-Regular',
    fontSize: 12,
    lineHeight: 18,
    color: Colors.dark.neutral100,
    marginTop: 1,
    letterSpacing: 0.25,
  },
  TKSWarninfContainer: {
    width: '100%',
    flexDirection: 'row',
    backgroundColor: Colors.primary.light3,
    paddingVertical: 10,
    marginBottom: 20,
    borderRadius: 10,
  },
  TKSHeaderLabel: {
    fontFamily: 'Poppins-Regular',
    fontSize: 11,
    lineHeight: 16,
  },
  mt20: {marginTop: 20},
  mr50: {marginRight: 50},
  separatorContainerStyle: {flex: 0.1, alignItems: 'center'},
  title: {
    fontFamily: Fonts.SemiBoldPoppins,
    textAlign: 'center',
    color: Colors.dark.neutral100,
    fontSize: 21,
    marginTop: 5,
  },
  DKSFilterContainer: {flexDirection: 'row', marginVertical: 12},
  historyTabContainer: {backgroundColor: 'white', flex: 1},
  mt10: {marginTop: 10},
  flex1: {flex: 1},
  DKSEditIconContainer: {flex: 1, alignItems: 'flex-end'},
  DKSAbenceCategoryLabel: {flex: 2.5, flexDirection: 'row'},
  w100: {width: '100%'},
  historyTabHeader: {
    flexDirection: 'row',
    marginTop: 15,
    marginLeft: '5%',
    marginBottom: 10,
  },
  separator2: {flex: 0.2, alignItems: 'center'},
  separator1: {flex: 0.1, alignItems: 'center'},
  navigation: {
    flexDirection: 'row',
    justifyContent: 'space-around',
    alignItems: 'center',
    gap: 8,
  },
  today_button: {
    backgroundColor: Colors.primary.light3,
    borderRadius: 25,
  },
  today_text: {
    fontSize: 15,
    paddingVertical: 8,
    paddingHorizontal: 16,
    color: Colors.primary.base,
    fontWeight: '500',
    fontFamily: Fonts.RegularPoppins,
  },
  flexRow: {
    display: 'flex',
    flexDirection: 'row',
    gap: 5,
  },
  tabKoHeaderPrimary: {
    backgroundColor: Colors.white,
    paddingHorizontal: '5%',
    paddingBottom: 10,
  },
  date: {
    alignItems: 'center',
    borderRadius: 25,
    height: 51,
    width: 51,
    textAlign: 'center',
    backgroundColor: 'transparent',
    justifyContent: 'center',
  },
  date2: {
    alignItems: 'center',
    borderRadius: 25,
    height: 55,
    width: 55,
    textAlign: 'center',
    backgroundColor: Colors.primary.base,
    justifyContent: 'center',
  },
  daycloneLabel1IsToday: {
    color: Colors.white,
    fontSize: 16,
    fontFamily: 'Poppins-Regular',
  },
  dayCloneLabel1: {
    color: Colors.dark.neutral100,
    fontSize: 16,
    fontFamily: 'Poppins-Regular',
  },
  TKSMainContainer: {flex: 1, backgroundColor: 'white'},
  TKSHeaderTitle: {
    fontFamily: 'Poppins-Regular',
    fontSize: 11,
    lineHeight: 16,
  },
  TKSWarningBox: {width: '100%', paddingHorizontal: '5%', marginVertical: 10},
  TKSWarningBoxInner: {
    width: '100%',
    flexDirection: 'row',
    backgroundColor: Colors.primary.light3,
    paddingVertical: 10,
    marginBottom: 20,
    borderRadius: 10,
  },
  TKSWarningIcon: {
    flex: 0.15,
    justifyContent: 'center',
    alignItems: 'center',
  },
  TKSDaycloneTitleIsToday: {
    color: '#1D252D',
    fontSize: 16,
    fontFamily: 'Poppins-Regular',
  },
  TKSDaycloneTitleIsSamMont: {
    color: '#1D252D',
    fontSize: 16,
    fontFamily: 'Poppins-Regular',
  },
  TKSDotDate: {
    width: 6,
    height: 6,
    borderRadius: 100,
  },
  TKSDaycloneTitle: {
    color: '#CED4DA',
    fontSize: 16,
    fontFamily: 'Poppins-Regular',
  },
  row: {
    flexDirection: 'row',
    justifyContent: 'space-around',
  },
  labelActiveStyle: {
    fontFamily: Fonts.SemiBoldPoppins,
    fontSize: 13,
    lineHeight: 22,
    letterSpacing: 0.25,
    color: Colors.primary.base,
    textTransform: 'capitalize',
  },
  dayName: {
    alignItems: 'center',
    justifyContent: 'center',
    width: 50,
    height: 30,
    color: Colors.dark.neutral100,
    fontFamily: Fonts.RegularPoppins,
  },
  ViewDay: {
    flexDirection: 'row',
    flex: 1,
    justifyContent: 'space-around',
  },
  labelInactiveStyle: {
    fontFamily: Fonts.SemiBoldPoppins,
    fontSize: 14,
    lineHeight: 22,
    letterSpacing: 0.25,
    color: Colors.dark.neutral80,
    textTransform: 'capitalize',
  },
  tabKOContainer: {
    backgroundColor: Colors.dark.neutral10,
  },
  tabKOHeaderTextStyle: {
    fontFamily: Fonts.SemiBoldPoppins,
    fontSize: 15,
    lineHeight: 24,
    color: Colors.dark.neutral100,
    marginVertical: 20,
  },
  tabKOPieIndicatorText: {
    fontFamily: Fonts.RegularPoppins,
    fontSize: 11,
    lineHeight: 16,
    color: Colors.dark.neutral100,
    marginVertical: 20,
  },
  tabKOFilterContainer: {
    width: '100%',
    flexDirection: 'row',
  },
  tabKOFilterTab: {
    flexDirection: 'row',
    backgroundColor: Colors.primary.light3,
    borderRadius: 20,
    alignItems: 'center',
    paddingVertical: 5,
    marginRight: 10,
  },
  tabKOFilterTabTextLeft: {
    marginLeft: 10,
    marginRight: 5,
    fontFamily: Fonts.SemiBoldPoppins,
    fontSize: 13,
    lineHeight: 22,
    color: Colors.primary.base,
  },
  tabKoFilterTabTextRight: {
    marginLeft: 5,
    marginRight: 10,
  },
  tabKOPengajuanButtonContainer: {
    marginTop: 5,
    backgroundColor: 'white',
    paddingVertical: 15,
    alignItems: 'center',
    paddingHorizontal: '5%',
  },
  tabKOLaporanKehadiranKelasContainer: {
    marginTop: 5,
    backgroundColor: 'white',
    paddingHorizontal: '5%',
    paddingBottom: 20,
  },
  tabKOPengajuanButton: {
    flexDirection: 'row',
    backgroundColor: Colors.white,
    alignItems: 'center',
    marginHorizontal: '1%',
    marginVertical: 8,
    borderRadius: 10,
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
    elevation: 5,
  },
  tabKOPengajuanButtonLeftContent: {
    flex: 4,
    paddingLeft: '5%',
    marginVertical: 10,
    justifyContent: 'center',
  },
  tabKOLaporanButtonLeftContent: {
    flex: 8,
    paddingLeft: '5%',
    marginVertical: 10,
    justifyContent: 'center',
  },
  tabKOPengajuanButtonRightContent: {
    flex: 1,
    alignItems: 'flex-start',
  },
  tabKOPengajuanButtonRightInnerContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
  },
  tabKOPengajuanButtonRightTextContainer: {
    marginRight: 5,
    width: 24,
    height: 24,
    backgroundColor: Colors.primary.base,
    borderRadius: 100,
    justifyContent: 'center',
    alignItems: 'center',
  },
  tabKOPengajuanButtonLeftTextTop: {
    fontFamily: Fonts.SemiBoldPoppins,
    fontSize: 15,
    lineHeight: 24,
    color: Colors.dark.neutral100,
  },
  tabKOPengajuanButtonLeftTextBottom: {
    fontFamily: Fonts.RegularPoppins,
    fontSize: 11,
    lineHeight: 16,
    color: Colors.dark.neutral80,
    marginTop: 5,
  },
  tabKOLaporanTotalMurid: {
    fontFamily: Fonts.RegularPoppins,
    fontSize: 11,
    lineHeight: 16,
    color: Colors.dark.neutral60,
    marginTop: 5,
  },
  tabKONumberText: {
    fontFamily: Fonts.SemiBoldPoppins,
    fontSize: 11,
    lineHeight: 16,
    color: Colors.white,
  },
  tabKORingkasanEmptyText1: {
    fontFamily: Fonts.SemiBoldPoppins,
    fontSize: 13,
    lineHeight: 18,
    color: Colors.dark.neutral100,
  },
  tabKORingkasanEmptyText2: {
    fontFamily: Fonts.RegularPoppins,
    fontSize: 13,
    lineHeight: 18,
    color: Colors.dark.neutral60,
    marginTop: 5,
  },
  pieContainer: {
    position: 'relative',
    width: 200,
    height: 200,
    borderRadius: 100,
    overflow: 'hidden',
  },
  pieSector: {
    width: 100,
    height: 100,
    position: 'absolute',
    borderTopLeftRadius: 100,
    borderTopRightRadius: 100,
    borderBottomLeftRadius: 100,
  },
  pieInnerCircle: {
    borderRadius: 100,
  },
  pieLabel: {
    fontWeight: 'bold',
    color: 'white',
  },
  pieDescriptionContainer: {
    width: '100%',
    justifyContent: 'center',
    flexDirection: 'row',
    paddingHorizontal: '10%',
    marginTop: 16,
  },
  pieDescriptionInnerContainer: {
    paddingHorizontal: '5%',
    alignItems: 'center',
    marginTop: 10,
  },
  pieDescriptionTitleText: {
    fontFamily: Fonts.RegularPoppins,
    textAlign: 'center',
    marginBottom: 2,
    fontSize: 11,
    lineHeight: 16,
    color: Colors.dark.neutral60,
  },
  pieDescriptionSubTitleTextGreen: {
    fontFamily: Fonts.SemiBoldPoppins,
    fontSize: 11,
    lineHeight: 16,
    color: Colors.success.light1,
    marginTop: 5,
  },
  pieDescriptionSubTitleTextYellow: {
    fontFamily: Fonts.SemiBoldPoppins,
    fontSize: 11,
    marginTop: 5,
    lineHeight: 16,
    color: Colors.orange.base,
  },
  pieDescriptionSubTitleTextGrey: {
    fontFamily: Fonts.SemiBoldPoppins,
    fontSize: 11,
    marginTop: 5,
    lineHeight: 16,
    color: Colors.dark.neutral80,
  },
  pieDescriptionSubTitleTextRed: {
    fontFamily: Fonts.SemiBoldPoppins,
    fontSize: 11,
    lineHeight: 16,
    marginTop: 5,
    color: Colors.danger.base,
  },
  TKSAttendanceTypeInner: {flex: 1, flexDirection: 'row', alignItems: 'center'},
  TKSWarningText: {
    fontFamily: 'Poppins-Regular',
    fontSize: 12,
    lineHeight: 16,
  },
  TKSRenderDaysContainer: {
    marginTop: 20,
    marginLeft: -13,
  },
  TKSAttendanceTypeContainer: {
    marginTop: 20,
    flexDirection: 'row',
    paddingHorizontal: '10%',
  },
  LKSContainer: {flex: 1, backgroundColor: 'white'},
  LKSHeaderTitle: {
    fontFamily: Fonts.RegularPoppins,
    fontSize: 10,
    lineHeight: 16,
    color: Colors?.dark?.neutral100,
  },
  LKSWarningContainer: {width: '100%', paddingHorizontal: '5%', marginTop: 15},
  LKSWarningInnerContainer: {
    flexDirection: 'row',
    width: '100%',
    backgroundColor: Colors.primary.light3,
    paddingVertical: 10,
    paddingHorizontal: 20,
    borderRadius: 10,
  },
  LKSWarningIconContainer: {flex: 0.1},
  LKSWarningDescriptionContainer: {flex: 1, justifyContent: 'center'},
  LKSWarnigDescription: {
    fontFamily: Fonts.RegularPoppins,
    color: Colors.dark.neutral100,
    fontSize: 11,
    lineHeight: 16,
  },
  LKSWarningUploadButtonContainer: {
    width: '100%',
    paddingHorizontal: '5%',
    marginTop: 20,
  },
  LKSFilterButtonContainer: {
    flexDirection: 'row',
    paddingHorizontal: '5%',
    marginTop: 15,
  },
  LKSScrollView: {marginTop: 10, paddingHorizontal: '5%'},
  LKSAttendanceCardContainer: {
    width: '98%',
    backgroundColor: 'white',
    alignSelf: 'center',
    borderRadius: 10,
    shadowColor: '#000',
    marginVertical: 10,
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
    elevation: 5,
    paddingHorizontal: 16,
    paddingVertical: 12,
  },
  LKSAttendanceCardName: {
    fontFamily: Fonts.SemiBoldPoppins,
    fontSize: 15,
    lineHeight: 24,
    color: Colors.dark.neutral100,
  },
  LKSAttendanceCardNIS: {
    fontFamily: Fonts.RegularPoppins,
    fontSize: 11,
    lineHeight: 16,
    color: Colors.dark.neutral60,
    marginBottom: 5,
  },
  LKSAttendanceCheckBarContainer: {flexDirection: 'row'},
  LKSAttendanceStatusContainer: {flex: 1, alignItems: 'center'},
  LKSAttendanceStatusText: {
    fontFamily: Fonts.RegularPoppins,
    fontSize: 13,
    lineHeight: 20,
    color: Colors.dark.neutral80,
  },
  LKSSaveButtonContainer: {
    width: '100%',
    paddingHorizontal: '5%',
    paddingVertical: 5,
  },
  TKOEmptyAttendanceDataContainerStyle: {
    width: '100%',
    alignItems: 'center',
    marginTop: 10,
    marginBottom: 10,
  },
  TKOAttendanceDataContainerStyle: {
    width: '100%',
    alignItems: 'center',
    marginTop: 20,
    marginBottom: 20,
  },
  TKOPieChartContainerStyle: {
    width: 110,
    justifyContent: 'center',
    alignItems: 'center',
  },
  TKOPieChartDescriptionContainerStyle: {
    width: '90%',
    borderRadius: 100,
    height: '90%',
    position: 'absolute',
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'white',
  },
  TKOSeparatorStyle: {
    borderLeftWidth: 1,
    height: 35,
    marginTop: 8,
    borderColor: Colors.dark.neutral40,
  },
  TTMEmptyAttendanceContainerStyle: {
    width: '100%',
    alignItems: 'center',
    marginTop: 10,
    marginBottom: 10,
  },
  TTMAttendanceDataContainerStyle: {
    width: '100%',
    alignItems: 'center',
    marginTop: 20,
    marginBottom: 20,
  },
  TTMPieChartStyle: {
    width: 110,
    justifyContent: 'center',
    alignItems: 'center',
  },
  TTMPieChartDescriptionStyle: {
    width: '90%',
    borderRadius: 100,
    height: '90%',
    position: 'absolute',
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'white',
  },
  TTMSeparatorStyle: {
    borderLeftWidth: 1,
    height: 50,
    marginTop: 8,
    borderColor: Colors.dark.neutral40,
  },
  DKSubtitleStyle: {
    fontFamily: Fonts.RegularPoppins,
    fontSize: 10,
    color: Colors.dark.neutral100,
    lineHeight: 16,
  },
  DKProfileContainerStyle: {
    width: '90%',
    alignSelf: 'center',
    backgroundColor: Colors.primary.light3,
    paddingVertical: 10,
    paddingHorizontal: 10,
    borderRadius: 10,
  },
  DKNameStyle: {
    fontFamily: Fonts.SemiBoldPoppins,
    fontSize: 15,
    lineHeight: 24,
    color: Colors.dark.neutral100,
    marginBottom: 3,
  },
  DKNISStyle: {
    fontFamily: Fonts.RegularPoppins,
    fontSize: 11,
    lineHeight: 16,
    color: Colors.dark.neutral80,
    marginBottom: 3,
  },
  DKAbsenceTypeStyle: {
    fontFamily: Fonts.SemiBoldPoppins,
    fontSize: 13,
    lineHeight: 22,
    color: Colors.dark.neutral80,
    marginBottom: 3,
  },
  DKAbsenceDateStyle: {
    fontFamily: Fonts.RegularPoppins,
    fontSize: 13,
    lineHeight: 22,
    marginTop: 5,
    marginLeft: 8,
    color: Colors.dark.neutral80,
    marginBottom: 3,
  },
  DKSContainerStyle: {
    flex: 1,
    backgroundColor: 'white',
    paddingHorizontal: '4%',
  },
  DKSSubTitleStyle: {
    fontFamily: Fonts.RegularPoppins,
    color: Colors.dark.neutral100,
    fontSize: 10,
    lineHeight: 16,
  },
  DKSTotalStudentStyle: {
    fontFamily: Fonts.RegularPoppins,
    fontSize: 13,
    lineHeight: 22,
    color: Colors.dark.neutral60,
    marginTop: 10,
  },
  DKSAttendanceCardStyle: {
    width: '98%',
    backgroundColor: 'white',
    alignSelf: 'center',
    borderRadius: 10,
    shadowColor: '#000',
    marginVertical: 10,
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
    elevation: 5,
    paddingHorizontal: 16,
    paddingVertical: 12,
  },
  DKSAttendanceNameStyle: {
    fontFamily: Fonts.SemiBoldPoppins,
    fontSize: 15,
    lineHeight: 24,
    color: Colors.dark.neutral100,
  },
  DKSEditIconStyle: {
    backgroundColor: 'white',
    padding: 5,
  },
  DKSNISStyle: {
    fontFamily: Fonts.RegularPoppins,
    fontSize: 11,
    lineHeight: 16,
    color: Colors.dark.neutral60,
    marginBottom: 5,
  },
  DKSAttendanceTypeAttendStyle: {
    fontFamily: Fonts.RegularPoppins,
    fontSize: 13,
    lineHeight: 24,
    color: Colors.dark.neutral80,
  },
  DKSAttendanceTypeAttendDescriptionStyle: {
    fontFamily: Fonts.SemiBoldPoppins,
    fontSize: 13,
    lineHeight: 24,
    color: Colors.dark.neutral100,
  },
  DKSAttendanceTypeAbsenceStyle: {
    fontFamily: Fonts.RegularPoppins,
    fontSize: 13,
    lineHeight: 24,
    color: Colors.dark.neutral80,
  },
  DKSAttendanceTypeAbsenceDescriptionStyle: {
    fontFamily: Fonts.SemiBoldPoppins,
    fontSize: 13,
    lineHeight: 24,
    color: Colors.dark.neutral100,
  },
  DKSAttendanceTypePermitStyle: {
    fontFamily: Fonts.RegularPoppins,
    fontSize: 13,
    lineHeight: 24,
    color: Colors.dark.neutral80,
  },
  DKSAttendanceTypePermitDescriptionStyle: {
    fontFamily: Fonts.SemiBoldPoppins,
    fontSize: 13,
    lineHeight: 24,
    color: Colors.dark.neutral100,
  },
  DKSAttendanceTypeSickStyle: {
    fontFamily: Fonts.RegularPoppins,
    fontSize: 13,
    lineHeight: 24,
    color: Colors.dark.neutral80,
  },
  DKSAttendanceTypeSickDescriptionStyle: {
    fontFamily: Fonts.SemiBoldPoppins,
    fontSize: 13,
    lineHeight: 24,
    color: Colors.dark.neutral100,
  },
  DKSAttendanceTypeAlphaStyle: {
    fontFamily: Fonts.RegularPoppins,
    fontSize: 13,
    lineHeight: 24,
    color: Colors.dark.neutral80,
  },
  DKSAttendanceTypeAlphaDescriptionStyle: {
    fontFamily: Fonts.SemiBoldPoppins,
    fontSize: 13,
    lineHeight: 24,
    color: Colors.dark.neutral100,
  },
  KSContainerStyle: {flex: 1, backgroundColor: 'white'},
  KSSubtitleStyle: {
    fontFamily: Fonts.RegularPoppins,
    fontSize: 10,
    lineHeight: 16,
    color: Colors.dark.neutral100,
  },
  KSHistoryButtonContainerStyle: {
    flexDirection: 'row',
    marginVertical: 10,
    backgroundColor: 'white',
    marginHorizontal: '3%',
    borderRadius: 10,
    shadowColor: '#000',
    paddingVertical: 12,
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,

    elevation: 5,
  },
  KSHistoryIconStyle: {
    flex: 0.2,
    justifyContent: 'center',
    alignItems: 'center',
  },
  KSApplicationsHostoryStyle: {
    fontFamily: Fonts.SemiBoldPoppins,
    fontSize: 13,
    lineHeight: 18,
    color: Colors.dark.neutral100,
  },
  KSApplicationHistoryCountStyle: {
    fontFamily: Fonts.RegularPoppins,
    fontSize: 11,
    marginTop: 3,
    lineHeight: 16,
    color: Colors.primary.base,
  },
  KSAbsenceApplicationStyle: {
    marginLeft: '4%',
    marginTop: 20,
    marginBottom: 5,
    fontFamily: Fonts.SemiBoldPoppins,
    color: Colors.dark.neutral100,
    fontSize: 17,
    lineHeight: 24,
  },
  KSEmptyAbsenceApplicationStyle: {
    fontFamily: Fonts.SemiBoldPoppins,
    fontSize: 13,
    lineHeight: 18,
    color: Colors.dark.neutral100,
    marginTop: 10,
  },
  KSEmptyAbsenceApplicationDescriptionStyle: {
    fontFamily: Fonts.RegularPoppins,
    fontSize: 13,
    lineHeight: 18,
    color: Colors.dark.neutral100,
    textAlign: 'center',
    marginTop: 10,
  },
  PKSAttendanceCardContainer: {
    width: '93%',
    alignSelf: 'center',
    marginVertical: 8,
    paddingVertical: 16,
    borderRadius: 10,
    backgroundColor: 'white',
    flexDirection: 'row',
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
    elevation: 5,
  },
  PKSAttendanceCardNameStyle: {
    fontFamily: Fonts.SemiBoldPoppins,
    fontSize: 13,
    lineHeight: 18,
    color: Colors.dark.neutral100,
  },
  PKSAttendanceCardApplicationCountStyle: {
    fontFamily: Fonts.RegularPoppins,
    fontSize: 11,
    lineHeight: 18,
    color: Colors.primary.base,
  },
  UploadCardContainer: {
    marginVertical: 10,
    borderWidth: 0.2,
    borderRadius: 10,
    borderColor: Colors.dark.neutral50,
    width: '100%',
    padding: '5%',
  },
  UploadCardContainerError: {
    marginVertical: 10,
    borderWidth: 1,
    borderRadius: 10,
    borderColor: Colors.danger.base,
    width: '100%',
    padding: '5%',
  },
  UploadCardFileTitle: {
    fontFamily: 'Poppins-Regular',
    marginTop: 2,
    fontSize: 13,
    lineHeight: 18,
    color: Colors.dark.neutral60,
  },
  UploadCardFileContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    marginVertical: 5,
  },
  UploadCardFileName: {
    fontFamily: 'Poppins-SemiBold',
    fontSize: 13,
    marginLeft: 3,
    lineHeight: 18,
    color: Colors.dark.neutral100,
    marginVertical: 10,
  },
  UploadCardUploadButton: {
    paddingHorizontal: 10,
    paddingVertical: 5,
    borderRadius: 20,
    backgroundColor: Colors.primary.light3,
  },
  UploadCardUploadButtonTitle: {
    fontFamily: 'Poppins-SemiBold',
    fontSize: 13,
    lineHeight: 18,
    color: Colors.primary.base,
  },
});
