import Colors from '@constants/colors';
import Fonts from '@constants/fonts';
import {StyleSheet} from 'react-native';

export const styles = StyleSheet.create({
  container: {
    borderRadius: 16,
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 1,
    },
    shadowOpacity: 0.1,
    shadowRadius: 1.84,
    elevation: 2,
    backgroundColor: Colors.white,
    marginVertical: 5,
    marginHorizontal: 2,
  },
  buttonGabung: {
    backgroundColor: Colors.primary.base,
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 25,
  },
  textBtnGabung: {
    backgroundColor: Colors.primary.base,
    color: Colors.white,
    fontFamily: 'Poppins-Regular',
    fontSize: 14,
    fontWeight: '600',
  },
  row: {
    flexDirection: 'row',
    justifyContent: 'flex-start',
    paddingBottom: 8,
  },
  live: {
    color: Colors.danger.base,
    fontFamily: 'Poppins-Regular',
    fontSize: 12,
  },
  waiting: {
    fontFamily: 'Poppins-Regular',
    fontSize: 12,
  },
  type: {
    backgroundColor: Colors.primary.light2,
    borderRadius: 15,
    paddingVertical: 4,
    paddingHorizontal: 8,
    fontWeight: '400',
    fontSize: 12,
    lineHeight: 16,
    color: Colors.primary.base,
    fontFamily: Fonts.RegularPoppins,
    marginRight: 10,
  },
  title: {
    fontWeight: '600',
    fontSize: 12,
    fontFamily: Fonts.SemiBoldPoppins,
    color: Colors.dark.neutral100,
  },
  chapter: {
    fontWeight: '600',
    fontSize: 14,
    lineHeight: 18,
    fontFamily: Fonts.SemiBoldPoppins,
    color: Colors.dark.neutral100,
  },
  btnDetail: {
    paddingVertical: 5,
    paddingHorizontal: 12,
    borderRadius: 18,
    borderColor: Colors.primary.base,
    borderWidth: 2,
    textAlign: 'center',
    height: 35,
  },
  alignCenter: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 5,
    height: 24,
  },
  btnDetailText: {
    fontWeight: '600',
    fontSize: 14,
    lineHeight: 22,
    color: Colors.primary.base,
    fontFamily: Fonts.SemiBoldPoppins,
  },
  greyText: {
    fontWeight: '400',
    fontSize: 12,
    lineHeight: 16,
    fontFamily: Fonts.RegularPoppins,
    color: Colors.dark.neutral60,
  },
  time: {
    fontWeight: '400',
    fontSize: 14,
    lineHeight: 18,
    color: Colors.dark.neutral80,
    fontFamily: Fonts.RegularPoppins,
    marginBottom: 10,
  },
  horizontalDivider: {
    borderTopWidth: 2,
    borderTopColor: '#E7EBEE',
    paddingHorizontal: 16,
    paddingVertical: 12,
  },
  dateTimeLabel: {paddingHorizontal: 16, marginBottom: 16},
  peopleContainer: {
    justifyContent: 'flex-start',
    gap: 5,
    alignItems: 'center',
    paddingHorizontal: 16,
  },
  titleContainer: {
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: 16,
  },
  titleSubContainer: {width: '80%'},
  countdownContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  onGoingContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    flex: 1,
    alignItems: 'center',
  },
});
