import Colors from '@constants/colors';
import Fonts from '@constants/fonts';
import {WINDOW_WIDTH} from '@gorhom/bottom-sheet';
import {Dimensions, StyleSheet} from 'react-native';

const window = Dimensions.get('window');
export const styles = StyleSheet.create({
  container: {flex: 1, backgroundColor: Colors.white, padding: 16},
  containerTab: {flex: 1, backgroundColor: Colors.white},
  topContainer: {flexDirection: 'row', alignItems: 'center'},
  topRight: {flexDirection: 'column', marginLeft: 16},
  contentContainerStyle: {
    flexGrow: 1,
    backgroundColor: Colors.white,
    marginBottom: 50,
  },
  topTitle: {
    fontFamily: Fonts.SemiBoldPoppins,
    fontWeight: '600',
    letterSpacing: 0.25,
    fontSize: 12,
    lineHeight: 16,
    color: Colors.dark.neutral60,
  },
  topLabel: {
    fontFamily: Fonts.SemiBoldPoppins,
    fontWeight: '600',
    letterSpacing: 1,
    fontSize: 18,
    lineHeight: 24,
    color: Colors.dark.neutral100,
    width: WINDOW_WIDTH / 1.4,
  },
  rectangle: {
    width: window.width,
    height: 4,
    backgroundColor: Colors.dark.neutral10,
    marginVertical: 16,
    marginHorizontal: -16,
  },
  taskDetail: {
    fontFamily: Fonts.SemiBoldPoppins,
    fontWeight: '600',
    letterSpacing: 0.25,
    fontSize: 14,
    lineHeight: 22,
    color: Colors.dark.neutral100,
  },
  detailContainer: {
    flexDirection: 'column',
  },
  detailTopContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  detailTitle: {
    fontFamily: Fonts.RegularPoppins,
    fontWeight: '400',
    letterSpacing: 0.25,
    fontSize: 14,
    lineHeight: 22,
    paddingTop: 8,
    color: Colors.dark.neutral60,
  },
  detailDate: {
    fontFamily: Fonts.RegularPoppins,
    fontWeight: '400',
    letterSpacing: 0.25,
    fontSize: 14,
    lineHeight: 22,
    paddingBottom: 8,
    color: Colors.dark.neutral100,
  },

  navigatorTabBarStyle: {
    height: 45,
    elevation: 0,
    borderBottomWidth: 1,
    borderBottomColor: Colors.dark.neutral20,
  },
  navigatorTabIndicatorStyle: {
    borderTopLeftRadius: 5,
    borderTopRightRadius: 5,
    height: 4,
    backgroundColor: Colors.primary.base,
  },
  labelStyle: {
    fontFamily: 'Poppins-SemiBold',
    color: Colors.dark.neutral80,
    letterSpacing: 0.25,
    lineHeight: 22,
    fontSize: 14,
    textTransform: 'capitalize',
  },
  labelActiveStyle: {
    fontFamily: 'Poppins-SemiBold',
    color: Colors.primary?.base,
    letterSpacing: 0.25,
    lineHeight: 22,
    fontSize: 14,
    textTransform: 'capitalize',
  },
  notFoundContainer: {
    flexDirection: 'column',
    alignSelf: 'center',
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: 86,
  },
  notFoundLabel: {
    fontFamily: Fonts.SemiBoldPoppins,
    fontWeight: '600',
    letterSpacing: 1,
    fontSize: 16,
    lineHeight: 20,
    paddingTop: 12,
    color: Colors.dark.neutral100,
    textAlign: 'center',
  },
  notFoundText: {
    fontFamily: Fonts.RegularPoppins,
    fontWeight: '400',
    letterSpacing: 1,
    fontSize: 14,
    lineHeight: 18,
    paddingTop: 6,
    color: Colors.dark.neutral100,
    textAlign: 'center',
  },
  bottomContainer: {
    position: 'absolute',
    bottom: 0,
    justifyContent: 'center',
    alignItems: 'center',
    padding: 16,
  },
  buttonStyle: {
    alignSelf: 'center',
    width: window.width * 0.9,
  },
  textFinish: {
    fontFamily: Fonts.SemiBoldPoppins,
    fontSize: 14,
    lineHeight: 22,
    letterSpacing: 0.25,
    color: Colors.dark.neutral80,
    fontWeight: '600',
  },
  popUpFinishContainer: {
    alignItems: 'center',
    marginBottom: 18,
  },
  __wrapIconAndText: {
    flexDirection: 'row',
    marginTop: 4,
    alignItems: 'center',
    gap: 12,
  },
  __regularText: {
    fontFamily: Fonts.RegularPoppins,
    fontWeight: '400',
    fontSize: 16,
    lineHeight: 24,
    letterSpacing: 1,
    color: Colors.dark.neutral100,
  },
  swipeUpContainer: {
    paddingHorizontal: 16,
    paddingBottom: 16,
  },
});
