import {StyleSheet} from 'react-native';
import Colors from '@constants/colors';
import Fonts from '@constants/fonts';
export const styles = StyleSheet.create({
  scrollContentContainerStyle: {
    flexGrow: 1,
    // backgroundColor: 'red',
  },
  notif: {
    width: '100%',
    flexDirection: 'row',
    height: 60,
    backgroundColor: Colors.primary.base,
    borderRadius: 10,
    marginTop: 50,
  },
  notifContent: {
    justifyContent: 'center',
    marginLeft: 10,
  },
  box: {
    borderWidth: 1,
    padding: 30,
    borderRadius: 30,
    alignItems: 'center',
    borderColor: '#CED4DA',
    marginBottom: 10,
  },
  textNotif: {
    fontFamily: 'Poppins-Bold',
    fontWeight: '600',
    fontSize: 14,
    lineHeight: 22,
    letterSpacing: 0.25,
    color: Colors.white,
  },
  coins: {
    width: 12,
    height: 12,
  },
  bgNotif: {
    backgroundColor: '#FFCE00',
    padding: 20,
    borderTopLeftRadius: 10,
    borderBottomLeftRadius: 10,
    borderTopRightRadius: 50,
    borderBottomRightRadius: 50,
    justifyContent: 'center',
  },
  contentContainerStyle: {
    width: '100%',
    flexDirection: 'row',
    flexWrap: 'wrap',
  },
  notifJawaban: {
    flexDirection: 'row',
    alignItems: 'center',
    borderBottomRightRadius: 10,
    borderTopRightRadius: 10,
  },
  contentProgress: {
    backgroundColor: Colors.primary.light3,
    borderRadius: 10,
    padding: 15,
    margin: 5,
    justifyContent: 'flex-start',
    width: '100%',
  },
  text: {
    fontFamily: 'Poppins-Regular',
    fontStyle: 'normal',
    fontWeight: '400',
    fontSize: 12,
    lineHeight: 16,
    letterSpacing: 0.25,
    color: '#1D252D',
  },
  subCard: {
    width: '33%',
    alignItems: 'center',
    marginTop: 20,
    justifyContent: 'center',
  },
  txtTanya: {
    fontFamily: 'Poppins-Regular',
    fontStyle: 'normal',
    fontWeight: '400',
    fontSize: 12,
    lineHeight: 16,
    letterSpacing: 0.25,
    color: '#1D252D',
  },
  botButton: {
    borderRadius: 30,
    justifyContent: 'center',
    flexDirection: 'row',
    padding: 10,
    width: '95%',
    backgroundColor: Colors.primary.base,
    position: 'absolute',
    bottom: 10,
    alignSelf: 'center',
  },
  txtButton: {
    fontFamily: 'Poppins-Bold',
    fontSize: 14,
    lineHeight: 22,
    letterSpacing: 0.25,
    color: Colors.white,
    marginLeft: 5,
    textAlignVertical: 'center',
    top: 2,
  },
  title: {
    fontFamily: Fonts.SemiBoldPoppins,
    fontSize: 16,
    lineHeight: 24,
    display: 'flex',
    alignItems: 'center',
    letterSpacing: 0.01,
    color: '#1D252D',
  },
  txtCoin: {
    fontFamily: 'Poppins-Regular',
    fontStyle: 'normal',
    fontWeight: '400',
    fontSize: 12,
    lineHeight: 16,
    display: 'flex',
    alignItems: 'center',
    letterSpacing: 0.25,
    color: '#4D545C',
  },
  subTitle: {
    fontFamily: Fonts.SemiBoldPoppins,
    fontSize: 12,
    lineHeight: 16,
    display: 'flex',
    alignItems: 'center',
    letterSpacing: 0.25,
    color: '#868E96',
    marginVertical: 5,
  },
  row: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    width: 51,
  },
  rowSwipe: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 10,
  },
  button: {
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 12,
    paddingVertical: 5,
    paddingLeft: 24,
    paddingRight: 24,
    width: '100%',
    backgroundColor: '#FFFFFF',
    borderRadius: 30,
    marginTop: 15,
    justifyContent: 'space-between',
  },
  buttonContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginVertical: 5,
  },
  subContainer: {
    flexDirection: 'row',
    width: '80%',
    alignItems: 'center',
  },
  coin: {
    fontFamily: 'Poppins-Bold',
    fontStyle: 'normal',
    fontWeight: '600',
    fontSize: 14,
    lineHeight: 22,
    display: 'flex',
    alignItems: 'center',
    letterSpacing: 0.25,
    color: Colors.primary.base,
  },
  sesi: {
    fontFamily: 'Poppins-Regular',
    fontStyle: 'normal',
    fontWeight: '400',
    fontSize: 12,
    lineHeight: 16,
    textAlign: 'center',
    letterSpacing: 0.25,
    color: Colors.primary.base,
  },
  coinRow: {
    flexDirection: 'row',
    alignItems: 'center',
    borderRadius: 20,
    paddingHorizontal: 6,
    paddingVertical: 2,
    height: 20,
    backgroundColor: Colors.white,
    position: 'absolute',
    alignContent: 'center',
  },
  shadowProp: {
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
    elevation: 5,
  },
  bgBlueOrnament: {
    resizeMode: 'cover',
    width: '100%',
    position: 'absolute',
    zIndex: -1,
    backgroundColor: '#F9FCFF',
  },
  headerContainer: {width: '100%', alignItems: 'center'},
  cardContainer: {
    marginTop: 16,
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
    paddingHorizontal: 16,
    paddingVertical: 10,
    backgroundColor: Colors.white,
  },
  container: {
    width: '100%',
  },

  headerWrapperSecond: {
    flexDirection: 'row',
    paddingHorizontal: 16,
    paddingVertical: 10,
  },
  headerWrapperSecondSubTitle: {
    width: '100%',
    height: 18,
    fontFamily: 'Poppins-Regular',
    fontStyle: 'normal',
    fontWeight: '400',
    fontSize: 14,
    lineHeight: 18,
    textAlign: 'center',
    letterSpacing: 0.25,

    color: '#FFFFFF',
  },
  iconContainer: {
    width: 50,
    height: 50,
    backgroundColor: Colors.white,
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 100,
  },
  titleLevel: {
    fontSize: 24,
    alignSelf: 'center',
    marginTop: 10,
    fontFamily: 'Poppins-Bold',
    color: Colors.dark.neutral100,
  },
  subTitleLevel: {
    fontSize: 14,
    alignSelf: 'center',
    marginTop: 10,
    fontFamily: 'Poppins-Regular',
    color: Colors.dark.neutral100,
  },
  buttonActive: {
    justifyContent: 'center',
    alignItems: 'center',
    paddingVertical: 4,
    paddingHorizontal: 8,
    flexDirection: 'row',
    width: 110,
    height: 32,
    backgroundColor: '#0055B8',
    borderRadius: 20,
    marginHorizontal: 8,
  },
  bottomContainer: {
    marginVertical: 16,
  },
  bottomTitle: {
    fontFamily: Fonts.SemiBoldPoppins,
    color: Colors.dark.neutral100,
    fontSize: 14,
    lineHeight: 18,
    fontWeight: '600',
    letterSpacing: 0.25,
  },
  dotContainer: {
    flexDirection: 'row',
    margin: 20,
    alignSelf: 'center',
  },
  dot: {
    width: 8,
    height: 8,
    borderRadius: 5,
    marginHorizontal: 5,
    backgroundColor: Colors.primary.base,
  },
  activeDot: {
    backgroundColor: Colors.primary.base,
  },
  check: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'flex-start',
    alignSelf: 'flex-start',
  },
  checkBox: {
    borderWidth: 1,
    width: 24,
    height: 24,
    borderColor: Colors.primary.base,
    borderRadius: 5,
    marginRight: 10,
    backgroundColor: Colors.primary.base,
    alignItems: 'center',
    justifyContent: 'center',
  },
  unCheckBox: {
    borderWidth: 1,
    width: 24,
    height: 24,
    borderColor: Colors.dark.neutral50,
    borderRadius: 5,
    marginRight: 10,
  },
  textCoin: {
    fontFamily: 'Poppins-Regular',
    fontSize: 11,
    marginLeft: 5,
    color: Colors.dark.neutral80,
  },
});
