import Colors from '@constants/colors';
import Fonts from '@constants/fonts';
import {StyleSheet} from 'react-native';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
  },
  indexContainer: {flex: 1, backgroundColor: 'white'},
  indexBodyContainer: {width: '100%', marginTop: 10},
  imageStyle: {width: 40, height: 40, borderRadius: 100},
  historyButtonStyle: {
    flexDirection: 'row',
    marginVertical: 10,
    backgroundColor: 'white',
    marginHorizontal: '3%',
    borderRadius: 10,
    shadowColor: '#000',
    paddingVertical: 12,
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,

    elevation: 5,
  },
  blueArrowIconContainer: {flex: 0.1, justifyContent: 'center'},
  attendanceListContainer: {paddingHorizontal: 15, marginBottom: 10},
  historyIcon: {width: 25, height: 25},
  historyButtonContainer: {flex: 1, justifyContent: 'center'},
  marginRight50: {marginRight: 50},
  marginBottom200: {marginBottom: 200},
  historyIconContainer: {
    flex: 0.2,
    justifyContent: 'center',
    alignItems: 'center',
  },
  seeDetailButton: {position: 'absolute', right: 20},
  flex15: {flex: 1.5},
  hstoryButtonTitleStyle: {
    fontFamily: Fonts.SemiBoldPoppins,
    fontSize: 14,
    lineHeight: 18,
    letterSpacing: 0.25,
  },
  absenceCountStyle: {
    fontFamily: Fonts.SemiBoldPoppins,
    fontSize: 18,
    lineHeight: 24,
  },
  emptyContainerStyle: {
    width: '100%',
    alignItems: 'center',
    marginTop: 46,
    marginBottom: 10,
  },
  emptyDescriptionStyle: {
    fontFamily: Fonts.SemiBoldPoppins,
    fontSize: 14,
    lineHeight: 18,
    color: Colors.dark.neutral100,
  },
  emptyDescription2Style: {
    fontFamily: Fonts.RegularPoppins,
    fontSize: 14,
    lineHeight: 18,
    textAlign: 'center',
    marginTop: 6,
    color: Colors.dark.neutral60,
  },
  attendanceCardContainerStyle: {
    width: '100%',
    backgroundColor: 'white',
    alignItems: 'center',
    justifyContent: 'center',
    marginVertical: 10,
  },
  attendanceCardInnerContainerStyle: {
    width: '90%',
    backgroundColor: 'white',
    borderRadius: 10,
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,

    elevation: 5,
  },
  leftContentContainerStyle: {
    width: '100%',
    flexDirection: 'row',
    marginBottom: 10,
    marginTop: 15,
  },
  avatarContainerStyle: {
    flex: 0.5,
    alignItems: 'center',
  },
  fullnameStyle: {
    fontFamily: 'Poppins-SemiBold',
    fontSize: 13,
    lineHeight: 18,
    color: Colors.dark.neutral100,
  },
  registNumberStyle: {
    fontFamily: 'Poppins-Regular',
    fontSize: 10,
    lineHeight: 16,
    color: Colors.dark.neutral80,
    marginTop: 3,
  },
  statusContainerStyle: {
    flex: 1,
    alignItems: 'flex-end',
    paddingRight: 15,
  },
  requestedDateContainerStyle: {
    fontFamily: 'Poppins-Regular',
    fontSize: 11,
    lineHeight: 16,
    color: Colors.dark.neutral60,
  },
  statusTextContainerStyle: {
    minWidth: 20,
    paddingVertical: 5,
    alignItems: 'flex-start',
  },
  statusApprovedBgColorStyle: {
    backgroundColor: Colors.success.light2,
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: 10,
    paddingVertical: 2,
    borderRadius: 20,
  },
  statusRejectedBgColorStyle: {
    backgroundColor: Colors.danger.light2,
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: 10,
    paddingVertical: 2,
    borderRadius: 20,
  },
  statusPendingBgColorStyle: {
    backgroundColor: Colors.secondary.light2,
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: 10,
    paddingVertical: 2,
    borderRadius: 20,
  },
  statusApprovedTextColorStyle: {
    fontFamily: 'Poppins-SemiBold',
    lineHeight: 16,
    fontSize: 11,
    color: Colors.success.base,
  },
  statusRejectedTextColorStyle: {
    fontFamily: 'Poppins-SemiBold',
    lineHeight: 16,
    fontSize: 11,
    color: Colors.danger.base,
  },
  statusPendingTextColorStyle: {
    fontFamily: 'Poppins-SemiBold',
    lineHeight: 16,
    fontSize: 11,
    color: Colors.orange.dark1,
  },
  startDateStyle: {
    paddingLeft: 15,
    fontFamily: 'Poppins-SemiBold',
    fontSize: 11,
    lineHeight: 16,
    color: Colors.dark.neutral80,
    marginTop: 5,
    marginBottom: 15,
  },
  actionButtonContainerStyle: {
    width: '100%',
    flexDirection: 'row',
    marginBottom: 20,
  },
  rejectButtonStyle: {
    flex: 1,
    justifyContent: 'center',
    paddingLeft: 15,
  },
  approveButtonStyle: {
    flex: 1,
    justifyContent: 'center',
    paddingLeft: 5,
    paddingRight: 15,
  },
  goDetailButtonStyle: {
    width: '100%',
    height: 50,
    backgroundColor: Colors.primary.light4,
    borderBottomEndRadius: 10,
    borderBottomStartRadius: 10,
    flexDirection: 'row',
    alignItems: 'center',
  },
  goDetailButtonLabelStyle: {
    paddingLeft: 15,
    fontFamily: 'Poppins-SemiBold',
    fontSize: 13,
    lineHeight: 22,
    color: Colors.primary.base,
  },
  separatorStyle: {
    width: '100%',
    height: 4,
    backgroundColor: Colors.dark.neutral10,
    marginVertical: 16,
  },
});
