export const VIRTUAL_MEETING_STATE_UPDATE_TITLE =
  'VIRTUAL_MEETING_STATE_UPDATE_TITLE';

export const VIRTUAL_MEETING_STATE_UPDATE_DESCRIPTION =
  'VIRTUAL_MEETING_STATE_UPDATE_DESCRIPTION';

export const VIRTUAL_MEETING_STATE_UPDATE_TIME_START =
  'VIRTUAL_MEETING_STATE_UPDATE_TIME_START';

export const VIRTUAL_MEETING_STATE_UPDATE_TIME_END =
  'VIRTUAL_MEETING_STATE_UPDATE_TIME_END';

export const VIRTUAL_MEETING_STATE_UPDATE_DURATION =
  'VIRTUAL_MEETING_STATE_UPDATE_DURATION';

export const VIRTUAL_MEETING_STATE_UPDATE_MEETING_URL =
  'VIRTUAL_MEETING_STATE_UPDATE_MEETING_URL';

export const VIRTUAL_MEETING_STATE_UPDATE_PARTICIPANTS =
  'VIRTUAL_MEETING_STATE_UPDATE_PARTICIPANTS';
export const VIRTUAL_MEETING_STATE_UPDATE_PARTICIPANTS_ALL =
  'VIRTUAL_MEETING_STATE_UPDATE_PARTICIPANTS_ALL';

export const VIRTUAL_MEETING_STATE_UPDATE_DESTROY =
  'VIRTUAL_MEETING_STATE_UPDATE_DESTROY';
