import Colors from '@constants/colors';
import Fonts from '@constants/fonts';
import {Dimensions, StyleSheet} from 'react-native';

const window = Dimensions.get('window');
export const styles = StyleSheet.create({
  container: {
    backgroundColor: Colors.primary.background,
    flex: 1,
  },
  subContainer: {
    flex: 1,
    backgroundColor: Colors.primary.background,
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
    paddingVertical: 16,
  },
  contentContainerStyle: {
    flexGrow: 1,
    flexDirection: 'column',
    backgroundColor: Colors.primary.background,
  },
  bgBlueOrnament: {
    resizeMode: 'cover',
    width: '100%',
    position: 'absolute',
    zIndex: -1,
    backgroundColor: '#F9FCFF',
  },
  styleLabel: {
    fontWeight: '600',
    fontSize: 16,
    lineHeight: 20,
    textAlign: 'center',
    letterSpacing: 1,
    color: Colors.white,
  },
  profileContainer: {
    flexDirection: 'row',
    marginTop: 20,
    marginBottom: 16,
    paddingHorizontal: 16,
  },
  userImage: {
    width: 56,
    height: 56,
    borderRadius: 100,
    marginLeft: 4,
    borderWidth: 2,
    borderColor: Colors.secondary.base,
  },
  profileRightContainer: {
    flexDirection: 'column',
    marginLeft: 20,
    width: '80%',
  },
  profileTitle: {
    fontWeight: '600',
    fontSize: 16,
    lineHeight: 24,
    letterSpacing: 1,
    color: Colors.dark.neutral100,
    fontFamily: Fonts.SemiBoldPoppins,
  },
  profileLabel: {
    fontWeight: '400',
    fontSize: 14,
    lineHeight: 22,
    letterSpacing: 0.25,
    color: Colors.dark.neutral100,
    fontFamily: Fonts.RegularPoppins,
  },
  descriptionContainer: {
    flexDirection: 'column',
    alignSelf: 'flex-start',
    marginTop: 28,
    marginBottom: 36,
    paddingHorizontal: 16,
  },
  descriptionTitle: {
    fontWeight: '600',
    fontSize: 14,
    lineHeight: 22,
    letterSpacing: 0.25,
    color: Colors.dark.neutral100,
    fontFamily: Fonts.SemiBoldPoppins,
  },
  descriptionRow: {
    flexDirection: 'row',
  },
  descriptionText: {
    fontWeight: '400',
    fontSize: 12,
    lineHeight: 16,
    letterSpacing: 0.25,
    color: Colors.dark.neutral100,
    fontFamily: Fonts.RegularPoppins,
  },
  descriptionContent: {
    marginTop: 4,
    paddingRight: 16,
  },
  viewMore: {
    fontWeight: '600',
    fontSize: 12,
    lineHeight: 16,
    letterSpacing: 0.25,
    color: Colors.primary.base,
    fontFamily: Fonts.SemiBoldPoppins,
    paddingTop: 8,
  },
  rectangle: {
    width: window.width * 1,
    height: 8,
    backgroundColor: Colors.dark.neutral20,
  },
  successfullFigure: {
    flexDirection: 'column',
    marginVertical: 16,
    paddingHorizontal: 16,
  },
  successfullFigureSroll: {
    marginTop: 16,
  },
  professionRecomendRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  professionRecomendContainer: {
    marginTop: 8,
    paddingHorizontal: 16,
  },
  professionRecomendScroll: {
    marginTop: 16,
  },
  viewAll: {
    fontWeight: '600',
    fontSize: 12,
    lineHeight: 16,
    letterSpacing: 0.25,
    color: Colors.dark.neutral80,
    fontFamily: Fonts.RegularPoppins,
  },
  successfullCharacterPicture: {
    borderRadius: 10,
    backgroundColor: Colors.dark.neutral50,
    width: window.width * 0.35,
    height: 160,
    marginRight: 20,
    overflow: 'hidden',
  },
  successfullCharacterPictureOverlay: {
    position: 'absolute',
    width: window.width * 0.35,
    height: 160,
    borderRadius: 10,
    overflow: 'hidden',
  },
  textCharacterPicture: {
    padding: 12,
    flex: 1,
    justifyContent: 'flex-end',
  },
  titleCharacterPicture: {
    fontWeight: '600',
    fontSize: 14,
    lineHeight: 18,
    letterSpacing: 0.25,
    color: Colors.white,
    fontFamily: Fonts.SemiBoldPoppins,
  },
  labelCharacterPicture: {
    fontWeight: '400',
    fontSize: 11,
    lineHeight: 16,
    letterSpacing: 0.25,
    color: Colors.white,
    fontFamily: Fonts.RegularPoppins,
  },
  navigatorTabBarStyle: {
    height: 45,
    elevation: 0,
    borderBottomWidth: 1,
    borderBottomColor: Colors.dark.neutral20,
  },
  navigatorTabIndicatorStyle: {
    borderTopLeftRadius: 5,
    borderTopRightRadius: 5,
    height: 4,
    backgroundColor: Colors.primary.base,
  },
  labelStyle: {
    fontFamily: Fonts.SemiBoldPoppins,
    color: Colors.dark.neutral80,
    letterSpacing: 0.25,
    lineHeight: 22,
    fontSize: 14,
    textTransform: 'capitalize',
  },
  labelActiveStyle: {
    fontFamily: Fonts.SemiBoldPoppins,
    color: Colors.primary?.base,
    letterSpacing: 0.25,
    lineHeight: 22,
    fontSize: 14,
    textTransform: 'capitalize',
  },
  containerTab: {
    height: 700,
    paddingHorizontal: 8,
  },
  assetStyle: {width: '100%', height: 184},
});
