export const Keys = {
  token: 'TOKEN',
  objectToken: 'OBJECT-TOKEN',
  deviceUser: 'DEVICE-USER',
  dataUser: 'DATAUSER',
  onboarded: 'ONBOARDED',
  coachmarkedHome: 'COACHMARKED_HOME',
  coachmarkedCart: 'COACHMARKED-COIN',
  coachmarkedKepsek: 'COACHMARKED-KEPSEK',
  coachmarkedAdmin: 'COACHMARKED-ADMIN',
  coachmarkedGuru: 'COACHMARKED-GURU',
  coachmarkedParent: 'COACHMARKED-PARENT',
  coachmarkedLeaderBoardMurid: 'COACHMARKED-LEADERBOARD-MURID',
  coachmarkedDetailSoal: 'COACHMARKED-DETAIL-SOAL',
  curriculumGuru: 'CURRICULUM-GURU',
  FTUESoal: 'FTUE-SOAL',
  FTUEGuru: 'FTUE-GURU',
  FTUETanya: 'FTUE-TANYA',
  FTUELearn: 'FTUE-LEARN',
  profession: 'PROFESSION',
  majors: 'MAJORS',
  localSavedVideo: 'LOCAL-SAVED-VIDEO',
  deviceId: 'DEVICE-ID',
  lastNotificationId: 'LAST_NOTIFICATION-ID',
  notificationData: 'NOTIFICATION-DATA',

  //coachmark
  coachmark_mobile_dashboard: 'coachmark_mobile_dashboard',
  coachmark_mobile_leaderboard: 'coachmark_mobile_leaderboard',
  coachmark_mobile_schedule: 'coachmark_mobile_schedule',
  coachmark_mobile_chapter: 'coachmark_mobile_chapter',
  coachmark_mobile_regular: 'coachmark_mobile_regular',
  coachmark_mobile_tanya: 'coachmark_mobile_tanya',
  coachmark_mobile_coin: 'coachmark_mobile_coin',
  coachmark_mobile_order: 'coachmark_mobile_order',
  coachmark_mobile_parent: 'coachmark_mobile_parent',
  coachmark_mobile_soal: 'coachmark_mobile_soal',
  popup_mobile_tanya: 'popup_mobile_tanya',
  popup_mobile_ptn: 'popup_mobile_ptn',

  ios_shared_keys: '1f0c232354584724836aeecd0cf4f462',
};

export const StorageKeys = {
  ...Keys,
  blogKeys: 'BLOG_KEYS',
  promoKeys: 'PROMO_KEYS',
  iapTransactionKeys: 'IAP_TRANSACTION_KEYS',
  isAdmin: 'IS_ADMIN',
};
