export const mockSoalData: IUjianCheck = {
  _id: '65b8bd760d6d688a347cda1d',
  paper: {
    id: 10126,
    name: 'Camputra',
    instructions: '',
    descriptions: '',
    total_question: 6,
    total_answered: 2,
    total_essay: 1,
    total_multiple: 5,
    total_multiple_complex: 0,
    total_essay_short: 0,
    total_matchmaking: 0,
    total_true_false: 0,
    chapter: {
      id: 0,
      name: 'Camputra',
    },
    subject: {
      id: 126,
      name: 'Camputra',
    },
    class: {
      id: 126,
      name: 'Kelas 8',
    },
    question_package_service: {
      id: 0,
      name: '',
    },
    original_questions: [
      {
        id: 550627,
        orig_order: 1,
        order: 1,
        questions:
          "<link href='https://fonts.googleapis.com/css?family=Poppins' rel='stylesheet'><div style='display: flex; flex-direction: column;'><p style='color: black; font-family: Poppins;'><b>Perhatikan kutipan berikut!</b></p> <p style='color: black; font-family: Poppins;'>Jakarta, CNN Indonesia -- Almarhum Bacharuddin Jusuf Habibie, Kamis (12/9) siang ini dimakamkan di Taman Makam Pahalawan (TMP) Kalibata, Jakarta Selatan. <b>Posesi pemakaman Habibie di TMP Kalibata dilakukan secara militer dan dipimpin Presiden Joko Widodo sebagai inspektur upacara</b>.</p> <p style='color: black; font-family: Poppins;'>Sumber:</p> <p style='color: black; font-family: Poppins;'>https://www.cnnindonesia.com/nasional/</p> <p style='color: black; font-family: Poppins;'>20190912124908-20-429878/habibie-presiden-ri-pertama-yang-dimakamkan-di-tmp-kalibata</p></div><span data-converted='true'></span> <div style='display: flex; flex-direction: column;'><p style='color: black; font-family: Poppins;'>Unsur berita yang digunakan dalam kalimat bercetak tebal tersebut adalah ... .</p></div>",
        instructions:
          "<p style='color: black; font-family: Poppins;'><b>Perhatikan kutipan berikut!</b></p> <p style='color: black; font-family: Poppins;'>Jakarta, CNN Indonesia -- Almarhum Bacharuddin Jusuf Habibie, Kamis (12/9) siang ini dimakamkan di Taman Makam Pahalawan (TMP) Kalibata, Jakarta Selatan. <b>Posesi pemakaman Habibie di TMP Kalibata dilakukan secara militer dan dipimpin Presiden Joko Widodo sebagai inspektur upacara</b>.</p> <p style='color: black; font-family: Poppins;'>Sumber:</p> <p style='color: black; font-family: Poppins;'>https://www.cnnindonesia.com/nasional/</p> <p style='color: black; font-family: Poppins;'>20190912124908-20-429878/habibie-presiden-ri-pertama-yang-dimakamkan-di-tmp-kalibata</p>",
        marks: 1,
        file_id: '',
        chapter: {
          id: 0,
          name: '',
        },
        subject: {
          id: 126,
          name: '',
        },
        class: {
          id: 126,
          name: '',
        },
        question_level: {
          id: 3,
          name: '',
        },
        question_package_service: {
          id: 0,
          name: '',
        },
        school: {
          id: 0,
          name: '',
        },
        tag: 'Menganalisis',
        question_type: {
          id: 1,
          name: '',
        },
        options: [
          {
            id: 2265789,
            answer: '<p >Bagaimana</p>',
            orig_key: 'A',
            key: 'A',
            is_correct: true,
            question_id: 550627,
            file_id: '',
            is_choosed: true,
          },
          {
            id: 2265790,
            answer: '<p >Di mana</p>',
            orig_key: 'B',
            key: 'B',
            is_correct: false,
            question_id: 550627,
            file_id: '',
            is_choosed: false,
          },
          {
            id: 2265791,
            answer: '<p >Apa</p>',
            orig_key: 'C',
            key: 'C',
            is_correct: false,
            question_id: 550627,
            file_id: '',
            is_choosed: false,
          },
          {
            id: 2265792,
            answer: '<p >Kapan</p>',
            orig_key: 'D',
            key: 'D',
            is_correct: false,
            question_id: 550627,
            file_id: '',
            is_choosed: false,
          },
        ],
        selected_option: {
          id: 2265789,
          answer: '<p >Bagaimana</p>',
          orig_key: 'A',
          key: 'A',
          is_correct: true,
          question_id: 550627,
          file_id: '',
          is_choosed: true,
        },
        user_input: '',
        status: 'answered',
        discussion:
          "<span data-converted='true'></span> <div style='display: flex; flex-direction: column;'><p style='color: black; font-family: Poppins;'>Unsur berita yang digunakan dalam kalimat bercetak tebal tersebut adalah <i>bagaimana</i>. Hal ini karena kutipan kalimat yang bercetak tebal tersebut menunjukkan proses pemakaman Bapak Habibie.</p>     <p style='color: black; font-family: Poppins;'> </p>   <p style='color: black; font-family: Poppins;'> </p></div>",
        point: 1,
        is_scored: true,
      },
      {
        id: 550628,
        orig_order: 2,
        order: 2,
        questions:
          "<link href='https://fonts.googleapis.com/css?family=Poppins' rel='stylesheet'><div style='display: flex; flex-direction: column;'><p style='color: black; font-family: Poppins;'><b>Perhatikan kutipan berikut!</b></p> <p style='color: black; font-family: Poppins;'>Jakarta, CNN Indonesia -- Almarhum Bacharuddin Jusuf Habibie, Kamis (12/9) siang ini <b>dimakamkan di Taman Makam Pahalawan (TMP) Kalibata, Jakarta Selatan</b>. Posesi pemakaman Habibie di TMP Kalibata dilakukan secara militer dan dipimpin Presiden Joko Widodo sebagai inspektur upacara.</p> <p style='color: black; font-family: Poppins;'>Sumber:</p> <p style='color: black; font-family: Poppins;'>https://www.cnnindonesia.com/nasional/</p> <p style='color: black; font-family: Poppins;'>20190912124908-20-429878/habibie-presiden-ri-pertama-yang-dimakamkan-di-tmp-kalibata</p></div><span data-converted='true'></span> <div style='display: flex; flex-direction: column;'><p style='color: black; font-family: Poppins;'>Unsur berita yang digunakan dalam kalimat bercetak tebal tersebut adalah ... .</p></div>",
        instructions:
          "<p style='color: black; font-family: Poppins;'><b>Perhatikan kutipan berikut!</b></p> <p style='color: black; font-family: Poppins;'>Jakarta, CNN Indonesia -- Almarhum Bacharuddin Jusuf Habibie, Kamis (12/9) siang ini <b>dimakamkan di Taman Makam Pahalawan (TMP) Kalibata, Jakarta Selatan</b>. Posesi pemakaman Habibie di TMP Kalibata dilakukan secara militer dan dipimpin Presiden Joko Widodo sebagai inspektur upacara.</p> <p style='color: black; font-family: Poppins;'>Sumber:</p> <p style='color: black; font-family: Poppins;'>https://www.cnnindonesia.com/nasional/</p> <p style='color: black; font-family: Poppins;'>20190912124908-20-429878/habibie-presiden-ri-pertama-yang-dimakamkan-di-tmp-kalibata</p>",
        marks: 1,
        file_id: '',
        chapter: {
          id: 0,
          name: '',
        },
        subject: {
          id: 126,
          name: '',
        },
        class: {
          id: 126,
          name: '',
        },
        question_level: {
          id: 3,
          name: '',
        },
        question_package_service: {
          id: 0,
          name: '',
        },
        school: {
          id: 0,
          name: '',
        },
        tag: 'Menganalisis',
        question_type: {
          id: 1,
          name: '',
        },
        options: [
          {
            id: 2265793,
            answer: '<p >Siapa</p>',
            orig_key: 'A',
            key: 'A',
            is_correct: false,
            question_id: 550628,
            file_id: '',
            is_choosed: false,
          },
          {
            id: 2265794,
            answer: '<p >Bagaimana</p>',
            orig_key: 'B',
            key: 'B',
            is_correct: false,
            question_id: 550628,
            file_id: '',
            is_choosed: false,
          },
          {
            id: 2265795,
            answer: '<p >Kapan</p>',
            orig_key: 'C',
            key: 'C',
            is_correct: false,
            question_id: 550628,
            file_id: '',
            is_choosed: false,
          },
          {
            id: 2265796,
            answer: '<p >Di mana</p>',
            orig_key: 'D',
            key: 'D',
            is_correct: true,
            question_id: 550628,
            file_id: '',
            is_choosed: false,
          },
        ],
        selected_option: {
          id: 0,
          answer: '',
          orig_key: '',
          key: '',
          is_correct: false,
          question_id: 0,
          file_id: '',
          is_choosed: false,
        },
        user_input: ' ',
        status: '',
        discussion:
          "<span data-converted='true'></span> <div style='display: flex; flex-direction: column;'><p style='color: black; font-family: Poppins;'>Unsur berita yang digunakan dalam kalimat bercetak tebal tersebut adalah <i>di mana</i>. Hal ini karena kutipan kalimat yang bercetak tebal tersebut menunjukkan tempat dimakamkannya Bapak Habibie.</p>     <p style='color: black; font-family: Poppins;'> </p>   <p style='color: black; font-family: Poppins;'> </p></div>",
        point: 0,
        is_scored: false,
      },
      {
        id: 550629,
        orig_order: 3,
        order: 3,
        questions:
          "<link href='https://fonts.googleapis.com/css?family=Poppins' rel='stylesheet'><div style='display: flex; flex-direction: column;'><p style='color: black; font-family: Poppins;'><b>Perhatikan kutipan berikut!</b></p> <p style='color: black; font-family: Poppins;'>Jakarta, CNN Indonesia -- Almarhum Bacharuddin Jusuf Habibie, <b>Kamis (12/9) siang ini dimakamkan</b> di Taman Makam Pahalawan (TMP) Kalibata, Jakarta Selatan. Posesi pemakaman Habibie di TMP Kalibata dilakukan secara militer dan dipimpin Presiden Joko Widodo sebagai inspektur upacara.</p> <p style='color: black; font-family: Poppins;'>Sumber:</p> <p style='color: black; font-family: Poppins;'>https://www.cnnindonesia.com/nasional/</p> <p style='color: black; font-family: Poppins;'>20190912124908-20-429878/habibie-presiden-ri-pertama-yang-dimakamkan-di-tmp-kalibata</p></div><span data-converted='true'></span> <div style='display: flex; flex-direction: column;'><p style='color: black; font-family: Poppins;'>Unsur berita yang digunakan dalam kalimat bercetak tebal tersebut adalah ... .</p></div>",
        instructions:
          "<p style='color: black; font-family: Poppins;'><b>Perhatikan kutipan berikut!</b></p> <p style='color: black; font-family: Poppins;'>Jakarta, CNN Indonesia -- Almarhum Bacharuddin Jusuf Habibie, <b>Kamis (12/9) siang ini dimakamkan</b> di Taman Makam Pahalawan (TMP) Kalibata, Jakarta Selatan. Posesi pemakaman Habibie di TMP Kalibata dilakukan secara militer dan dipimpin Presiden Joko Widodo sebagai inspektur upacara.</p> <p style='color: black; font-family: Poppins;'>Sumber:</p> <p style='color: black; font-family: Poppins;'>https://www.cnnindonesia.com/nasional/</p> <p style='color: black; font-family: Poppins;'>20190912124908-20-429878/habibie-presiden-ri-pertama-yang-dimakamkan-di-tmp-kalibata</p>",
        marks: 1,
        file_id: '',
        chapter: {
          id: 0,
          name: '',
        },
        subject: {
          id: 126,
          name: '',
        },
        class: {
          id: 126,
          name: '',
        },
        question_level: {
          id: 3,
          name: '',
        },
        question_package_service: {
          id: 0,
          name: '',
        },
        school: {
          id: 0,
          name: '',
        },
        tag: 'Menganalisis',
        question_type: {
          id: 1,
          name: '',
        },
        options: [
          {
            id: 2265797,
            answer: '<p >Siapa</p>',
            orig_key: 'A',
            key: 'A',
            is_correct: false,
            question_id: 550629,
            file_id: '',
            is_choosed: false,
          },
          {
            id: 2265798,
            answer: '<p >Di mana</p>',
            orig_key: 'B',
            key: 'B',
            is_correct: false,
            question_id: 550629,
            file_id: '',
            is_choosed: false,
          },
          {
            id: 2265799,
            answer: '<p >Kapan</p>',
            orig_key: 'C',
            key: 'C',
            is_correct: true,
            question_id: 550629,
            file_id: '',
            is_choosed: false,
          },
          {
            id: 2265800,
            answer: '<p >Bagaimana</p>',
            orig_key: 'D',
            key: 'D',
            is_correct: false,
            question_id: 550629,
            file_id: '',
            is_choosed: false,
          },
        ],
        selected_option: {
          id: 0,
          answer: '',
          orig_key: '',
          key: '',
          is_correct: false,
          question_id: 0,
          file_id: '',
          is_choosed: false,
        },
        user_input: ' ',
        status: '',
        discussion:
          "<span data-converted='true'></span> <div style='display: flex; flex-direction: column;'><p style='color: black; font-family: Poppins;'>Unsur berita yang digunakan dalam kalimat bercetak tebal tersebut adalah <i>kapan</i>. Hal ini karena kutipan kalimat yang bercetak tebal tersebut menunjukkan waktu dimakamkannya Bapak Habibie.</p>     <p style='color: black; font-family: Poppins;'> </p>   <p style='color: black; font-family: Poppins;'> </p></div>",
        point: 0,
        is_scored: false,
      },
      {
        id: 550630,
        orig_order: 4,
        order: 4,
        questions:
          "<link href='https://fonts.googleapis.com/css?family=Poppins' rel='stylesheet'><div style='display: flex; flex-direction: column;'><p style='color: black; font-family: Poppins;'><b>Perhatikan kutipan berikut!</b></p> <p style='color: black; font-family: Poppins;'>Kebakaran terjadi di Apartemen Kalibata City. .... Petugas Sudin, M. Ahsan menyatakan bahwa kebakaran ini disebabkan oleh korsleting listrik.</p></div><span data-converted='true'></span> <div style='display: flex; flex-direction: column;'><p style='color: black; font-family: Poppins;'>Kalimat yang tepat untuk melengkapi bagian rumpang tersebut sesuai dengan unsur <i>kapan</i> adalah ... .</p></div>",
        instructions:
          "<p style='color: black; font-family: Poppins;'><b>Perhatikan kutipan berikut!</b></p> <p style='color: black; font-family: Poppins;'>Kebakaran terjadi di Apartemen Kalibata City. .... Petugas Sudin, M. Ahsan menyatakan bahwa kebakaran ini disebabkan oleh korsleting listrik.</p>",
        marks: 1,
        file_id: '',
        chapter: {
          id: 0,
          name: '',
        },
        subject: {
          id: 126,
          name: '',
        },
        class: {
          id: 126,
          name: '',
        },
        question_level: {
          id: 3,
          name: '',
        },
        question_package_service: {
          id: 0,
          name: '',
        },
        school: {
          id: 0,
          name: '',
        },
        tag: 'Menerapkan',
        question_type: {
          id: 1,
          name: '',
        },
        options: [
          {
            id: 2265801,
            answer:
              '<p >Kejadian tersebut terjadi karena kompor yang meledak.</p>',
            orig_key: 'A',
            key: 'A',
            is_correct: false,
            question_id: 550630,
            file_id: '',
            is_choosed: false,
          },
          {
            id: 2265802,
            answer:
              '<p >Kejadian tersebut terjadi pada hari Rabu (11/9/2019).</p>',
            orig_key: 'B',
            key: 'B',
            is_correct: true,
            question_id: 550630,
            file_id: '',
            is_choosed: false,
          },
          {
            id: 2265803,
            answer:
              '<p >Beberapa orang menjadi korban akibat kejadian ini.</p>',
            orig_key: 'C',
            key: 'C',
            is_correct: false,
            question_id: 550630,
            file_id: '',
            is_choosed: false,
          },
          {
            id: 2265804,
            answer:
              '<p >Kebakaran terjadi sangat dahsyat di Kalibata City.</p>',
            orig_key: 'D',
            key: 'D',
            is_correct: false,
            question_id: 550630,
            file_id: '',
            is_choosed: false,
          },
        ],
        selected_option: {
          id: 0,
          answer: '',
          orig_key: '',
          key: '',
          is_correct: false,
          question_id: 0,
          file_id: '',
          is_choosed: false,
        },
        user_input: ' ',
        status: '',
        discussion:
          "<span data-converted='true'></span> <div style='display: flex; flex-direction: column;'><p style='color: black; font-family: Poppins;'>Kalimat yang tepat untuk melengkapi bagian rumpang tersebut sesuai dengan unsur <i>kapan</i> adalah <i>kejadian tersebut terjadi pada hari Rabu (11/9/2019)</i>.</p> <p style='color: black; font-family: Poppins;'>Kalimat tersebut menunjukkan jawaban dari pertanyaan kapan yang berisi waktu terjadinya kebakaran.</p>     <p style='color: black; font-family: Poppins;'> </p>   <p style='color: black; font-family: Poppins;'> </p></div>",
        point: 0,
        is_scored: false,
      },
      {
        id: 550631,
        orig_order: 5,
        order: 5,
        questions:
          "<link href='https://fonts.googleapis.com/css?family=Poppins' rel='stylesheet'><div style='display: flex; flex-direction: column;'><p style='color: black; font-family: Poppins;'><b>Perhatikan kutipan berikut!</b></p> <p style='color: black; font-family: Poppins;'>Presiden ketiga Republik Indonesia, B.J. Habibie, meninggal dunia. Beliau mengalami komplikasi. .... Tepat pada hari Rabu, 11 September 2019, beliau menghembuskan napas terakhirnya.</p></div><span data-converted='true'></span> <div style='display: flex; flex-direction: column;'><p style='color: black; font-family: Poppins;'>Kalimat yang tepat untuk melengkapi bagian rumpang tersebut sesuai dengan unsur <i>di mana</i> adalah ... .</p></div>",
        instructions:
          "<p style='color: black; font-family: Poppins;'><b>Perhatikan kutipan berikut!</b></p> <p style='color: black; font-family: Poppins;'>Presiden ketiga Republik Indonesia, B.J. Habibie, meninggal dunia. Beliau mengalami komplikasi. .... Tepat pada hari Rabu, 11 September 2019, beliau menghembuskan napas terakhirnya.</p>",
        marks: 1,
        file_id: '',
        chapter: {
          id: 0,
          name: '',
        },
        subject: {
          id: 126,
          name: '',
        },
        class: {
          id: 126,
          name: '',
        },
        question_level: {
          id: 3,
          name: '',
        },
        question_package_service: {
          id: 0,
          name: '',
        },
        school: {
          id: 0,
          name: '',
        },
        tag: 'Menerapkan',
        question_type: {
          id: 1,
          name: '',
        },
        options: [
          {
            id: 2265805,
            answer: '<p >Bapak Habibie dirawat di RSPAD Gatot Subroto.</p>',
            orig_key: 'A',
            key: 'A',
            is_correct: true,
            question_id: 550631,
            file_id: '',
            is_choosed: false,
          },
          {
            id: 2265806,
            answer: '<p >Bapak Habibie mengalami luka yang sangat parah.</p>',
            orig_key: 'B',
            key: 'B',
            is_correct: false,
            question_id: 550631,
            file_id: '',
            is_choosed: false,
          },
          {
            id: 2265807,
            answer: '<p >Bapak Habibie akhirnya meninggal pada Rabu malam.</p>',
            orig_key: 'C',
            key: 'C',
            is_correct: false,
            question_id: 550631,
            file_id: '',
            is_choosed: false,
          },
          {
            id: 2265808,
            answer:
              '<p >Bapak Habibie ialah presiden ketiga Republik Indonesia.</p>',
            orig_key: 'D',
            key: 'D',
            is_correct: false,
            question_id: 550631,
            file_id: '',
            is_choosed: false,
          },
        ],
        selected_option: {
          id: 0,
          answer: '',
          orig_key: '',
          key: '',
          is_correct: false,
          question_id: 0,
          file_id: '',
          is_choosed: false,
        },
        user_input: ' ',
        status: '',
        discussion:
          "<span data-converted='true'></span> <div style='display: flex; flex-direction: column;'><p style='color: black; font-family: Poppins;'>Kalimat yang tepat untuk melengkapi bagian rumpang tersebut sesuai dengan unsur <i>di mana</i> adalah <i>Bapak Habibie dirawat di RSPAD Gatot Subroto</i>.</p> <p style='color: black; font-family: Poppins;'>Kalimat tersebut menunjukkan jawaban dari pertanyaan di mana yang berisi tempat Bapak Habibie dirawat selama sakit.</p>     <p style='color: black; font-family: Poppins;'> </p>   <p style='color: black; font-family: Poppins;'> </p></div>",
        point: 0,
        is_scored: false,
      },
      {
        id: 607323,
        orig_order: 6,
        order: 6,
        questions: 'Ini essay saya',
        instructions: '',
        marks: 2,
        file_id: '',
        chapter: {
          id: 0,
          name: '',
        },
        subject: {
          id: 126,
          name: '',
        },
        class: {
          id: 126,
          name: '',
        },
        question_level: {
          id: 1,
          name: '',
        },
        question_package_service: {
          id: 0,
          name: '',
        },
        school: {
          id: 0,
          name: '',
        },
        tag: 'Memahami',
        question_type: {
          id: 2,
          name: '',
        },
        options: null,
        selected_option: {
          id: 0,
          answer: '',
          orig_key: '',
          key: '',
          is_correct: false,
          question_id: 0,
          file_id: '',
          is_choosed: false,
        },
        user_input: 'Ini jawabanku',
        status: 'answered',
        discussion: 'Bacot lu',
        point: 1,
        is_scored: true,
      },
    ],
    questions: [
      {
        id: 550627,
        orig_order: 1,
        order: 1,
        questions:
          "<link href='https://fonts.googleapis.com/css?family=Poppins' rel='stylesheet'><div style='display: flex; flex-direction: column;'><p style='color: black; font-family: Poppins;'><b>Perhatikan kutipan berikut!</b></p> <p style='color: black; font-family: Poppins;'>Jakarta, CNN Indonesia -- Almarhum Bacharuddin Jusuf Habibie, Kamis (12/9) siang ini dimakamkan di Taman Makam Pahalawan (TMP) Kalibata, Jakarta Selatan. <b>Posesi pemakaman Habibie di TMP Kalibata dilakukan secara militer dan dipimpin Presiden Joko Widodo sebagai inspektur upacara</b>.</p> <p style='color: black; font-family: Poppins;'>Sumber:</p> <p style='color: black; font-family: Poppins;'>https://www.cnnindonesia.com/nasional/</p> <p style='color: black; font-family: Poppins;'>20190912124908-20-429878/habibie-presiden-ri-pertama-yang-dimakamkan-di-tmp-kalibata</p></div><span data-converted='true'></span> <div style='display: flex; flex-direction: column;'><p style='color: black; font-family: Poppins;'>Unsur berita yang digunakan dalam kalimat bercetak tebal tersebut adalah ... .</p></div>",
        instructions:
          "<p style='color: black; font-family: Poppins;'><b>Perhatikan kutipan berikut!</b></p> <p style='color: black; font-family: Poppins;'>Jakarta, CNN Indonesia -- Almarhum Bacharuddin Jusuf Habibie, Kamis (12/9) siang ini dimakamkan di Taman Makam Pahalawan (TMP) Kalibata, Jakarta Selatan. <b>Posesi pemakaman Habibie di TMP Kalibata dilakukan secara militer dan dipimpin Presiden Joko Widodo sebagai inspektur upacara</b>.</p> <p style='color: black; font-family: Poppins;'>Sumber:</p> <p style='color: black; font-family: Poppins;'>https://www.cnnindonesia.com/nasional/</p> <p style='color: black; font-family: Poppins;'>20190912124908-20-429878/habibie-presiden-ri-pertama-yang-dimakamkan-di-tmp-kalibata</p>",
        marks: 1,
        file_id: '',
        chapter: {
          id: 0,
          name: '',
        },
        subject: {
          id: 126,
          name: '',
        },
        class: {
          id: 126,
          name: '',
        },
        question_level: {
          id: 3,
          name: '',
        },
        question_package_service: {
          id: 0,
          name: '',
        },
        school: {
          id: 0,
          name: '',
        },
        tag: 'Menganalisis',
        question_type: {
          id: 1,
          name: '',
        },
        options: [
          {
            id: 2265789,
            answer: '<p >Bagaimana</p>',
            orig_key: 'A',
            key: 'A',
            is_correct: true,
            question_id: 550627,
            file_id: '',
            is_choosed: true,
          },
          {
            id: 2265790,
            answer: '<p >Di mana</p>',
            orig_key: 'B',
            key: 'B',
            is_correct: false,
            question_id: 550627,
            file_id: '',
            is_choosed: false,
          },
          {
            id: 2265791,
            answer: '<p >Apa</p>',
            orig_key: 'C',
            key: 'C',
            is_correct: false,
            question_id: 550627,
            file_id: '',
            is_choosed: false,
          },
          {
            id: 2265792,
            answer: '<p >Kapan</p>',
            orig_key: 'D',
            key: 'D',
            is_correct: false,
            question_id: 550627,
            file_id: '',
            is_choosed: false,
          },
        ],
        selected_option: {
          id: 2265789,
          answer: '<p >Bagaimana</p>',
          orig_key: 'A',
          key: 'A',
          is_correct: true,
          question_id: 550627,
          file_id: '',
          is_choosed: true,
        },
        user_input: '',
        status: 'answered',
        discussion:
          "<span data-converted='true'></span> <div style='display: flex; flex-direction: column;'><p style='color: black; font-family: Poppins;'>Unsur berita yang digunakan dalam kalimat bercetak tebal tersebut adalah <i>bagaimana</i>. Hal ini karena kutipan kalimat yang bercetak tebal tersebut menunjukkan proses pemakaman Bapak Habibie.</p>     <p style='color: black; font-family: Poppins;'> </p>   <p style='color: black; font-family: Poppins;'> </p></div>",
        point: 1,
        is_scored: true,
      },
      {
        id: 550628,
        orig_order: 2,
        order: 2,
        questions:
          "<link href='https://fonts.googleapis.com/css?family=Poppins' rel='stylesheet'><div style='display: flex; flex-direction: column;'><p style='color: black; font-family: Poppins;'><b>Perhatikan kutipan berikut!</b></p> <p style='color: black; font-family: Poppins;'>Jakarta, CNN Indonesia -- Almarhum Bacharuddin Jusuf Habibie, Kamis (12/9) siang ini <b>dimakamkan di Taman Makam Pahalawan (TMP) Kalibata, Jakarta Selatan</b>. Posesi pemakaman Habibie di TMP Kalibata dilakukan secara militer dan dipimpin Presiden Joko Widodo sebagai inspektur upacara.</p> <p style='color: black; font-family: Poppins;'>Sumber:</p> <p style='color: black; font-family: Poppins;'>https://www.cnnindonesia.com/nasional/</p> <p style='color: black; font-family: Poppins;'>20190912124908-20-429878/habibie-presiden-ri-pertama-yang-dimakamkan-di-tmp-kalibata</p></div><span data-converted='true'></span> <div style='display: flex; flex-direction: column;'><p style='color: black; font-family: Poppins;'>Unsur berita yang digunakan dalam kalimat bercetak tebal tersebut adalah ... .</p></div>",
        instructions:
          "<p style='color: black; font-family: Poppins;'><b>Perhatikan kutipan berikut!</b></p> <p style='color: black; font-family: Poppins;'>Jakarta, CNN Indonesia -- Almarhum Bacharuddin Jusuf Habibie, Kamis (12/9) siang ini <b>dimakamkan di Taman Makam Pahalawan (TMP) Kalibata, Jakarta Selatan</b>. Posesi pemakaman Habibie di TMP Kalibata dilakukan secara militer dan dipimpin Presiden Joko Widodo sebagai inspektur upacara.</p> <p style='color: black; font-family: Poppins;'>Sumber:</p> <p style='color: black; font-family: Poppins;'>https://www.cnnindonesia.com/nasional/</p> <p style='color: black; font-family: Poppins;'>20190912124908-20-429878/habibie-presiden-ri-pertama-yang-dimakamkan-di-tmp-kalibata</p>",
        marks: 1,
        file_id: '',
        chapter: {
          id: 0,
          name: '',
        },
        subject: {
          id: 126,
          name: '',
        },
        class: {
          id: 126,
          name: '',
        },
        question_level: {
          id: 3,
          name: '',
        },
        question_package_service: {
          id: 0,
          name: '',
        },
        school: {
          id: 0,
          name: '',
        },
        tag: 'Menganalisis',
        question_type: {
          id: 1,
          name: '',
        },
        options: [
          {
            id: 2265793,
            answer: '<p >Siapa</p>',
            orig_key: 'A',
            key: 'A',
            is_correct: false,
            question_id: 550628,
            file_id: '',
            is_choosed: false,
          },
          {
            id: 2265794,
            answer: '<p >Bagaimana</p>',
            orig_key: 'B',
            key: 'B',
            is_correct: false,
            question_id: 550628,
            file_id: '',
            is_choosed: false,
          },
          {
            id: 2265795,
            answer: '<p >Kapan</p>',
            orig_key: 'C',
            key: 'C',
            is_correct: false,
            question_id: 550628,
            file_id: '',
            is_choosed: false,
          },
          {
            id: 2265796,
            answer: '<p >Di mana</p>',
            orig_key: 'D',
            key: 'D',
            is_correct: true,
            question_id: 550628,
            file_id: '',
            is_choosed: false,
          },
        ],
        selected_option: {
          id: 0,
          answer: '',
          orig_key: '',
          key: '',
          is_correct: false,
          question_id: 0,
          file_id: '',
          is_choosed: false,
        },
        user_input: ' ',
        status: '',
        discussion:
          "<span data-converted='true'></span> <div style='display: flex; flex-direction: column;'><p style='color: black; font-family: Poppins;'>Unsur berita yang digunakan dalam kalimat bercetak tebal tersebut adalah <i>di mana</i>. Hal ini karena kutipan kalimat yang bercetak tebal tersebut menunjukkan tempat dimakamkannya Bapak Habibie.</p>     <p style='color: black; font-family: Poppins;'> </p>   <p style='color: black; font-family: Poppins;'> </p></div>",
        point: 0,
        is_scored: false,
      },
      {
        id: 550629,
        orig_order: 3,
        order: 3,
        questions:
          "<link href='https://fonts.googleapis.com/css?family=Poppins' rel='stylesheet'><div style='display: flex; flex-direction: column;'><p style='color: black; font-family: Poppins;'><b>Perhatikan kutipan berikut!</b></p> <p style='color: black; font-family: Poppins;'>Jakarta, CNN Indonesia -- Almarhum Bacharuddin Jusuf Habibie, <b>Kamis (12/9) siang ini dimakamkan</b> di Taman Makam Pahalawan (TMP) Kalibata, Jakarta Selatan. Posesi pemakaman Habibie di TMP Kalibata dilakukan secara militer dan dipimpin Presiden Joko Widodo sebagai inspektur upacara.</p> <p style='color: black; font-family: Poppins;'>Sumber:</p> <p style='color: black; font-family: Poppins;'>https://www.cnnindonesia.com/nasional/</p> <p style='color: black; font-family: Poppins;'>20190912124908-20-429878/habibie-presiden-ri-pertama-yang-dimakamkan-di-tmp-kalibata</p></div><span data-converted='true'></span> <div style='display: flex; flex-direction: column;'><p style='color: black; font-family: Poppins;'>Unsur berita yang digunakan dalam kalimat bercetak tebal tersebut adalah ... .</p></div>",
        instructions:
          "<p style='color: black; font-family: Poppins;'><b>Perhatikan kutipan berikut!</b></p> <p style='color: black; font-family: Poppins;'>Jakarta, CNN Indonesia -- Almarhum Bacharuddin Jusuf Habibie, <b>Kamis (12/9) siang ini dimakamkan</b> di Taman Makam Pahalawan (TMP) Kalibata, Jakarta Selatan. Posesi pemakaman Habibie di TMP Kalibata dilakukan secara militer dan dipimpin Presiden Joko Widodo sebagai inspektur upacara.</p> <p style='color: black; font-family: Poppins;'>Sumber:</p> <p style='color: black; font-family: Poppins;'>https://www.cnnindonesia.com/nasional/</p> <p style='color: black; font-family: Poppins;'>20190912124908-20-429878/habibie-presiden-ri-pertama-yang-dimakamkan-di-tmp-kalibata</p>",
        marks: 1,
        file_id: '',
        chapter: {
          id: 0,
          name: '',
        },
        subject: {
          id: 126,
          name: '',
        },
        class: {
          id: 126,
          name: '',
        },
        question_level: {
          id: 3,
          name: '',
        },
        question_package_service: {
          id: 0,
          name: '',
        },
        school: {
          id: 0,
          name: '',
        },
        tag: 'Menganalisis',
        question_type: {
          id: 1,
          name: '',
        },
        options: [
          {
            id: 2265797,
            answer: '<p >Siapa</p>',
            orig_key: 'A',
            key: 'A',
            is_correct: false,
            question_id: 550629,
            file_id: '',
            is_choosed: false,
          },
          {
            id: 2265798,
            answer: '<p >Di mana</p>',
            orig_key: 'B',
            key: 'B',
            is_correct: false,
            question_id: 550629,
            file_id: '',
            is_choosed: false,
          },
          {
            id: 2265799,
            answer: '<p >Kapan</p>',
            orig_key: 'C',
            key: 'C',
            is_correct: true,
            question_id: 550629,
            file_id: '',
            is_choosed: false,
          },
          {
            id: 2265800,
            answer: '<p >Bagaimana</p>',
            orig_key: 'D',
            key: 'D',
            is_correct: false,
            question_id: 550629,
            file_id: '',
            is_choosed: false,
          },
        ],
        selected_option: {
          id: 0,
          answer: '',
          orig_key: '',
          key: '',
          is_correct: false,
          question_id: 0,
          file_id: '',
          is_choosed: false,
        },
        user_input: ' ',
        status: '',
        discussion:
          "<span data-converted='true'></span> <div style='display: flex; flex-direction: column;'><p style='color: black; font-family: Poppins;'>Unsur berita yang digunakan dalam kalimat bercetak tebal tersebut adalah <i>kapan</i>. Hal ini karena kutipan kalimat yang bercetak tebal tersebut menunjukkan waktu dimakamkannya Bapak Habibie.</p>     <p style='color: black; font-family: Poppins;'> </p>   <p style='color: black; font-family: Poppins;'> </p></div>",
        point: 0,
        is_scored: false,
      },
      {
        id: 550630,
        orig_order: 4,
        order: 4,
        questions:
          "<link href='https://fonts.googleapis.com/css?family=Poppins' rel='stylesheet'><div style='display: flex; flex-direction: column;'><p style='color: black; font-family: Poppins;'><b>Perhatikan kutipan berikut!</b></p> <p style='color: black; font-family: Poppins;'>Kebakaran terjadi di Apartemen Kalibata City. .... Petugas Sudin, M. Ahsan menyatakan bahwa kebakaran ini disebabkan oleh korsleting listrik.</p></div><span data-converted='true'></span> <div style='display: flex; flex-direction: column;'><p style='color: black; font-family: Poppins;'>Kalimat yang tepat untuk melengkapi bagian rumpang tersebut sesuai dengan unsur <i>kapan</i> adalah ... .</p></div>",
        instructions:
          "<p style='color: black; font-family: Poppins;'><b>Perhatikan kutipan berikut!</b></p> <p style='color: black; font-family: Poppins;'>Kebakaran terjadi di Apartemen Kalibata City. .... Petugas Sudin, M. Ahsan menyatakan bahwa kebakaran ini disebabkan oleh korsleting listrik.</p>",
        marks: 1,
        file_id: '',
        chapter: {
          id: 0,
          name: '',
        },
        subject: {
          id: 126,
          name: '',
        },
        class: {
          id: 126,
          name: '',
        },
        question_level: {
          id: 3,
          name: '',
        },
        question_package_service: {
          id: 0,
          name: '',
        },
        school: {
          id: 0,
          name: '',
        },
        tag: 'Menerapkan',
        question_type: {
          id: 1,
          name: '',
        },
        options: [
          {
            id: 2265801,
            answer:
              '<p >Kejadian tersebut terjadi karena kompor yang meledak.</p>',
            orig_key: 'A',
            key: 'A',
            is_correct: false,
            question_id: 550630,
            file_id: '',
            is_choosed: false,
          },
          {
            id: 2265802,
            answer:
              '<p >Kejadian tersebut terjadi pada hari Rabu (11/9/2019).</p>',
            orig_key: 'B',
            key: 'B',
            is_correct: true,
            question_id: 550630,
            file_id: '',
            is_choosed: false,
          },
          {
            id: 2265803,
            answer:
              '<p >Beberapa orang menjadi korban akibat kejadian ini.</p>',
            orig_key: 'C',
            key: 'C',
            is_correct: false,
            question_id: 550630,
            file_id: '',
            is_choosed: false,
          },
          {
            id: 2265804,
            answer:
              '<p >Kebakaran terjadi sangat dahsyat di Kalibata City.</p>',
            orig_key: 'D',
            key: 'D',
            is_correct: false,
            question_id: 550630,
            file_id: '',
            is_choosed: false,
          },
        ],
        selected_option: {
          id: 0,
          answer: '',
          orig_key: '',
          key: '',
          is_correct: false,
          question_id: 0,
          file_id: '',
          is_choosed: false,
        },
        user_input: ' ',
        status: '',
        discussion:
          "<span data-converted='true'></span> <div style='display: flex; flex-direction: column;'><p style='color: black; font-family: Poppins;'>Kalimat yang tepat untuk melengkapi bagian rumpang tersebut sesuai dengan unsur <i>kapan</i> adalah <i>kejadian tersebut terjadi pada hari Rabu (11/9/2019)</i>.</p> <p style='color: black; font-family: Poppins;'>Kalimat tersebut menunjukkan jawaban dari pertanyaan kapan yang berisi waktu terjadinya kebakaran.</p>     <p style='color: black; font-family: Poppins;'> </p>   <p style='color: black; font-family: Poppins;'> </p></div>",
        point: 0,
        is_scored: false,
      },
      {
        id: 550631,
        orig_order: 5,
        order: 5,
        questions:
          "<link href='https://fonts.googleapis.com/css?family=Poppins' rel='stylesheet'><div style='display: flex; flex-direction: column;'><p style='color: black; font-family: Poppins;'><b>Perhatikan kutipan berikut!</b></p> <p style='color: black; font-family: Poppins;'>Presiden ketiga Republik Indonesia, B.J. Habibie, meninggal dunia. Beliau mengalami komplikasi. .... Tepat pada hari Rabu, 11 September 2019, beliau menghembuskan napas terakhirnya.</p></div><span data-converted='true'></span> <div style='display: flex; flex-direction: column;'><p style='color: black; font-family: Poppins;'>Kalimat yang tepat untuk melengkapi bagian rumpang tersebut sesuai dengan unsur <i>di mana</i> adalah ... .</p></div>",
        instructions:
          "<p style='color: black; font-family: Poppins;'><b>Perhatikan kutipan berikut!</b></p> <p style='color: black; font-family: Poppins;'>Presiden ketiga Republik Indonesia, B.J. Habibie, meninggal dunia. Beliau mengalami komplikasi. .... Tepat pada hari Rabu, 11 September 2019, beliau menghembuskan napas terakhirnya.</p>",
        marks: 1,
        file_id: '',
        chapter: {
          id: 0,
          name: '',
        },
        subject: {
          id: 126,
          name: '',
        },
        class: {
          id: 126,
          name: '',
        },
        question_level: {
          id: 3,
          name: '',
        },
        question_package_service: {
          id: 0,
          name: '',
        },
        school: {
          id: 0,
          name: '',
        },
        tag: 'Menerapkan',
        question_type: {
          id: 1,
          name: '',
        },
        options: [
          {
            id: 2265805,
            answer: '<p >Bapak Habibie dirawat di RSPAD Gatot Subroto.</p>',
            orig_key: 'A',
            key: 'A',
            is_correct: true,
            question_id: 550631,
            file_id: '',
            is_choosed: false,
          },
          {
            id: 2265806,
            answer: '<p >Bapak Habibie mengalami luka yang sangat parah.</p>',
            orig_key: 'B',
            key: 'B',
            is_correct: false,
            question_id: 550631,
            file_id: '',
            is_choosed: false,
          },
          {
            id: 2265807,
            answer: '<p >Bapak Habibie akhirnya meninggal pada Rabu malam.</p>',
            orig_key: 'C',
            key: 'C',
            is_correct: false,
            question_id: 550631,
            file_id: '',
            is_choosed: false,
          },
          {
            id: 2265808,
            answer:
              '<p >Bapak Habibie ialah presiden ketiga Republik Indonesia.</p>',
            orig_key: 'D',
            key: 'D',
            is_correct: false,
            question_id: 550631,
            file_id: '',
            is_choosed: false,
          },
        ],
        selected_option: {
          id: 0,
          answer: '',
          orig_key: '',
          key: '',
          is_correct: false,
          question_id: 0,
          file_id: '',
          is_choosed: false,
        },
        user_input: ' ',
        status: '',
        discussion:
          "<span data-converted='true'></span> <div style='display: flex; flex-direction: column;'><p style='color: black; font-family: Poppins;'>Kalimat yang tepat untuk melengkapi bagian rumpang tersebut sesuai dengan unsur <i>di mana</i> adalah <i>Bapak Habibie dirawat di RSPAD Gatot Subroto</i>.</p> <p style='color: black; font-family: Poppins;'>Kalimat tersebut menunjukkan jawaban dari pertanyaan di mana yang berisi tempat Bapak Habibie dirawat selama sakit.</p>     <p style='color: black; font-family: Poppins;'> </p>   <p style='color: black; font-family: Poppins;'> </p></div>",
        point: 0,
        is_scored: false,
      },
      {
        id: 607323,
        orig_order: 6,
        order: 6,
        questions: 'Ini essay saya',
        instructions: '',
        marks: 2,
        file_id: '',
        chapter: {
          id: 0,
          name: '',
        },
        subject: {
          id: 126,
          name: '',
        },
        class: {
          id: 126,
          name: '',
        },
        question_level: {
          id: 1,
          name: '',
        },
        question_package_service: {
          id: 0,
          name: '',
        },
        school: {
          id: 0,
          name: '',
        },
        tag: 'Memahami',
        question_type: {
          id: 2,
          name: '',
        },
        options: null,
        selected_option: {
          id: 0,
          answer: '',
          orig_key: '',
          key: '',
          is_correct: false,
          question_id: 0,
          file_id: '',
          is_choosed: false,
        },
        user_input: 'Ini jawabanku',
        status: 'answered',
        discussion: 'Bacot lu',
        point: 1,
        is_scored: true,
      },
    ],
    max_point: 7,
    total_point: 2,
    point: 28,
    wrong_answer: 0,
    correct_answer: 1,
    pass_answer: 4,
    submitted_answer: 1,
    exam_type: 'mix',
    duration: 0,
  },
  school_exam: {
    id: 1128,
    title: 'Bambo',
    teacher: {
      id: 13562010,
      name: '',
    },
    school: {
      id: 2,
      name: 'Kelas Pintar Indonesia',
    },
    curriculumn: {
      id: 1,
      name: '',
    },
    question_package_service: {
      id: 13,
      name: '',
    },
    rombel_class_school: {
      id: 217,
      name: '8-B',
    },
    subject: {
      id: 126,
      name: '',
    },
    start_time: '2024-01-30 16:10:00',
    end_time: '2024-01-30 16:20:00',
    duration: 10,
    instructions: 'Hello',
    status: 'scheduled',
    completed_at: '',
    created_at: '',
    teacher_token:
      'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3MDY2MDkxNjksImlzcyI6ImtwLWxpdmVraXQiLCJuYmYiOjE3MDY2MDU1NjksInN1YiI6IjEzNTYyMDEwIiwidmlkZW8iOnsiY2FuUHVibGlzaCI6ZmFsc2UsInJvb20iOiI4OGRjMjA2Ni1hZjM5LTQ1OTItYmMyZi02ZTAyZDA2NjI2OTYiLCJyb29tSm9pbiI6dHJ1ZX19.kyxHy-iQK5ezDUOiBwnPC34o_dQo3PuslIeds-1Owng',
    room: '88dc2066-af39-4592-bc2f-6e02d0662696',
    total_assigned: 0,
    total_finished: 0,
    is_active_proctoring: false,
    is_shuffle_questions: false,
    is_shuffle_answers: false,
  },
  student_exam: {
    id: 197046,
    school_exam_id: 1128,
    school: {
      id: 1128,
      name: '',
    },
    status: 'dikumpulkan',
    start_at: '2024-01-30 16:12:22',
    finished_at: '2024-01-30 16:18:04',
    token:
      'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3MDY2MDkxNjksImlzcyI6ImtwLWxpdmVraXQiLCJtZXRhZGF0YSI6IkNhaHlvIFNhcHV0cm8iLCJuYW1lIjoiQ2FoeW8gU2FwdXRybyIsIm5iZiI6MTcwNjYwNTU2OSwic3ViIjoiMTA1MDk1ODIiLCJ2aWRlbyI6eyJyb29tIjoiODhkYzIwNjYtYWYzOS00NTkyLWJjMmYtNmUwMmQwNjYyNjk2Iiwicm9vbUpvaW4iOnRydWV9fQ.KD1acsVESklh42H1flSP_n8ihIH14GbbF2jUycy6sE0',
    room: '88dc2066-af39-4592-bc2f-6e02d0662696',
    recording: '',
    duration: 6,
  },
  user: {
    id: 10509582,
    name: '',
  },
};
