import Colors from '@constants/colors';
import Fonts from '@constants/fonts';
import {StyleSheet} from 'react-native';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: Colors.white,
    paddingHorizontal: 16,
  },
  scrollContainer: {
    height: 90,
  },
  filter: {
    backgroundColor: Colors.primary.light3,
    height: 32,
    justifyContent: 'center',
    padding: 5,
    marginHorizontal: 10,
  },
  textBlue: {
    fontFamily: 'Poppins-Bold',
    color: Colors.primary.base,
    fontSize: 14,
    lineHeight: 22,
    letterSpacing: 0.25,
  },
  content: {
    backgroundColor: Colors.white,
    height: '90%',
  },
  shadowProp: {
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 4,
    },
    shadowOpacity: 0.3,
    shadowRadius: 4.65,

    elevation: 8,
  },
  card: {
    backgroundColor: Colors.white,
    borderRadius: 10,
    width: '99%',
    padding: 16,
    marginVertical: 10,
    alignSelf: 'center',
  },
  row: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  rowPp: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  pp: {
    width: 32,
    height: 32,
    marginRight: 10,
  },
  textType: {
    fontFamily: 'Poppins-Regular',
    backgroundColor: Colors.primary.light3,
    borderRadius: 16,
    overflow: 'hidden',
    color: Colors.primary.base,
    fontSize: 12,
    paddingVertical: 4,
    paddingHorizontal: 8,
  },
  textTitle: {
    fontFamily: 'Poppins-Bold',
    color: Colors.dark.neutral100,
    fontSize: 16,
    borderRadius: 10,
  },
  textSubTitle: {
    fontFamily: 'Poppins-Regular',
    fontSize: 12,
    borderRadius: 10,
  },
  filterContainer: {
    justifyContent: 'space-between',
    width: '100%',
  },
  FilterHeader: {
    backgroundColor: Colors.primary.light3,
    borderRadius: 25,
    marginHorizontal: 10,
    paddingHorizontal: 12,
    paddingVertical: 5,
    flexDirection: 'row',
    alignItems: 'center',
  },
  filterHeaderActive: {
    backgroundColor: Colors.primary.base,
    borderRadius: 25,
    marginHorizontal: 10,
    paddingHorizontal: 12,
    paddingVertical: 5,
    flexDirection: 'row',
    alignItems: 'center',
  },
  itemSubjectSelected: {
    backgroundColor: Colors.primary.base,
    borderRadius: 25,
    marginRight: 8,
    paddingHorizontal: 12,
    paddingVertical: 5,
    flexDirection: 'row',
    alignItems: 'center',
    marginVertical: 3,
    flexBasis: '33%',
    justifyContent: 'center',
    alignContent: 'center',
  },
  itemSubject: {
    backgroundColor: Colors.primary.light3,
    borderRadius: 25,
    marginRight: 8,
    paddingHorizontal: 12,
    paddingVertical: 5,
    flexDirection: 'row',
    alignItems: 'center',
    marginVertical: 3,
    flexBasis: '33%',
    justifyContent: 'center',
    alignContent: 'center',
  },
  dateItem: {
    borderRadius: 25,
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 12,
    paddingVertical: 5,
    backgroundColor: Colors.dark.neutral10,
    width: '95%',
    justifyContent: 'space-between',
  },
  dateText: {
    width: '85%',
    fontWeight: '600',
    fontSize: 14,
    lineHeight: 22,
    fontFamily: Fonts.SemiBoldPoppins,
    color: Colors.black,
  },
  textFilter: {
    fontFamily: Fonts.SemiBoldPoppins,
    fontSize: 14,
    fontWeight: '400',
    lineHeight: 22,
    color: Colors.primary.base,
    marginRight: 4,
  },
  textFilterActive: {
    fontFamily: Fonts.SemiBoldPoppins,
    fontSize: 14,
    fontWeight: '400',
    lineHeight: 22,
    color: Colors.white,
    marginRight: 4,
    textTransform: 'capitalize',
  },
  itemSubjectLabel: {
    fontFamily: Fonts.RegularPoppins,
    fontSize: 14,
    fontWeight: '400',
    lineHeight: 22,
    color: Colors.primary.base,
    textAlign: 'center',
    textTransform: 'capitalize',
  },
  itemSubjectLabelActive: {
    fontFamily: Fonts.RegularPoppins,
    fontSize: 14,
    fontWeight: '400',
    lineHeight: 22,
    color: Colors.white,
    textTransform: 'capitalize',
    textAlign: 'center',
  },
  searchBar: {
    backgroundColor: Colors.dark.neutral10,
    borderRadius: 15,
  },
  containerSwipe: {
    height: 300,
    paddingHorizontal: 16,
  },
  titleSwipe: {
    textAlign: 'center',
    fontWeight: '600',
    fontSize: 20,
    lineHeight: 28,
    fontFamily: Fonts.SemiBoldPoppins,
    color: Colors.black,
  },
  typeRecord: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginTop: 30,
    alignSelf: 'center',
  },
  typeRecordItem: {
    width: '40%',
    backgroundColor: Colors.primary.light3,
    paddingHorizontal: 12,
    paddingVertical: 5,
    borderRadius: 15,
    alignItems: 'center',
  },
  typeRecordItemText: {
    fontWeight: '400',
    fontSize: 14,
    lineHeight: 22,
    color: Colors.primary.base,
    fontFamily: Fonts.SemiBoldPoppins,
  },
  btmWidth: {width: '49%'},
});
