import Colors from '@constants/colors';
import {StyleSheet} from 'react-native';
export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: Colors.white,
  },
  contentContainer: {
    flexGrow: 1,
    // flex: 1,
  },
  input: {
    backgroundColor: '#F5F7F9',
    borderRadius: 10,
    padding: 10,
    color: 'black',
  },
  image: {
    width: '100%',
    height: 200,
    borderRadius: 10,
    alignSelf: 'center',
  },
  buttonCamera: {
    flexDirection: 'row',
    width: '100%',
    alignItems: 'center',
    backgroundColor: Colors.white,
    borderRadius: 20,
    justifyContent: 'space-evenly',
    maxWidth: 130,
    padding: 5,
    position: 'absolute',
    alignSelf: 'flex-start',
    bottom: 10,
    left: 10,
  },
  text: {
    fontFamily: 'Poppins-Bold',
    fontSize: 14,
    color: Colors.primary.base,
  },
  imageContainer: {
    alignSelf: 'center',
    margin: 20,
    justifyContent: 'flex-end',
    width: '95%',
  },
  listButton: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    backgroundColor: '#F5F7F9',
    paddingHorizontal: 16,
    paddingVertical: 10,
    borderRadius: 30,
  },
  title: {
    fontFamily: 'Poppins-Regular',
    fontStyle: 'normal',
    fontWeight: '400',
    fontSize: 14,
    lineHeight: 22,
    letterSpacing: 0.25,
    color: '#1D252D',
  },
  boldTetxt: {
    fontFamily: 'Poppins-Bold',
    fontStyle: 'normal',
    fontWeight: '400',
    fontSize: 14,
    lineHeight: 22,
    letterSpacing: 0.25,
    color: Colors.primary.base,
  },
  textWarning: {
    fontFamily: 'Poppins-Regular',
    fontStyle: 'normal',
    fontWeight: '400',
    fontSize: 14,
    lineHeight: 22,
    letterSpacing: 0.25,
    color: Colors.danger.base,
  },
  active: {
    fontFamily: 'Poppins-Bold',
    fontStyle: 'normal',
    fontWeight: '600',
    fontSize: 16,
    lineHeight: 24,
    letterSpacing: 0.01,
    color: '#1D252D',
  },
  inActive: {
    fontFamily: 'Poppins-Bold',
    fontStyle: 'normal',
    fontWeight: '600',
    fontSize: 16,
    lineHeight: 24,
    letterSpacing: 0.01,
    color: '#A5B0BB',
  },

  listContainer: {
    width: '90%',
    alignSelf: 'center',
    marginVertical: 10,
  },
  textBlue: {
    fontFamily: 'Poppins-Bold',
    fontStyle: 'normal',
    fontWeight: '600',
    fontSize: 12,
    lineHeight: 16,
    display: 'flex',
    alignItems: 'center',
    textAlign: 'center',
    letterSpacing: 0.25,
    color: Colors.primary.base,
    marginVertical: 5,
  },
  ModalTitle: {
    fontFamily: 'Poppins-Bold',
    fontStyle: 'normal',
    fontWeight: '600',
    fontSize: 20,
    lineHeight: 28,
    display: 'flex',
    alignItems: 'center',
    textAlign: 'center',
    color: Colors.black,
  },
  subCard: {
    width: '33%',
    alignItems: 'center',
    marginTop: 20,
    justifyContent: 'center',
  },
  coinRow: {
    flexDirection: 'row',
    alignItems: 'center',
    borderRadius: 20,
    paddingHorizontal: 6,
    paddingVertical: 2,
    height: 20,
    backgroundColor: Colors.white,
    position: 'absolute',
    alignContent: 'center',
  },
  shadowProp: {
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
    elevation: 5,
  },
  circle: {
    width: 24,
    height: 24,
    borderRadius: 100,
  },
});
