import Colors from '@constants/colors';
import Fonts from '@constants/fonts';
import {StyleSheet} from 'react-native';

export const styles = StyleSheet.create({
  contentContainerStyle: {
    flexGrow: 1,
  },
  rootContainer: {
    flex: 1,
    backgroundColor: Colors.white,
  },
  container: {
    flex: 1,
  },
  dataCard: {
    padding: 16,
    flexDirection: 'row',
    backgroundColor: Colors.white,
    marginHorizontal: 16,
    marginBottom: 12,
    borderRadius: 10,
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 1,
    },
    shadowOpacity: 0.1,
    shadowRadius: 1.84,
    elevation: 2,
  },
  leftContent: {
    marginRight: 8,
    flex: 1,
  },
  badgeWaiting: {
    paddingHorizontal: 12,
    paddingVertical: 5,
    borderRadius: 20,
    backgroundColor: Colors.primary.light3,
    marginBottom: 8,
  },
  badgeAccepted: {
    paddingHorizontal: 12,
    paddingVertical: 5,
    borderRadius: 20,
    backgroundColor: Colors.success.light2,
    marginBottom: 8,
  },
  badgeRejected: {
    paddingHorizontal: 12,
    paddingVertical: 5,
    borderRadius: 20,
    backgroundColor: Colors.danger.light2,
    marginBottom: 8,
  },
  titleBadgeWaiting: {
    fontSize: 14,
    lineHeight: 22,
    color: Colors.primary.base,
    fontWeight: '400',
    fontFamily: Fonts.RegularPoppins,
  },
  titleBadgeAccepted: {
    fontSize: 14,
    lineHeight: 22,
    color: Colors.success.base,
    fontWeight: '400',
    fontFamily: Fonts.RegularPoppins,
  },
  titleBadgeRejected: {
    fontSize: 14,
    lineHeight: 22,
    color: Colors.danger.base,
    fontWeight: '400',
    fontFamily: Fonts.RegularPoppins,
  },
  cardHeadTitle: {
    fontSize: 14,
    lineHeight: 18,
    color: Colors.primary.base,
    fontWeight: '600',
    fontFamily: Fonts.SemiBoldPoppins,
    marginBottom: 4,
  },
  row: {
    flexDirection: 'row',
  },
  cardDateContainer: {
    flexDirection: 'row',
    marginBottom: 4,
  },
  cardDateTitle: {
    fontSize: 14,
    lineHeight: 18,
    color: Colors.dark.neutral100,
    fontWeight: '600',
    fontFamily: Fonts.SemiBoldPoppins,
  },
  cardDateDescription: {
    fontSize: 14,
    lineHeight: 18,
    color: Colors.dark.neutral100,
    fontWeight: '400',
    fontFamily: Fonts.RegularPoppins,
  },
  cardReasonTitle: {
    fontSize: 14,
    lineHeight: 18,
    color: Colors.dark.neutral100,
    fontWeight: '600',
    fontFamily: Fonts.SemiBoldPoppins,
  },
  cardIcon: {
    alignSelf: 'center',
  },
  grayLine: {
    width: '100%',
    height: 1,
    backgroundColor: Colors.dark.neutral20,
  },
  dataContainer: {
    flex: 1,
    paddingVertical: 16,
  },
  swipeUpDateContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  swipeUpDateTitle: {
    flexDirection: 'row',
    marginBottom: 8,
  },
  swipeUpdateLeftField: {
    flex: 1,
    marginRight: 8,
  },
  swipeUpdateRightField: {
    flex: 1,
  },
  swipeUpDateButton: {
    flexDirection: 'row',
    paddingVertical: 11,
    paddingHorizontal: 16,
    backgroundColor: Colors.dark.neutral10,
    borderRadius: 30,
    marginBottom: 32,
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  swipeUpDateLabelButton: {
    fontSize: 14,
    lineHeight: 22,
    color: Colors.dark.neutral100,
    fontWeight: '600',
    fontFamily: Fonts.SemiBoldPoppins,
    textAlign: 'center',
  },
  swipeUpContainer: {
    padding: 16,
  },
  swipeUpDateWrapperField: {
    height: 85,
  },
  swipeUpDateWrapper: {
    height: 300,
  },
  swipeUpHeaderTitle: {
    fontSize: 20,
    lineHeight: 28,
    color: Colors.dark.neutral100,
    fontWeight: '600',
    fontFamily: Fonts.SemiBoldPoppins,
    textAlign: 'center',
    marginBottom: 16,
  },
  swipeUpDateHeaderTitle: {
    fontSize: 20,
    lineHeight: 28,
    color: Colors.dark.neutral100,
    fontWeight: '600',
    fontFamily: Fonts.SemiBoldPoppins,
    textAlign: 'center',
  },
  swipeUpTitle: {
    fontSize: 14,
    lineHeight: 18,
    color: Colors.dark.neutral60,
    fontWeight: '600',
    fontFamily: Fonts.SemiBoldPoppins,
    marginBottom: 16,
  },
  swipeUpContent: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    marginBottom: 16,
  },
  swipeUpLabelActiveContainer: {
    paddingVertical: 5,
    paddingHorizontal: 12,
    backgroundColor: Colors.primary.base,
    borderRadius: 20,
    marginBottom: 8,
    flexDirection: 'row',
    marginRight: 8,
  },
  swipeUpLabelPassiveContainer: {
    marginRight: 8,
    flexDirection: 'row',
    marginBottom: 8,
    borderRadius: 20,
    paddingVertical: 5,
    paddingHorizontal: 12,
    backgroundColor: Colors.primary.light3,
  },
  swipeUpLabelActive: {
    fontSize: 14,
    lineHeight: 22,
    color: Colors.white,
    fontWeight: '400',
    fontFamily: Fonts.RegularPoppins,
  },
  swipeUpLabelPassive: {
    fontSize: 14,
    lineHeight: 18,
    color: Colors.primary.base,
    fontWeight: '400',
    fontFamily: Fonts.RegularPoppins,
  },
  swipeUpButtonWrapper: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingBottom: 8,
  },
  swipeUpDateButtonWrapper: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingBottom: 8,
    paddingHorizontal: 16,
  },
  swipeUpButtonCancel: {
    flex: 1,
    marginRight: 8,
  },
  swipeUpButtonConfirm: {
    flex: 1,
  },
  noDataContainer: {
    flex: 1,
    backgroundColor: Colors.white,
    alignItems: 'center',
    justifyContent: 'center',
  },
  noDataIcon: {
    width: 120,
    height: 120,
    marginBottom: 12,
  },
  noDataTitle: {
    fontWeight: '600',
    fontSize: 16,
    lineHeight: 20,
    color: Colors.dark.neutral100,
    fontFamily: Fonts.SemiBoldPoppins,
    textAlign: 'center',
    marginBottom: 6,
  },
  noDataDescription: {
    fontSize: 14,
    lineHeight: 18,
    color: Colors.dark.neutral60,
    fontWeight: '400',
    fontFamily: Fonts.RegularPoppins,
    textAlign: 'center',
  },
  noDataButton: {
    width: '35%',
  },
  tabContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  tabCard: {
    alignItems: 'center',
    flex: 1,
  },
  tabCloseButton: {
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 25,
    width: 30,
    height: 30,
    backgroundColor: Colors.primary.light3,
    marginRight: 10,
  },
  lineActive: {
    backgroundColor: Colors.primary.base,
    height: 4,
    width: '100%',
    borderTopLeftRadius: 10,
    borderTopRightRadius: 10,
  },
  tabTitleActive: {
    fontWeight: '600',
    fontSize: 14,
    lineHeight: 22,
    color: Colors.primary.base,
    fontFamily: Fonts.SemiBoldPoppins,
    textAlign: 'center',
    marginBottom: 6,
  },
  tabTitlePassive: {
    fontWeight: '600',
    fontSize: 14,
    lineHeight: 22,
    color: Colors.dark.neutral80,
    fontFamily: Fonts.SemiBoldPoppins,
    textAlign: 'center',
    marginBottom: 6,
  },
});
