// Docx 6569567105caa0c059c9347f
// PDF 656957eb05caa0c059c93480
// IMAGE 653f57dbe29e21116102aa52
export const mockLKPDTask: ILKPDTask = {
  task_teacher: {
    id: 2,
    user_id: 13,
    user: {
      id: 13,
      user_type_id: 1,
      class_id: 5,
      username: 'bapakapdy@gmail.com',
      gender: 'Null',
      phone_number: '081246464195',
      full_name: 'Bapak Apdy',
      password: 'Babangciko12',
      max_password_failed: 10,
      otp: '9945',
      max_otp_failed: 3,
      max_request_otp: 10,
      attempted_request_after_failed: 3,
      user_type: {},
      school: {
        degree: {},
      },
      class: {},
    },
    type: 'PR',
    question_type: 'Buat Soal',
    curriculum_id: 1,
    curriculum: {
      id: 1,
      name: 'KTPSP',
      image: 'example.com',
    },
    rombel_class_school_id: 3,
    rombel_class_school: {
      id: 3,
      rombel_id: 2,
      class_id: 5,
      school_id: 2,
      name: 'Kelas 5 - B',
    },
    subject_id: 1,
    subject: {
      id: 1,
      class_id: 5,
      curriculum_id: 1,
      name: 'Bahasa Indonesia',
      icon_mobile: '63a1aede0ff605f45e3b7fe3',
      icon_web: '63a1aede0ff605f45e3b7fe3',
      is_active: true,
      coin_default: 4,
      class: {},
      curriculum: {},
      major: {},
    },
    chapter_id: 2,
    chapter: {
      id: 2,
      subject_id: 1,
      name: 'Bab 1 Hiperbola',
      is_active: true,
    },
    title: 'PR Pola Bilangan',
    time_start: '2023-01-02T08:00:00Z',
    time_finish: '2023-01-02T09:30:44Z',
    instructions:
      'Silahkan kerjakan soal dengan teliti dengan menjawab soal Pilihan Ganda & Esay yang tersedia.',
    media_id: '6569567105caa0c059c9347f',
    status: 'done',
  },
  task_student: {
    id: 6,
    task_teacher_id: 2,
    task_teacher: {
      id: 2,
      user_id: 13,
      type: 'PR',
      question_type: 'Buat Soal',
      curriculum_id: 1,
      rombel_class_school_id: 3,
      subject_id: 1,
      chapter_id: 2,
      title: 'PR Pola Bilangan',
      time_start: '2023-01-02T08:00:00Z',
      time_finish: '2023-01-02T09:30:44Z',
      instructions:
        'Silahkan kerjakan soal dengan teliti dengan menjawab soal Pilihan Ganda & Esay yang tersedia.',
      media_id: '',
      status: 'done',
    },
    user_id: 13,
    user: {
      id: 13,
      user_type_id: 1,
      class_id: 5,
      username: 'bapakapdy@gmail.com',
      gender: 'Null',
      phone_number: '081246464195',
      full_name: 'Bapak Apdy',
      password: 'Babangciko12',
      max_password_failed: 10,
      otp: '9945',
      max_otp_failed: 3,
      max_request_otp: 10,
      attempted_request_after_failed: 3,
      user_type: {},
      school: {
        degree: {},
      },
      class: {},
    },
    correction_type: 'finish',
    status: 'finish',
    correct: 2,
    wrong: 1,
    skip: 1,
    value: 50,
    description: '',
    image_id: '',
    time_start: '2022-12-29T14:33:40Z',
    time_finish: '2022-12-29T14:25:07Z',
    time_correction: '2023-01-02T11:24:47Z',
  },
};
