import Colors from '@constants/colors';
import Fonts from '@constants/fonts';
import {StyleSheet} from 'react-native';

export const styles = StyleSheet.create({
  contentContainerStyle: {
    flexGrow: 1,
  },
  bgBlueOrnament: {
    resizeMode: 'cover',
    width: '100%',
    position: 'absolute',
    zIndex: -1,
    backgroundColor: Colors.primary.background,
  },
  styleLabel: {
    fontWeight: '600',
    fontSize: 16,
    lineHeight: 20,
    textAlign: 'center',
  },
  content: {
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
    padding: 16,
    backgroundColor: Colors.primary.background2,
    paddingBottom: 32,
    flex: 1,
  },
  topCard: {
    paddingHorizontal: 16,
    paddingTop: 24,
    paddingBottom: 29,
    borderRadius: 10,
    backgroundColor: Colors.white,
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 1,
    },
    shadowOpacity: 0.1,
    shadowRadius: 1.84,
    elevation: 2,
    marginBottom: 16,
  },
  headTitleTopCard: {
    fontWeight: '400',
    fontSize: 16,
    lineHeight: 20,
    textAlign: 'center',
    color: Colors.dark.neutral80,
    fontFamily: Fonts.RegularPoppins,
  },
  headDescriptionTopCard: {
    fontWeight: '600',
    fontSize: 32,
    lineHeight: 40,
    textAlign: 'center',
    color: Colors.primary.base,
    fontFamily: Fonts.SemiBoldPoppins,
    marginBottom: 24,
  },
  contentRow: {
    flexDirection: 'row',
    justifyContent: 'center',
    marginBottom: 24,
  },
  blueCard: {
    borderRadius: 10,
    backgroundColor: Colors.primary.light3,
    padding: 16,
  },
  gap: {
    width: 16,
  },
  titleTopCard: {
    fontWeight: '400',
    fontSize: 14,
    lineHeight: 18,
    textAlign: 'center',
    color: Colors.dark.neutral80,
    fontFamily: Fonts.RegularPoppins,
  },
  descriptionTopCard: {
    fontWeight: '600',
    fontSize: 20,
    lineHeight: 28,
    textAlign: 'center',
    color: Colors.primary.base,
    fontFamily: Fonts.SemiBoldPoppins,
  },
  historyTopCard: {
    fontWeight: '600',
    fontSize: 14,
    lineHeight: 22,
    textAlign: 'center',
    color: Colors.primary.base,
    fontFamily: Fonts.SemiBoldPoppins,
  },
  bottomCard: {
    paddingHorizontal: 16,
    paddingTop: 16,
    paddingBottom: 21,
    borderRadius: 10,
    backgroundColor: Colors.white,
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 1,
    },
    shadowOpacity: 0.1,
    shadowRadius: 1.84,
    elevation: 2,
  },
  titleBottomCard: {
    fontWeight: '400',
    fontSize: 12,
    lineHeight: 16,
    textAlign: 'center',
    color: Colors.dark.neutral100,
    fontFamily: Fonts.RegularPoppins,
    marginBottom: 8,
  },
  requestAttendanceBottomCard: {
    flexDirection: 'row',
    justifyContent: 'center',
    marginBottom: 13,
    borderRadius: 20,
    alignSelf: 'center',
    paddingHorizontal: 12,
    paddingVertical: 5,
    backgroundColor: Colors.primary.light3,
    width: '75%',
  },
  requestAttendanceBottomTitle: {
    fontWeight: '600',
    fontSize: 14,
    lineHeight: 22,
    textAlign: 'center',
    color: Colors.primary.base,
    fontFamily: Fonts.SemiBoldPoppins,
  },
  historyBottomCard: {
    fontWeight: '600',
    fontSize: 14,
    lineHeight: 22,
    textAlign: 'center',
    color: Colors.primary.base,
    fontFamily: Fonts.SemiBoldPoppins,
  },
});
