import { StyleSheet, Dimensions } from 'react-native'

const { width, height } = Dimensions.get('window')

const styles = StyleSheet.create({
  container: {
    padding: 16,
    backgroundColor: '#fff',
    width: width * 0.9,
    maxWidth: 400,
    borderRadius: 12,
    borderColor: '#CED4DA',
    borderWidth: 1,
    alignSelf: 'center',
    marginTop: height * 0.05,
    minHeight: height * 0.6,
  },
  headerContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  questionNumberContainer: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: '#F1F3F9',
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 8,
  },
  questionNumber: {
    fontFamily: 'Poppins_600SemiBold',
    fontSize: 14,
    color: '#1D252D',
  },
  questionTitle: {
    fontFamily: 'Poppins_600SemiBold',
    fontSize: 18,
    color: '#0055B8',
    flex: 1,
    lineHeight: 24,
  },
  trashIcon: {
    marginLeft: 10,
    borderRadius: 24,
    paddingVertical: 10,
    paddingHorizontal: 10,
    backgroundColor: '#EFF7FF',
  },
  trashIcon1: {
    padding: 10,
  },
  section: {
    marginBottom: 20,
  },
  sectionTitle: {
    fontFamily: 'Poppins_600SemiBold',
    fontSize: 16,
    lineHeight: 20,
    marginTop: 16,
    textAlign: 'left',
    marginBottom: 10,
  },
  inputContainer: {
    backgroundColor: '#F1F3F9',
    borderRadius: 10,
    padding: 15,
    marginBottom: 10,
  },
  textInput: {
    fontFamily: 'Poppins_400Regular',
    minHeight: 80,
    fontSize: 14,
    color: '#868E96',
  },
  toolbarContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 8,
    backgroundColor: '#F5F7F9',
    borderRadius: 12,
    alignItems: 'center',
  },
  iconButton: {
    padding: 10,
    borderRadius: 15,
  },
  mathTypeButton: {
    marginTop: 10,
    alignSelf: 'flex-end',
    backgroundColor: '#FFFFFF',
    paddingVertical: 8,
    paddingHorizontal: 24,
    borderRadius: 8,
    justifyContent: 'center',
  },
  mathTypeText: {
    fontFamily: 'Poppins_600SemiBold',
    fontSize: 12,
    color: '#0055B8',
  },
  addMediaButton: {
    alignSelf: 'flex-start',
    paddingVertical: 4,
    paddingHorizontal: 12,
    borderRadius: 10,
    backgroundColor: '#EFF7FF',
    flexDirection: 'row',
    alignItems: 'center',
  },
  addMediaText: {
    fontFamily: 'Poppins_600SemiBold',
    fontSize: 14,
    color: '#3A7CE2',
  },
  userIconContainer: {
    position: 'absolute',
    bottom: 15,
    right: 70,
    width: 30,
    height: 30,
    borderRadius: 15,
    backgroundColor: '#3A7CE2',
    justifyContent: 'center',
    alignItems: 'center',
  },
  horizontalRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: 10,
    justifyContent: 'space-between',
  },
  button: {
    width: 118,
    height: 32,
    paddingVertical: 10,
    paddingHorizontal: 16,
    borderRadius: 30,
    backgroundColor: '#007bff',
    justifyContent: 'center',
    alignItems: 'center',
  },
  buttonText: {
    color: '#ffffff',
    fontSize: 14,
    lineHeight: 24,
    fontFamily: 'Poppins_600SemiBold',
  },
  // Additional Styles
  userIcon: {
    fontSize: 16,
    color: '#FFFFFF',
  },
  imageIcon: {
    width: 16,
    height: 16,
    tintColor: '#A3A3A3',
  },
  iconContainer: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: '#EFF7FF',
    justifyContent: 'center',
    alignItems: 'center',
  },
  questionContainer: {
    marginBottom: 16,
  },
  questionText: {
    fontFamily: 'Poppins_400Regular',
    fontSize: 16,
    color: '#4D545C',
    lineHeight: 24,
    marginBottom: 12,
  },
  answerContainer: {
    backgroundColor: '#E6F0FF',
    borderRadius: 8,
    padding: 10,
    marginBottom: 16,
  },
  answerText: {
    fontFamily: 'Poppins_400Regular',
    fontSize: 14,
    color: '#1D252D',
  },
  explanationContainer: {
    paddingVertical: 10,
    paddingHorizontal: 16,
    borderRadius: 8,
    backgroundColor: '#F8F9FA',
  },
  explanationTitle: {
    fontFamily: 'Poppins_600SemiBold',
    fontSize: 14,
    color: '#000000',
    lineHeight: 24,
    marginBottom: 8,
  },
  explanationText: {
    fontFamily: 'Poppins_400Regular',
    fontSize: 16,
    color: '#1D252D',
    lineHeight: 27.2,
  },
})

export default styles
