import {StyleSheet} from 'react-native';
import Colors from '@constants/colors';

export default StyleSheet.create({
  container: {},
  soalTestContainer: {
    width: '100%',
    paddingBottom: 100,
    backgroundColor: 'white',
  },
  soalTestHeaderContainer: {
    width: '100%',
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: '3%',
  },
  soalTestHeaderTextBottom: {
    fontFamily: 'Poppins-SemiBold',
    fontSize: 20,
    lineHeight: 28,
    color: Colors?.dark?.neutral100,
  },
  soalTestInfoButtonText: {
    fontSize: 14,
    fontFamily: 'Poppins-Regular',
    lineHeight: 22,
    letterSpacing: 0.25,
    color: Colors?.primary?.base,
  },
  soalTestRulesContainer: {
    width: '100%',
    marginTop: '5%',
    paddingHorizontal: '5%',
  },
  soalTestSubmitButtonContainer: {
    width: '100%',
    position: 'absolute',
    bottom: 20,
    justifyContent: 'center',
    alignItems: 'center',
  },
  soalTestSubmitButton: {width: '90%'},
  soalTestRulesTitleText: {
    fontFamily: 'Poppins-SemiBold',
    fontSize: 14,
    lineHeight: 22,
    letterSpacing: 0.25,
    color: Colors?.dark?.neutral100,
  },
  soalTestInfoButtonContainer: {
    paddingHorizontal: 10,
    paddingVertical: 5,
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 20,
    backgroundColor: Colors?.primary?.light3,
    marginRight: 4,
  },
  soalTestInfoContainer: {
    width: '100%',
    alignItems: 'center',
    justifyContent: 'center',
    flexDirection: 'row',
    marginTop: '3%',
  },
  soalTestHeaderTextTop: {
    fontFamily: 'Poppins-SemiBold',
    fontSize: 14,
    lineHeight: 18,
    letterSpacing: 0.25,
    color: Colors?.primary?.base,
    marginBottom: 8,
  },
  soalCardTitleContainer: {
    flex: 1,
    justifyContent: 'flex-end',
    marginBottom: 10,
  },
  soalCardTitleContainerKuis: {flex: 5, justifyContent: 'center'},
  soalCardTitleContainerKuis2: {
    flex: 1,
    alignItems: 'flex-end',
    justifyContent: 'center',
  },
  soalCardContainer: {
    width: '100%',
    marginTop: 10,
    paddingVertical: 10,
    paddingHorizontal: '5%',
    borderRadius: 10,
    backgroundColor: 'white',
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
    elevation: 5,
  },
  soalCardContainerKuis: {
    width: '100%',
    marginTop: 12,
    flexDirection: 'row',
    paddingVertical: 10,
    paddingHorizontal: '5%',
    borderRadius: 10,
    backgroundColor: 'white',
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
    elevation: 5,
  },
});
