import {StyleSheet} from 'react-native';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    width: '100%',
  },
  openButton: {
    padding: 10,
    backgroundColor: '#007BFF',
    borderRadius: 5,
  },
  openButtonText: {
    color: '#fff',
    fontSize: 16,
  },
  modal: {
    justifyContent: 'flex-end',
    margin: 0,
  },
  modalView: {
    backgroundColor: 'white',
    borderTopRightRadius: 20,
    borderTopLeftRadius: 20,
    paddingTop: 8,
    paddingRight: 16,
    paddingBottom: 16,
    paddingLeft: 16,
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 4,
    elevation: 5,
    width: '100%',
  },
  header: {
    fontSize: 14,
    color: '#A0A0A0',
    marginBottom: 5,
  },
  title: {
    fontSize: 19,
    fontWeight: '600',
    lineHeight: 28,
    letterSpacing: 0.01,
    textAlign: 'center',
    marginBottom: 4,
  },
  nilaiContainer: {
    height: 'auto',
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 13,
    opacity: 1,
    backgroundColor: 'transparent',
  },
  nilai: {
    fontSize: 14,
    fontWeight: '400',
    lineHeight: 22,
    letterSpacing: 0.25,
    textAlign: 'center',
    width: 132,
    height: 22,
    opacity: 1,
    color: '#868E96',
    paddingTop: 2,
    marginBottom: 4,
  },
  value: {
    fontSize: 24,
    fontWeight: '600',
    lineHeight: 32,
    letterSpacing: 0.01,
    textAlign: 'center',
    color: '#0055B8',
  },
  statsContainer: {
    flexDirection: 'row',
    justifyContent: 'space-around',
    alignItems: 'center',
    width: '100%',
    marginBottom: 12,
  },
  cardContainer: {
    width: 320,
    height: 'auto',
    paddingTop: 16,
    paddingRight: 0,
    paddingBottom: 0,
    paddingLeft: 0,
    backgroundColor: '#FFFFFF',
    borderRadius: 10,
    opacity: 1,
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 3,
    },
    shadowOpacity: 0.1,
    shadowRadius: 10,
    elevation: 5, // Shadow for Android
  },
  stats: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 0,
    opacity: 1,
  },
  correct: {
    fontSize: 16,
    fontWeight: '600',
    lineHeight: 20,
    letterSpacing: 0.01,
    textAlign: 'center',
    color: '#019859',
  },
  correctLabel: {
    fontSize: 14,
    fontWeight: '400',
    lineHeight: 18,
    letterSpacing: 0.25,
    textAlign: 'center',
    color: 'green',
    opacity: 1,
  },
  wrong: {
    fontSize: 16,
    fontWeight: '600',
    lineHeight: 20,
    letterSpacing: 0.01,
    textAlign: 'center',
    color: '#D92037',
  },
  wrongLabel: {
    fontSize: 14,
    fontWeight: '400',
    lineHeight: 18,
    letterSpacing: 0.25,
    textAlign: 'center',
    color: '#D92037',
    opacity: 1,
  },
  skipped: {
    fontSize: 16,
    fontWeight: '600',
    lineHeight: 20,
    letterSpacing: 0.01,
    textAlign: 'center',
    color: '#868E96',
  },
  skippedLabel: {
    fontSize: 14,
    fontWeight: '400',
    lineHeight: 18,
    letterSpacing: 0.25,
    textAlign: 'center',
    color: '#868E96',
    opacity: 1,
  },
  divider: {
    width: 288,
    height: 0,
    borderTopWidth: 0.6,
    borderTopColor: '#CED4DA',
    alignSelf: 'center',
    opacity: 1,
    marginBottom: 0,
  },
  duration: {
    fontSize: 14,
    fontWeight: '400',
    lineHeight: 18,
    letterSpacing: 0.25,
    textAlign: 'left',
    color: '#868E96',
  },
  icon: {
    width: 16,
    height: 16,
    padding: 1.33,
    marginRight: 4,
    opacity: 1,
    color: '#0055B8',
  },
  timeText: {
    fontSize: 14,
    fontWeight: '600',
    lineHeight: 18,
    letterSpacing: 0.25,
    textAlign: 'center',
    color: '#0055B8',
    justifyContent: 'center',
    alignItems: 'center',
    opacity: 1,
  },
  date: {
    fontSize: 14,
    fontWeight: '400',
    lineHeight: 18,
    letterSpacing: 0.25,
    textAlign: 'center',
    color: '#868E96',
    justifyContent: 'center',
    alignItems: 'center',
    opacity: 1,
  },
  infoContainer: {
    alignItems: 'center',
    justifyContent: 'center',
    width: 'auto',
    gap: 4,
    marginTop: 4,
  },
});
