import Colors from '@constants/colors';
import Fonts from '@constants/fonts';
import {StyleSheet} from 'react-native';

export const styles = StyleSheet.create({
  container: {backgroundColor: Colors.white, padding: 16},
  BtnContainer: {
    justifyContent: 'space-around',
  },
  button: {
    paddingVertical: 5,
    paddingHorizontal: 12,
    marginRight: 8,
  },
  middleContainer: {
    flexDirection: 'column',
    flexGrow: 1,
  },
  searchNotFoundContainer: {
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: 130,
  },
  searchTipsOrNotFound: {
    justifyContent: 'center',
    alignItems: 'center',
  },
  searchTipsOrNotFoundTitle: {
    marginTop: 12,
    fontFamily: 'Poppins-SemiBold',
    fontWeight: '600',
    fontSize: 16,
    lineHeight: 24,
    letterSpacing: 1,
    textAlign: 'center',
    color: Colors.dark.neutral100,
  },
  searchTipsOrNotFoundDescription: {
    marginTop: 6,
    fontFamily: 'Poppins-Regular',
    fontWeight: '400',
    fontSize: 14,
    lineHeight: 18,
    letterSpacing: 0.25,
    textAlign: 'center',
    color: Colors.dark.neutral60,
  },
  swipeUpContainerSoal: {
    backgroundColor: Colors.white,
    flexGrow: 1,
  },
  swpTopContent: {
    padding: 16,
    paddingTop: 0,
  },
  rectangle: {
    backgroundColor: Colors.dark.neutral10,
    height: 4,
    marginVertical: '8%',
    width: '100%',
    padding: 0,
  },
  swpMiddleContent3: {
    flexDirection: 'row',
    flexWrap: 'wrap',
  },
  soalSubContent: {
    flexDirection: 'column',
    width: '70%',
    marginBottom: '4%',
  },
  soalTitle: {
    marginLeft: '4%',
    fontFamily: 'Poppins-SemiBold',
    color: Colors.dark.neutral100,
    fontSize: 14,
    lineHeight: 22,
  },
  soalText: {
    marginLeft: '4%',
    fontFamily: 'Poppins-Regular',
    color: Colors.dark.neutral80,
    fontSize: 12,
    lineHeight: 16,
  },
  swpBottomContentSoal: {
    marginHorizontal: 32,
    marginBottom: 16,
    justifyContent: 'center',
    alignItems: 'center',
    flexDirection: 'row',
  },
  SoalButton: {
    width: '55%',
    marginHorizontal: '2%',
  },
  swpMiddleContentSoal: {
    justifyContent: 'center',
    alignItems: 'center',
  },
  swpTopTitle2Container: {alignItems: 'center'},
  swpTopTitle: {
    fontFamily: 'Poppins-SemiBold',
    color: Colors.dark.neutral100,
    fontSize: 20,
    lineHeight: 28,
    fontWeight: '600',
    paddingBottom: 8,
    alignSelf: 'center',
  },
  swpSubTitle: {
    fontFamily: Fonts.SemiBoldPoppins,
    fontSize: 14,
    lineHeight: 18,
    letterSpacing: 0.25,
    color: Colors.dark.neutral60,
  },
  chips: {
    backgroundColor: Colors.primary.light3,
    paddingVertical: 5,
    paddingHorizontal: 12,
    borderRadius: 20,
    marginTop: 4,
    alignSelf: 'flex-end',
    marginRight: 8,
    marginVertical: 16,
  },
  chipsBold: {
    backgroundColor: Colors.success.light2,
    paddingVertical: 2,
    paddingHorizontal: 8,
    borderRadius: 20,
    alignSelf: 'flex-end',
  },
  chipsText: {
    fontFamily: Fonts.RegularPoppins,
    fontSize: 14,
    lineHeight: 22,
    letterSpacing: 0.25,
    color: Colors.primary.base,
    fontWeight: '400',
    textAlign: 'center',
  },
  chipsTextBold: {
    fontFamily: Fonts.SemiBoldPoppins,
    fontWeight: '600',
    fontSize: 11,
    lineHeight: 16,
  },

  dateContainer: {
    width: '100%',
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 16,
  },
  dateItem: {
    width: '49%',
  },
  dateText: {
    fontFamily: Fonts.SemiBoldPoppins,
    color: Colors.dark.neutral100,
    width: '90%',
  },
  dateContainerText: {
    paddingVertical: 10,
    paddingHorizontal: 16,
    borderRadius: 15,
    backgroundColor: Colors.primary.light4,
    justifyContent: 'space-between',
    flexDirection: 'row',
  },
  titleDate: {
    fontFamily: 'Poppins-Bold',
    color: Colors.dark.neutral60,
    fontSize: 14,
  },
  titleBlue: {
    fontFamily: 'Poppins-Bold',
    fontSize: 18,
    color: Colors.primary.base,
  },
  itemTitle: {
    fontFamily: 'Poppins-Regular',
    fontSize: 18,
    lineHeight: 22,
    letterSpacing: 0.25,
    color: Colors.dark.neutral100,
    marginBottom: 8,
  },
  calendar: {
    flexDirection: 'column',
    height: 150,
  },
  transactionText: {
    fontFamily: Fonts.RegularPoppins,
    fontWeight: '400',
    lineHeight: 18,
    fontSize: 12,
    paddingBottom: 4,
    color: Colors.black,
    width: 150,
  },
  transactionDescription: {
    fontFamily: Fonts.RegularPoppins,
    fontWeight: '400',
    lineHeight: 18,
    fontSize: 12,
    paddingBottom: 4,
    color: Colors.black,
  },
  imageProof: {
    width: '100%',
    height: 237,
    backgroundColor: Colors.dark.neutral10,
    borderRadius: 10,
    marginTop: 16,
  },
  containerImageProof: {
    padding: 10,
    flexDirection: 'row',
    backgroundColor: Colors.dark.neutral10,
    width: '100%',
    marginVertical: 16,
    borderRadius: 8,
    alignItems: 'center',
  },
  imagePaymentProof: {
    width: 70,
    height: 50,
    backgroundColor: Colors.white,
    borderRadius: 4,
  },
  swipeUpMiddleContainer: {
    paddingTop: 8,
    justifyContent: 'flex-start',
    alignItems: 'flex-start',
    marginBottom: 32,
  },
  transactionRow: {
    flexDirection: 'row',
  },
});
