import Colors from '@constants/colors';
import {StyleSheet} from 'react-native';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: Colors.primary.base,
  },
  containerSection: {
    flex: 1,
    backgroundColor: Colors.white,
  },
  info: {
    alignItems: 'flex-start',
    backgroundColor: '#FFF0B4',
    padding: 10,
    borderRadius: 10,
    top: 30,
  },
  image: {
    width: 80,
    height: 80,
    alignSelf: 'center',
    borderRadius: 100,
  },
  scrollview: {
    backgroundColor: Colors.white,
    borderTopRightRadius: 30,
    borderTopLeftRadius: 30,
    flex: 1,
    paddingHorizontal: 16,
  },
  textTitle: {
    fontFamily: 'Poppins-Bold',
    color: Colors.dark.neutral60,
  },
  textTitleBlack: {
    fontFamily: 'Poppins-Bold',
    color: Colors.dark.neutral100,
  },
  textSubTitle: {
    fontFamily: 'Poppins-Regular',
    color: Colors.dark.neutral100,
    marginRight: 2,
    fontSize: 12,
    lineHeight: 18,
  },
  textSubTitleGreen: {
    fontFamily: 'Poppins-Regular',
    color: Colors.success.base,
    backgroundColor: Colors.success.light3,
    marginRight: 2,
    fontSize: 12,
    paddingHorizontal: 10,
    borderRadius: 30,
    width: '45%',
  },
  textSubTitleGrey: {
    fontFamily: 'Poppins-Regular',
    color: Colors.dark.neutral60,
    fontSize: 12,
    lineHeight: 18,
  },
  shadowProp: {
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
    elevation: 5,
  },
  card: {
    backgroundColor: Colors.white,
    borderRadius: 10,
    padding: 16,
    marginVertical: 10,
    width: '99%',
    alignSelf: 'center',
  },
  row: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  rowBetween: {
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  circleGreen: {
    width: 12,
    height: 12,
    borderRadius: 100,
    backgroundColor: Colors.success.base,
    marginRight: 5,
  },
  circleRed: {
    width: 12,
    height: 12,
    borderRadius: 100,
    backgroundColor: Colors.danger.base,
    marginRight: 5,
  },
  textTitleBigBlack: {
    fontFamily: 'Poppins-Bold',
    color: Colors.dark.neutral100,
    fontSize: 16,
  },
  textSubTitleBigBlack: {
    fontFamily: 'Poppins-Regular',
    color: Colors.dark.neutral100,
    fontSize: 12,
    lineHeight: 18,
  },
  textBlue: {
    fontFamily: 'Poppins-Regular',
    color: Colors.primary.base,
  },
  textBlueBold: {
    fontFamily: 'Poppins-Bold',
    color: Colors.primary.base,
  },
  labelBlue: {
    backgroundColor: Colors.primary.light3,
    paddingVertical: 5,
    paddingHorizontal: 10,
    borderRadius: 10,
    fontFamily: 'Poppins-Regular',
    color: Colors.primary.base,
    marginRight: 10,
  },
  line: {
    borderWidth: 0.5,
    marginVertical: 16,
    borderColor: Colors.dark.neutral20,
  },
  textRed: {
    fontFamily: 'Poppins-Regular',
    color: Colors.danger.base,
    fontSize: 12,
  },
  textWhite: {
    fontFamily: 'Poppins-Bold',
    color: Colors.white,
  },
  buttonJoin: {
    backgroundColor: Colors.primary.base,
    paddingVertical: 5,
    paddingHorizontal: 16,
    borderRadius: 20,
  },
  tabBarLabelStyle: {
    fontSize: 14,
    fontFamily: 'Poppins-Bold',
    textTransform: 'none',
  },
  tabBar: {
    height: 45,
    elevation: 0,
    borderBottomWidth: 1,
    borderBottomColor: Colors.dark.neutral20,
  },
  tabBarIndicator: {
    borderTopLeftRadius: 5,
    borderTopRightRadius: 5,
    height: 4,
    backgroundColor: Colors.primary.base,
  },
  modalHeader: {
    justifyContent: 'center',
    alignItems: 'center',
  },
  dropDown: {
    backgroundColor: Colors.primary.light3,
    padding: 10,
    borderRadius: 30,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  custom: {
    borderBottomWidth: 1,
    borderColor: Colors.dark.neutral40,
    paddingHorizontal: 16,
    paddingTop: 16,
    paddingBottom: 10,
  },
  circleBorderBlue: {
    width: 16,
    height: 16,
    borderWidth: 2,
    borderRadius: 100,
    borderColor: Colors.primary.base,
  },
  circleBlue: {
    width: 16,
    height: 16,
    borderWidth: 2,
    backgroundColor: Colors.primary.base,
    borderRadius: 100,
    borderColor: Colors.primary.base,
  },
  circleActive: {
    width: 24,
    height: 24,
    borderWidth: 8,
    borderColor: Colors.primary.base,
    borderRadius: 100,
    marginVertical: 2,
    marginRight: 5,
  },
  circleInActive: {
    width: 24,
    height: 24,
    borderWidth: 3,
    borderColor: Colors.dark.neutral50,
    borderRadius: 100,
    marginVertical: 5,
    marginRight: 5,
  },
});
