import Colors from '@constants/colors';
import Fonts from '@constants/fonts';
import {Dimensions, Platform, StyleSheet} from 'react-native';

const windowWidth = Dimensions.get('window').width;
const scaleFactor = Platform.OS === 'ios' ? windowWidth / 375 : 1;

const getComponentWidth = (scale: number) => {
  //0.1 == 10% width of device
  return windowWidth * scale * scaleFactor;
};

export const Styles = StyleSheet.create({
  cardExamMainContainer: {
    flexDirection: 'row',
    marginHorizontal: 10,
    marginBottom: 16,
  },
  flexRow: {flexDirection: 'row'},
  flex1: {flex: 1},
  tabMendatangSecondInnerContainer: {marginVertical: 20, paddingLeft: 10},
  popUpOnGoingDateFormatStyle: {
    width: '100%',
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 5,
    flexDirection: 'row',
  },
  tabRiwayatInner2Container: {marginVertical: 20, paddingLeft: 10},
  tab3: {marginRight: 3, marginLeft: 2, marginTop: 5},
  flex2: {flex: 2},
  detailButton: {paddingHorizontal: 10, paddingVertical: 5},
  doneScroingContainer: {width: '100%', alignItems: 'center'},
  justifyCenter: {justifyContent: 'center'},
  tabMendatangCalendarIconContainerStyle3: {marginRight: 7, marginLeft: 2},
  onGoingContainer: {flexDirection: 'row', marginTop: 5},
  doButton: {paddingHorizontal: 10, paddingVertical: 4},
  tabMendatangCalendarIconContainerStyle2: {
    marginRight: 3,
    marginLeft: 2,
    marginTop: 5,
  },
  popUpDoneSubjectNameStyle: {
    fontFamily: 'Poppins-SemiBold',
    color: Colors.dark.neutral60,
    fontSize: 14,
    lineHeight: 18,
    letterSpacing: 0.25,
  },
  popUpDoneTitleStyle: {
    textAlign: 'center',
    fontFamily: 'Poppins-SemiBold',
    color: Colors.dark.neutral100,
    fontSize: 20,
    lineHeight: 28,
    letterSpacing: 1,
  },
  popUpDoneMarkTitleStyle: {
    fontFamily: 'Poppins-Regular',
    color: Colors.dark.neutral60,
    fontSize: 14,
    lineHeight: 22,
    letterSpacing: 0.25,
  },
  popUpDoneExamStyle: {
    fontFamily: 'Poppins-SemiBold',
    color: Colors.dark.neutral60,
    fontSize: 24,
    lineHeight: 32,
    letterSpacing: 1,
    marginTop: 5,
    marginBottom: 30,
  },
  popUpDoneBodyContainerStyle: {
    backgroundColor: 'white',
    marginHorizontal: '5%',
    borderRadius: 10,
    marginBottom: 25,
    paddingVertical: 10,
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,

    elevation: 5,
  },
  popUpDoneTopInnerContainerStyle: {
    width: '100%',
    justifyContent: 'center',
    marginVertical: 10,
    flexDirection: 'row',
  },
  popUpDoneStripLeftContainerStyle: {
    fontFamily: 'Poppins-SemiBold',
    color: Colors.success.base,
    fontSize: 16,
    lineHeight: 20,
    letterSpacing: 1,
  },
  popUpDoneTrueStyle: {
    fontFamily: 'Poppins-Regular',
    color: Colors.success.base,
    fontSize: 14,
    lineHeight: 18,
    letterSpacing: 0.25,
    marginTop: 5,
  },
  popUpDoneStripMiddleStyle: {
    fontFamily: 'Poppins-SemiBold',
    color: Colors.danger.base,
    fontSize: 16,
    lineHeight: 20,
    letterSpacing: 1,
  },
  popUpDoneFalseStyle: {
    fontFamily: 'Poppins-Regular',
    color: Colors.danger.base,
    fontSize: 14,
    lineHeight: 18,
    letterSpacing: 0.25,
    marginTop: 5,
  },
  popUpDoneStripRightStyle: {
    fontFamily: 'Poppins-SemiBold',
    color: Colors.dark.neutral60,
    fontSize: 16,
    lineHeight: 20,
    letterSpacing: 1,
  },
  popUpDoneSkipStyle: {
    fontFamily: 'Poppins-Regular',
    color: Colors.dark.neutral60,
    fontSize: 14,
    lineHeight: 18,
    letterSpacing: 0.25,
    marginTop: 5,
  },
  popUpDoneSeparator1: {
    width: '80%',
    borderTopWidth: 0.5,
    alignSelf: 'center',
    marginVertical: 10,
  },
  popUpDoneDurationContainerStyle: {
    flexDirection: 'row',
    justifyContent: 'center',
    marginTop: 15,
  },
  popUpDoneDurationStyle: {
    fontFamily: 'Poppins-Regular',
    color: Colors.dark.neutral60,
    fontSize: 14,
    lineHeight: 18,
    letterSpacing: 0.25,
  },
  popUpDoneDurationValueStyle: {
    fontFamily: 'Poppins-SemiBold',
    color: Colors.primary.base,
    fontSize: 14,
    lineHeight: 18,
    letterSpacing: 0.25,
  },
  popUpDoneDateStyle: {
    fontFamily: 'Poppins-Regular',
    color: Colors.dark.neutral60,
    marginTop: 10,
    marginBottom: 20,
    fontSize: 14,
    lineHeight: 18,
    letterSpacing: 0.25,
  },
  popUpProcessSubjectStyle: {
    fontFamily: 'Poppins-SemiBold',
    color: Colors.dark.neutral60,
    fontSize: 14,
    lineHeight: 18,
    letterSpacing: 0.25,
  },
  popUpProcessChapterStyle: {
    fontFamily: 'Poppins-SemiBold',
    color: Colors.dark.neutral100,
    fontSize: 20,
    lineHeight: 28,
    letterSpacing: 1,
  },
  popUpProcessWarningStyle: {
    marginTop: 16.5,
    marginBottom: 32.5,
    marginVertical: 0,
    fontFamily: 'Poppins-Regular',
    color: Colors.dark.neutral100,
    fontSize: 14,
    lineHeight: 22,
    textAlign: 'center',
    letterSpacing: 0.25,
  },
  popUpDurationCOntainerSTyle: {
    flexDirection: 'row',
    justifyContent: 'center',
    marginTop: 15,
  },
  popUpProcessDurationStyle: {
    fontFamily: 'Poppins-Regular',
    color: Colors.dark.neutral60,
    fontSize: 14,
    lineHeight: 18,
    letterSpacing: 0.25,
  },
  popUpProcessDurationValueStyle: {
    fontFamily: 'Poppins-SemiBold',
    color: Colors.primary.base,
    fontSize: 14,
    lineHeight: 18,
    letterSpacing: 0.25,
  },
  popUpProcessDateStyle: {
    fontFamily: 'Poppins-Regular',
    color: Colors.dark.neutral60,
    marginTop: 10,
    marginBottom: 20,
    fontSize: 14,
    lineHeight: 18,
    letterSpacing: 0.25,
  },
  popUpOnGoingTitleStyle: {
    fontFamily: 'Poppins-SemiBold',
    color: Colors.dark.neutral60,
    fontSize: 14,
    lineHeight: 18,
    letterSpacing: 0.25,
  },
  popUpOnGoingSubjectStyle: {
    fontFamily: 'Poppins-SemiBold',
    color: Colors.dark.neutral100,
    fontSize: 20,
    lineHeight: 28,
    letterSpacing: 1,
  },
  popUpProcessLMSDateStyle: {
    fontFamily: 'Poppins-Regular',
    color: Colors.dark.neutral80,
    fontSize: 14,
    lineHeight: 18,
    letterSpacing: 0.25,
    marginLeft: 2,
  },
  popUpOngoingLeftBodyStyle: {
    width: '95%',
    flexDirection: 'row',
    backgroundColor: Colors.secondary.light2,
    borderRadius: 10,
    paddingVertical: 12,
    paddingHorizontal: 8,
    marginVertical: 10,
  },
  popUpOngoingWarningStyle: {
    fontFamily: 'Poppins-Regular',
    color: Colors.secondary.dark1,
    fontSize: 14,
    lineHeight: 18,
    letterSpacing: 0.25,
  },
  contentContainer: {flex: 1},
  labelActiveStyle: {
    fontFamily: 'Poppins-SemiBold',
    fontSize: 14,
    lineHeight: 22,
    letterSpacing: 0.25,
    color: Colors.primary.base,
    textTransform: 'capitalize',
  },
  mainContainer: {flex: 1, backgroundColor: Colors.white},
  labelInactiveStyle: {
    fontFamily: 'Poppins-SemiBold',
    fontSize: 14,
    lineHeight: 22,
    letterSpacing: 0.25,
    color: Colors.dark.neutral80,
    textTransform: 'capitalize',
  },
  tabContentContainerStyle: {
    width: '100%',
    backgroundColor: Colors.white,
  },
  tabFilterContainer: {
    flexDirection: 'row',
  },
  tabMapelFilterButtonStyle: {
    paddingVertical: 5,
    backgroundColor: Colors.primary.light3,
    borderRadius: 20,
    paddingHorizontal: 13,
    justifyContent: 'center',
    flexDirection: 'row',
    marginTop: '7%',
  },
  tabMapelFilterButtonStyle2: {
    paddingVertical: 5,
    backgroundColor: Colors.primary.light3,
    marginHorizontal: 10,
    borderRadius: 20,
    paddingHorizontal: 13,
    justifyContent: 'center',
    marginRight: 5,
    flexDirection: 'row',
  },
  tabMapelFilterButtonStyle3: {
    paddingVertical: 5,
    backgroundColor: Colors.primary.base,
    marginHorizontal: 10,
    borderRadius: 20,
    paddingHorizontal: 13,
    justifyContent: 'center',
    marginRight: 5,
    flexDirection: 'row',
  },
  tabMapelTitleStyle: {
    fontFamily: 'Poppins-SemiBold',
    fontSize: 13,
    lineHeight: 22,
    letterSpacing: 0.25,
    color: Colors.primary.base,
  },
  tabMapelTitleStyle2: {
    fontFamily: 'Poppins-SemiBold',
    fontSize: 13,
    lineHeight: 22,
    letterSpacing: 0.25,
    color: Colors.white,
  },
  tabMapelIconStyle: {transform: [{rotate: '90deg'}], marginLeft: 5},
  tabMapelIconStyle2: {marginLeft: 5, justifyContent: 'center'},
  popUpContentContainer: {},
  popUpContentContainer2: {},
  popUpTopContent: {flex: 1, backgroundColor: 'rgba(155,159,164,0.6)'},
  popUpContentInnerContainer: {
    width: '100%',
    maxHeight: 500,
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
    backgroundColor: 'white',
    paddingHorizontal: '5%',
  },
  popUpheaderStripIconContainer: {
    width: '100%',
    alignItems: 'center',
    paddingVertical: 15,
  },
  popUpFilterContainer: {
    width: '100%',
    alignItems: 'center',
    marginVertical: 10,
  },
  popUpFilterText: {
    fontFamily: 'Poppins-SemiBold',
    fontSize: 20,
    lineHeight: 28,
    color: Colors.dark.neutral100,
  },
  popUpSubHeaderContainer: {
    width: '100%',
    flexDirection: 'row',
    marginVertical: 10,
  },
  popUpSubHeaderLeft: {flex: 1},
  popUpSubHeaderLeftText: {
    fontFamily: 'Poppins-SemiBold',
    fontSize: 14,
    lineHeight: 18,
    color: Colors.dark.neutral60,
  },
  popUpSubHeaderRight: {flex: 1, alignItems: 'flex-end'},
  popUpSubHeaderRightText: {
    fontFamily: 'Poppins-SemiBold',
    fontSize: 14,
    lineHeight: 18,
    color: Colors.primary.base,
  },
  popUpSubjectListContainer: {
    width: '100%',
    marginVertical: 10,
    flexDirection: 'row',
    flexWrap: 'wrap',
  },
  popUpSubjectCard: {
    paddingHorizontal: 10,
    marginHorizontal: 5,
    marginVertical: 5,
    height: 32,
    justifyContent: 'center',
    backgroundColor: Colors.primary.light3,
    borderRadius: 20,
  },
  popUpSubjectCardChoosed: {
    paddingHorizontal: 10,
    marginHorizontal: 5,
    marginVertical: 5,
    height: 32,
    justifyContent: 'center',
    backgroundColor: Colors.primary.base,
    borderRadius: 20,
  },
  popUpSubjectCardText: {
    fontFamily: 'Poppins-Regular',
    fontSize: 14,
    lineHeight: 22,
    color: Colors.primary.base,
  },
  popUpSubjectCardTextChoosed: {
    fontFamily: 'Poppins-Regular',
    fontSize: 14,
    lineHeight: 22,
    color: Colors.white,
  },
  popUpShowAllContainer: {
    width: '100%',
    marginVertical: 10,
    flexDirection: 'row',
  },
  popUpShowAllButton: {
    fontFamily: 'Poppins-SemiBold',
    fontSize: 14,
    lineHeight: 18,
    color: Colors.dark.neutral60,
  },
  popUpSubmitButtonContainer: {
    marginTop: 20,
    marginBottom: 10,
    flexDirection: 'row',
  },
  popUpSubmitButton: {flex: 1, paddingHorizontal: 5},
  tabMendatangScrollContainer: {
    marginBottom: 100,
  },
  tabMendatangCardContainer: {
    width: '100%',
    backgroundColor: 'red',
    marginVertical: 10,
  },
  tabMendatangContainer: {flex: 1, backgroundColor: Colors.white},
  tabOnGoingCardContent: {
    width: getComponentWidth(0.8),
    marginHorizontal: 7,
    marginTop: 10,
    borderRadius: 8,
    backgroundColor: 'white',
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
    elevation: 5,
    paddingHorizontal: 15,
    paddingBottom: 16,
  },
  tabMendatangCardContent: {
    width: getComponentWidth(0.88),
    borderRadius: 8,
    marginVertical: 10,
    paddingHorizontal: 16,
    backgroundColor: 'white',
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
    elevation: 5,
  },
  tabMendatangCardbadge: {
    marginVertical: 20,
    borderRadius: 20,
    paddingHorizontal: 10,
    alignItems: 'center',
    backgroundColor: Colors.primary.light3,
  },
  tabMendatangCardBadgeText: {
    fontFamily: 'Poppins-Regular',
    textAlign: 'center',
    marginVertical: 2,
    fontSize: 12,
    color: Colors.primary.base,
  },
  tabMendatangCardBodyContent: {flexDirection: 'row'},
  tabMendatangSubjectName: {
    fontFamily: 'Poppins-Regular',
    fontSize: 11,
    lineHeight: 16,
    color: Colors.dark.neutral100,
  },
  tabMendatangChapterName: {
    fontFamily: 'Poppins-SemiBold',
    fontSize: 13,
    marginTop: 5,
    lineHeight: 16,
    color: Colors.dark.neutral100,
  },
  tabMendatangTimerContainer: {flex: 1, alignItems: 'flex-end'},
  tabMendatangTimerContainerOnProgress: {flex: 1, alignItems: 'flex-end'},
  tabMendatangTimerInnerContainer: {
    borderRadius: 10,
    backgroundColor: Colors.primary.light3,
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: 8,
    paddingVertical: 5,
  },
  tabMendatangTimerTitle: {
    fontFamily: 'Poppins-Regular',
    fontSize: 11,
    lineHeight: 16,
    color: Colors.dark.neutral100,
  },
  tabMendatangTimerTime: {
    fontFamily: 'Poppins-Regular',
    fontSize: 11,
    lineHeight: 16,
    color: Colors.dark.neutral100,
  },
  tabMendatangScheduleContainer: {flex: 1, marginTop: 8, marginBottom: 20},
  tabMendatangScheduleContainer2: {
    flex: 0.6,
    marginTop: 8,
    marginBottom: 20,
  },
  tabMendatangScheduleTitle: {
    fontFamily: 'Poppins-Regular',
    fontSize: 11,
    lineHeight: 16,
    color: Colors.dark.neutral60,
  },
  tabMendatangScheduleTitleOnProgress: {
    fontFamily: 'Poppins-Regular',
    fontSize: 12,
    lineHeight: 16,
    color: 'red',
    marginTop: 2,
  },
  tabMendatangScheduleDateContainer: {flexDirection: 'row'},
  tabMendatangCalendarIconContainerStyle: {
    justifyContent: 'center',
    marginRight: 2,
    paddingTop: 1,
  },
  tabMendatangScheduleDate: {
    fontFamily: 'Poppins-Regular',
    fontSize: 12,
    letterSpacing: 0.25,
    marginTop: 5,
    lineHeight: 16,
    color: Colors.dark.neutral80,
  },
  tabMendatangScheduleDate1: {
    fontFamily: 'Poppins-Regular',
    marginBottom: 5,
    fontSize: 11,
    letterSpacing: 0.25,
    marginTop: 5,
    lineHeight: 16,
    color: Colors.dark.neutral100,
  },
  tabMendatangScheduleMark: {
    fontFamily: 'Poppins-SemiBold',
    fontSize: 14,
    letterSpacing: 0.25,
    marginTop: 5,
    lineHeight: 16,
    color: Colors.primary.base,
  },
  tabMendatangScheduleMarkUndone: {
    fontFamily: 'Poppins-Regular',
    fontSize: 13,
    letterSpacing: 0.25,
    marginTop: 5,
    lineHeight: 16,
    color: Colors.dark.neutral80,
  },
  topContentContainer: {},
  topContentTitleContainer: {paddingHorizontal: 10, marginTop: 12},
  topContentTitle: {
    fontFamily: 'Poppins-SemiBold',
    fontSize: 16,
    lineHeight: 20,
    color: Colors.dark.neutral100,
  },
  topEmptyText: {
    marginTop: 15,
    fontFamily: 'Poppins-Regular',
    fontSize: 14,
    lineHeight: 18,
    letterSpacing: 0.25,
    color: Colors.dark.neutral60,
  },
  topEmptyContainer: {
    width: '100%',
    marginTop: 40,
    alignItems: 'center',
    paddingTop: 10,
  },
  topEmptyImage: {width: 120, height: 100},
  topContentCardContainer: {marginVertical: 10},
  contentContainerStyle: {
    paddingBottom: 130,
  },
  instructionText: {
    fontFamily: Fonts.RegularPoppins,
    fontSize: 14,
    lineHeight: 22,
    fontWeight: '400',
    color: Colors.dark.neutral100,
  },
  instructionLabel: {
    fontFamily: Fonts.SemiBoldPoppins,
    fontSize: 14,
    lineHeight: 22,
    fontWeight: '600',
    color: Colors.dark.neutral100,
  },
});
