import Colors from '@constants/colors';
import Fonts from '@constants/fonts';
import {StyleSheet} from 'react-native';

export const styles = StyleSheet.create({
  contentContainer: {
    backgroundColor: Colors.white,
    flex: 1,
    paddingHorizontal: 16,
  },
  rootContainer: {
    flex: 1,
    backgroundColor: Colors.white,
  },
  container: {
    flex: 1,
    padding: 16,
    backgroundColor: Colors.white,
  },
  popupIcon: {
    resizeMode: 'contain',
    height: 100,
    width: 100,
    alignSelf: 'center',
    marginBottom: 20,
  },
  popupTitle: {
    fontSize: 18,
    lineHeight: 24,
    color: Colors.dark.neutral100,
    fontWeight: '600',
    fontFamily: Fonts.SemiBoldPoppins,
    textAlign: 'center',
    marginBottom: 8,
  },
  popupSubtitle: {
    fontSize: 14,
    lineHeight: 22,
    color: Colors.dark.neutral80,
    fontWeight: '400',
    fontFamily: Fonts.RegularPoppins,
    textAlign: 'center',
    marginBottom: 20,
  },
  popupInputText: {
    height: 80,
    marginBottom: 16,
  },
  popupButtonContainer: {
    flexDirection: 'row',
    paddingTop: 16,
    justifyContent: 'space-between',
    width: '100%',
  },
  popupButton: {
    width: '48%',
  },
  emptyContentContainer: {
    flex: 1,
    padding: 16,
    backgroundColor: Colors.white,
    justifyContent: 'center',
    alignItems: 'center',
  },
  emptyContentIcon: {
    width: 100,
    height: 100,
    marginBottom: 12,
    alignSelf: 'center',
  },
  emptyContentTitle: {
    fontSize: 16,
    lineHeight: 20,
    color: Colors.dark.neutral100,
    fontWeight: '600',
    fontFamily: Fonts.SemiBoldPoppins,
    textAlign: 'center',
  },
  emptyContentSubtitle: {
    fontSize: 14,
    lineHeight: 18,
    color: Colors.dark.neutral60,
    fontWeight: '400',
    fontFamily: Fonts.RegularPoppins,
    textAlign: 'center',
  },
  contentContainerStyleTab: {
    flexGrow: 1,
    backgroundColor: Colors.white,
  },
  contentStyleTab: {
    flex: 1,
    flexDirection: 'row',
  },
  contentContainerStyle: {
    flexGrow: 1,
    backgroundColor: Colors.white,
    paddingHorizontal: 0.5,
    marginBottom: 4,
  },
  row: {
    flexDirection: 'row',
  },
  tabContainer: {
    alignItems: 'center',
    paddingHorizontal: 16,
    marginBottom: 6,
    flexDirection: 'row',
  },
  tabTitleActive: {
    fontSize: 14,
    lineHeight: 22,
    color: Colors.primary.base,
    fontWeight: '600',
    fontFamily: Fonts.SemiBoldPoppins,
    marginRight: 4,
  },
  tabTitlePassive: {
    fontSize: 14,
    lineHeight: 22,
    color: Colors.dark.neutral80,
    fontWeight: '600',
    fontFamily: Fonts.SemiBoldPoppins,
    marginRight: 4,
  },
  tabCountActiveContainer: {
    borderRadius: 100,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: Colors.primary.light2,
    paddingHorizontal: 5,
    paddingVertical: 2,
  },
  tabCountNotActiveContainer: {
    borderRadius: 100,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: Colors.dark.neutral10,
    paddingHorizontal: 5,
    paddingVertical: 2,
  },
  tabCountActiveTitle: {
    fontSize: 12,
    lineHeight: 16,
    color: Colors.primary.base,
    fontWeight: '600',
    fontFamily: Fonts.SemiBoldPoppins,
  },
  tabCountNotActiveTitle: {
    fontSize: 12,
    lineHeight: 16,
    color: Colors.dark.neutral60,
    fontWeight: '600',
    fontFamily: Fonts.SemiBoldPoppins,
  },
  tabBottomLineActive: {
    height: 4,
    backgroundColor: Colors.primary.base,
    borderTopLeftRadius: 16,
    borderTopRightRadius: 16,
  },
  tabBottomLineGrey: {
    height: 2,
    backgroundColor: Colors.dark.neutral20,
  },
  card: {
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 1,
    },
    shadowOpacity: 0.1,
    shadowRadius: 1.84,
    elevation: 2,
    backgroundColor: Colors.white,
    borderRadius: 10,
    width: '100%',
  },
  cardTopSection: {
    padding: 16,
    justifyContent: 'space-between',
    flexDirection: 'row',
    marginBottom: 16,
  },
  cardBottomSection: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingHorizontal: 16,
    paddingTop: 12,
    paddingBottom: 8,
    backgroundColor: Colors.primary.light4,
    borderBottomLeftRadius: 10,
    borderBottomRightRadius: 10,
  },
  evidenceTitle: {
    fontSize: 14,
    lineHeight: 22,
    color: Colors.primary.base,
    fontWeight: '600',
    fontFamily: Fonts.SemiBoldPoppins,
  },
  cardIcon: {
    width: 40,
    height: 40,
    borderRadius: 100,
  },
  cardTitle: {
    fontSize: 16,
    lineHeight: 24,
    color: Colors.dark.neutral100,
    fontWeight: '600',
    fontFamily: Fonts.SemiBoldPoppins,
  },
  cardNameTitle: {
    fontSize: 14,
    lineHeight: 18,
    color: Colors.dark.neutral100,
    fontWeight: '600',
    fontFamily: Fonts.SemiBoldPoppins,
  },
  cardNisTitle: {
    fontSize: 12,
    lineHeight: 16,
    color: Colors.dark.neutral100,
    fontWeight: '400',
    fontFamily: Fonts.RegularPoppins,
  },
  cardDateTitle: {
    fontSize: 11,
    lineHeight: 16,
    color: Colors.dark.neutral60,
    fontWeight: '400',
    fontFamily: Fonts.RegularPoppins,
    alignSelf: 'flex-end',
    marginBottom: 4,
  },
  cardPaymentForTitle: {
    fontSize: 14,
    lineHeight: 18,
    color: Colors.dark.neutral100,
    fontWeight: '600',
    fontFamily: Fonts.SemiBoldPoppins,
    marginBottom: 16,
    paddingHorizontal: 16,
  },
  cardSubtitle: {
    fontSize: 12,
    lineHeight: 16,
    color: Colors.dark.neutral60,
    fontWeight: '400',
    fontFamily: Fonts.RegularPoppins,
  },
  cardStatusContainer: {
    paddingHorizontal: 8,
    paddingVertical: 2,
    backgroundColor: Colors.secondary.light2,
    borderRadius: 20,
  },
  cardStatusTitle: {
    fontSize: 11,
    lineHeight: 16,
    color: Colors.orange.dark1,
    fontWeight: '600',
    fontFamily: Fonts.SemiBoldPoppins,
  },
  cardButtonContainer: {
    flex: 1,
    marginBottom: 16,
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingHorizontal: 16,
  },
  cardButton: {
    width: '48%',
  },
  gap: {
    height: 12,
  },
  buttonContainer: {
    padding: 16,
    backgroundColor: Colors.white,
  },
  verificationHeaderCotainer: {
    flexDirection: 'row',
    marginBottom: 8,
  },
  verificationHeadTitle: {
    fontSize: 18,
    lineHeight: 24,
    color: Colors.dark.neutral100,
    fontWeight: '600',
    fontFamily: Fonts.SemiBoldPoppins,
    marginRight: 4,
  },
  historyCard: {
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 1,
    },
    shadowOpacity: 0.1,
    shadowRadius: 1.84,
    elevation: 2,
    backgroundColor: Colors.white,
    borderRadius: 10,
    width: '100%',
    padding: 12,
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 24,
    marginTop: 16,
  },
  historyTitle: {
    fontSize: 14,
    lineHeight: 18,
    color: Colors.dark.neutral100,
    fontWeight: '600',
    fontFamily: Fonts.SemiBoldPoppins,
    marginBottom: 4,
  },
  historySubtitle: {
    fontSize: 12,
    lineHeight: 16,
    color: Colors.primary.base,
    fontWeight: '400',
    fontFamily: Fonts.RegularPoppins,
  },
  scrollViewStyle: {
    marginTop: 16,
  },
  scrollViewContentContainerStyle: {
    flexGrow: 1,
  },
  swipeUpEvidenceContainer: {
    padding: 16,
    maxHeight: 500,
  },
  swipeUpConfirmDateContainer: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'center',
    marginTop: 2,
  },
  swipeUpConfirmDateTitle: {
    fontSize: 12,
    lineHeight: 16,
    color: Colors.dark.neutral60,
    fontWeight: '400',
    fontFamily: Fonts.RegularPoppins,
  },
  swipeUpConfirmDateDescription: {
    fontSize: 12,
    lineHeight: 16,
    color: Colors.dark.neutral60,
    fontWeight: '700',
    fontFamily: Fonts.SemiBoldPoppins,
  },
  swipeUpEvidenceHeaderTitle: {
    fontSize: 20,
    lineHeight: 28,
    color: Colors.dark.neutral100,
    fontWeight: '600',
    fontFamily: Fonts.SemiBoldPoppins,
    textAlign: 'center',
  },
  swipeUpEvidenceTitle: {
    fontSize: 12,
    lineHeight: 18,
    color: Colors.black,
    fontWeight: '400',
    fontFamily: Fonts.RegularPoppins,
    width: 150,
    marginBottom: 4,
  },
  swipeUpEvidenceDecription: {
    fontSize: 12,
    lineHeight: 18,
    color: Colors.black,
    fontWeight: '400',
    fontFamily: Fonts.RegularPoppins,
    marginBottom: 4,
  },
  swipeUpEvidenceBadgeErrorContainer: {
    borderRadius: 20,
    backgroundColor: Colors.danger.light2,
    paddingHorizontal: 8,
    paddingVertical: 2,
  },
  swipeUpEvidenceBadgeErrorTitle: {
    fontSize: 11,
    lineHeight: 16,
    color: Colors.danger.base,
    fontWeight: '600',
    fontFamily: Fonts.SemiBoldPoppins,
  },
  swipeUpEvidenceBadgeSuccessContainer: {
    borderRadius: 20,
    backgroundColor: Colors.success.light2,
    paddingHorizontal: 8,
    paddingVertical: 2,
  },
  swipeUpEvidenceBadgeSuccessTitle: {
    fontSize: 11,
    lineHeight: 16,
    color: Colors.success.base,
    fontWeight: '600',
    fontFamily: Fonts.SemiBoldPoppins,
  },
  greyLine: {
    marginTop: 8,
    marginBottom: 16,
    height: 4,
    backgroundColor: Colors.dark.neutral20,
  },
  swipeUpEvidenceImage: {
    width: '100%',
    height: 250,
    borderRadius: 10,
    resizeMode: 'contain',
    marginBottom: 32,
  },
  swipeUpEvidenceButtonContainer: {
    paddingTop: 16,
  },
});
