import Colors from '@constants/colors';
import {StyleSheet} from 'react-native';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    marginTop: -40,
  },
  imageOutterContainer: {
    padding: 4,
    width: 80,
    height: 80,
    backgroundColor: Colors.yellow,
    borderRadius: 100,
    alignItems: 'center',
    justifyContent: 'center',
    alignSelf: 'center',
    marginBottom: 10,
  },
  imageOutterParentContainer: {
    padding: 4,
    width: 80,
    height: 80,
    backgroundColor: Colors.success.base,
    borderRadius: 100,
    alignItems: 'center',
    justifyContent: 'center',
    alignSelf: 'center',
    marginBottom: 10,
  },
  imageOutterHeadMasterContainer: {
    padding: 4,
    width: 80,
    height: 80,
    backgroundColor: Colors.primary.base,
    borderRadius: 100,
    alignItems: 'center',
    justifyContent: 'center',
    alignSelf: 'center',
    marginBottom: 10,
  },
  imageOutterAdminContainer: {
    padding: 4,
    width: 80,
    height: 80,
    backgroundColor: Colors.primary.light5,
    borderRadius: 100,
    alignItems: 'center',
    justifyContent: 'center',
    alignSelf: 'center',
    marginBottom: 10,
  },
  imageInnerContainer: {
    padding: 4,
    width: 72,
    height: 72,
    backgroundColor: Colors.white,
    borderRadius: 100,
    alignItems: 'center',
    justifyContent: 'center',
  },
  imageUser: {
    resizeMode: 'cover',
    width: 70,
    height: 70,
    borderRadius: 100,
  },
  badgeNameContainer: {
    flexDirection: 'row',
    marginBottom: 4,
    alignSelf: 'center',
  },
  badgeName: {
    fontSize: 16,
    lineHeight: 24,
    color: Colors.primary.base,
    fontWeight: '600',
    fontFamily: 'Poppins-SemiBold',
    textAlign: 'center',
    marginRight: 4,
  },
  iconEditContainer: {
    alignItems: 'center',
    justifyContent: 'center',
  },
  badgeClassContainer: {
    flexDirection: 'row',
    alignSelf: 'center',
    backgroundColor: Colors.yellow,
    paddingHorizontal: 10,
    paddingVertical: 2,
    borderRadius: 30,
    marginBottom: 24,
    flexWrap: 'wrap',
  },
  badgeClassText: {
    fontSize: 16,
    lineHeight: 24,
    color: Colors.primary.base,
    fontWeight: '600',
    fontFamily: 'Poppins-SemiBold',
    textAlign: 'center',
    marginRight: 4,
  },
  badgeClassParentContainer: {
    flexDirection: 'row',
    alignSelf: 'center',
    backgroundColor: Colors.success.base,
    paddingHorizontal: 10,
    paddingVertical: 2,
    borderRadius: 30,
    marginBottom: 24,
  },
  badgeClassParentText: {
    fontSize: 16,
    lineHeight: 24,
    color: Colors.white,
    fontWeight: '600',
    fontFamily: 'Poppins-SemiBold',
    textAlign: 'center',
    marginRight: 4,
  },
  badgeClassAdminContainer: {
    flexDirection: 'row',
    alignSelf: 'center',
    backgroundColor: Colors.primary.light5,
    paddingHorizontal: 10,
    paddingVertical: 2,
    borderRadius: 30,
    marginBottom: 24,
    flexWrap: 'wrap',
  },
  badgeClassAdminText: {
    fontSize: 16,
    lineHeight: 24,
    color: Colors.white,
    fontWeight: '600',
    fontFamily: 'Poppins-SemiBold',
    textAlign: 'center',
    marginRight: 4,
  },
});
