import Colors from '@constants/colors';
import {StyleSheet} from 'react-native';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    flexGrow: 1,
    paddingBottom: 16,
    backgroundColor: Colors.white,
  },
  videoContainerStyle: {
    flex: 1,
    justifyContent: 'flex-start',
  },
  videoContainer: {
    backgroundColor: Colors.white,
    justifyContent: 'flex-start',
  },
  empty: {width: 20, height: 20},
  videoStyle: {
    height: 400,
    alignItems: 'flex-start',
  },
  slider: {
    width: '100%',
  },
  title: {
    fontFamily: 'Poppins-Bold',
    fontWeight: '600',
    fontSize: 16,
    lineHeight: 24,
    letterSpacing: 0.01,
    color: Colors.dark.neutral100,
    width: '75%',
  },
  headerContent: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingHorizontal: 16,
    marginBottom: 20,
    marginTop: 10,
  },
  contentContainerStyle: {
    flex: 1,
  },
  contentContainer: {},
  switch: {
    flexDirection: 'row',
    alignItems: 'flex-end',
    justifyContent: 'space-between',
  },
  buttonSwtich: {
    width: '50%',
    height: 32,
    justifyContent: 'center',
  },
  textSwitch: {
    fontFamily: 'Poppins-Bold',
    fontSize: 14,
    lineHeight: 22,
    textAlign: 'center',
    letterSpacing: 0.25,
  },
  lineActive: {
    width: '50%',
    borderWidth: 4,
    borderColor: Colors.primary.base,
    borderTopLeftRadius: 10,
    borderTopRightRadius: 10,
  },
  controlMain: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    alignSelf: 'center',
    height: '100%',
  },
  time: {
    fontFamily: 'Poppins-Regular',
    color: Colors.white,
    fontSize: 12,
    marginLeft: 10,
  },
  lineDeactive: {
    width: '50%',
    borderWidth: 1,
    borderColor: Colors.dark.neutral40,
    borderTopLeftRadius: 10,
    borderTopRightRadius: 10,
  },
  description: {
    fontFamily: 'Poppins-Regular',
    fontSize: 14,
    lineHeight: 22,
    letterSpacing: 0.25,
  },
  listContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    borderBottomWidth: 1,
    padding: 20,
    borderColor: '#E7EBEE',
  },
  thumbail: {
    width: 80,
    height: 44,
    backgroundColor: Colors.dark.neutral20,
    borderRadius: 10,
  },
  textList: {
    fontFamily: 'Poppins-Regular',
    fontSize: 14,
    lineHeight: 18,
    marginHorizontal: 5,
    color: Colors.dark.neutral100,
    letterSpacing: 0.25,
  },
  play: {
    alignSelf: 'center',
  },
  next: {
    marginHorizontal: 10,
  },
  control: {
    width: '100%',
    position: 'absolute',
    height: '100%',
    justifyContent: 'flex-start',
  },
  setting: {
    position: 'absolute',
    marginVertical: 20,
    right: 5,
  },
  settingList: {
    padding: 5,
    borderBottomWidth: 1,
    borderColor: Colors.dark.neutral50,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  controlContainer: {
    justifyContent: 'flex-end',
    position: 'absolute',
    width: '100%',
    height: '100%',
  },
  sliderContainer: {
    justifyContent: 'flex-end',
    position: 'absolute',
    width: '100%',
  },
  modalList: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  accordion: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  textAccordion: {
    fontFamily: 'Poppins-Regular',
    fontWeight: '400',
    fontSize: 16,
    lineHeight: 24,
    padding: 10,
  },
  slide: {
    fontFamily: 'Poppins-Regular',
    color: Colors.primary.base,
    backgroundColor: Colors.primary.light2,
    padding: 5,
    borderRadius: 10,
    width: 80,
    marginBottom: 10,
  },
  input: {
    height: 120,
  },
  button: {
    flexDirection: 'row',
    backgroundColor: Colors.primary.base,
    justifyContent: 'center',
    padding: 10,
    margin: 16,
    borderRadius: 20,
  },
  textButton: {
    fontFamily: 'Poppins-Bold',
    color: Colors.white,
    fontSize: 16,
    lineHeight: 24,
  },
  modalTitle: {
    fontFamily: 'Poppins-Bold',
    fontWeight: '600',
    fontSize: 16,
    lineHeight: 24,
    letterSpacing: 0.01,
    color: Colors.dark.neutral100,
    width: '100%',
    textAlign: 'center',
    marginTop: 15,
  },
  containerSwipe: {
    justifyContent: 'center',
    alignItems: 'center',
    width: '100%',
  },
  search: {
    backgroundColor: '#F5F7F9',
    width: '100%',
    fontFamily: 'Poppins-Regular',
    borderTopRightRadius: 20,
    borderBottomRightRadius: 20,
    height: 40,
    paddingVertical: 8,
    paddingHorizontal: 16,
  },
  searchBar: {
    flexDirection: 'row',
    alignItems: 'center',
    height: 40,
    paddingHorizontal: 45,
  },
  iconSearch: {
    backgroundColor: '#F5F7F9',
    paddingVertical: 8,
    borderTopLeftRadius: 20,
    borderBottomLeftRadius: 20,
  },
  presentationContainer: {width: '100%', height: '50%'},
});
