import Colors from '@constants/colors';
import Fonts from '@constants/fonts';
import {StyleSheet} from 'react-native';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: Colors.white,
  },
  innerSubjectsFavContainer: {
    flexDirection: 'row',
    width: '100%',
    justifyContent: 'center',
    marginTop: 10,
  },
  defaultImageStyle: {width: 60, height: 60, marginHorizontal: 10},
  mh10: {marginHorizontal: 10},
  swipeUpContainer: {height: 400, width: '100%', marginTop: 10},
  swpTopContent: {flex: 1, alignItems: 'center'},
  swpTopTitle: {
    marginLeft: '1%',
    fontFamily: 'Poppins-SemiBold',
    color: Colors.primary.base,
    marginTop: '1%',
    fontSize: 14,
    lineHeight: 18,
  },
  settingFavIconActionContainer: {
    position: 'absolute',
    right: 10,
    width: 20,
    height: 20,
    backgroundColor: Colors.success.light1,
    borderRadius: 100,
    justifyContent: 'center',
    alignItems: 'center',
  },
  settingFavIconActionContainer2: {
    position: 'absolute',
    right: 10,
    width: 20,
    height: 20,
    backgroundColor: Colors.danger.base,
    borderRadius: 100,
    justifyContent: 'center',
    alignItems: 'center',
  },
  swpMiddleContent2: {
    width: '100%',
    height: 250,
  },
  swpMiddleTitleContainer: {flex: 1},
  subjectIcon: {width: 60, height: 60, marginBottom: 10},
  swpMiddleInnerContent: {
    alignItems: 'center',
    marginVertical: 10,
    height: 100,
    marginHorizontal: 10,
  },
  swpMiddleScrollViewInner: {
    flex: 1,
    flexWrap: 'wrap',
    justifyContent: 'center',
    flexDirection: 'row',
  },
  swpMiddleContent: {
    flex: 4,
    flexDirection: 'row',
    flexWrap: 'wrap',
  },
  swpBottomContent: {
    flex: 1.4,
    paddingHorizontal: '10%',
    justifyContent: 'center',
  },
  swpTopInnerContent: {
    flex: 1,
    alignItems: 'center',
  },
  swpTopTitle2Container: {flexDirection: 'row', alignItems: 'center'},
  swpTopTitle2: {
    marginLeft: '1%',
    fontFamily: 'Poppins-SemiBold',
    color: Colors.dark.neutral100,
    marginTop: '1%',
    fontSize: 20,
    lineHeight: 28,
  },
  swpTopTitle3: {
    fontSize: 16,
    lineHeight: 24,
    textAlign: 'center',
    marginTop: '4%',
  },
  swpMiddleIconSubject: {
    width: 50,
    height: 50,
    marginHorizontal: '5%',
    marginVertical: '10%',
    borderRadius: 50,
  },
  swpTopBodyContent: {flexDirection: 'row', alignItems: 'center', gap: 8},
  content: {
    flex: 2,
    backgroundColor: Colors.primary.light4,
    padding: 16,
    borderRadius: 20,
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
  },
  fab: {
    backgroundColor: 'yellow',
  },
  btn: {
    position: 'absolute',
    bottom: 12,
    backgroundColor: Colors.primary.base,
    flexDirection: 'row',
    alignItems: 'center',
    alignSelf: 'center',
    gap: 8,
    borderRadius: 30,
    paddingVertical: 8,
    paddingHorizontal: 16,
    marginTop: 22,
  },
  swpMiddleTitle: {
    textAlign: 'center',
    fontFamily: 'Poppins-Regular',
    color: Colors.dark.neutral100,
    fontSize: 12,
  },
  box: {
    height: '100%',
    backgroundColor: Colors.primary.light4,
    flex: 1,
  },
  settingFavContainer: {width: '100%', height: 600, backgroundColor: 'white'},
  settingFavTopContentContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  settingFavTopTitleContainer: {
    width: '100%',
    marginTop: '2%',
    marginBottom: '2%',
    paddingHorizontal: '5%',
  },
  settingFavTopTitle: {
    fontFamily: 'Poppins-SemiBold',
    fontSize: 16,
    lineHeight: 24,
    color: Colors.dark.neutral100,
  },
  settingFavBottomContentContainer: {
    width: '100%',
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'center',
    paddingVertical: 5,
  },
  settingFavEmptyIcon: {
    flex: 1,
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'center',
    alignItems: 'center',
  },
  settingFavBottomContainer: {
    flex: 3,
    backgroundColor: 'white',
  },
  settingFavBottomTitlecontainer: {width: '100%', paddingHorizontal: '5%'},
  settingFavBottomTitle: {
    fontFamily: 'Poppins-SemiBold',
    fontSize: 16,
    lineHeight: 24,
    color: Colors.dark.neutral100,
  },
  settingFavBottomScrollView: {marginTop: '5%', marginBottom: '10%'},
  settingFavBottomSubjectContainer: {marginHorizontal: 5, marginBottom: 20},
  settingFavSubmitButtonContainer: {marginHorizontal: '5%'},
  containerSwipeUp: {},
  forbiddenTestContainerStyle: {
    alignItems: 'center',
    paddingBottom: 24,
    marginHorizontal: 10,
  },
  forbiddenTestIconContainerStyle: {marginTop: 28, marginBottom: 8},
  forbiddenTestDescriptionTopStyle: {
    marginTop: 10,
    fontFamily: Fonts.SemiBoldPoppins,
    color: Colors.dark.neutral100,
    fontSize: 16,
    lineHeight: 24,
    textAlign: 'center',
  },
  forbiddenTestDescriptionBottomStyle: {
    marginTop: 10,
    fontFamily: Fonts.RegularPoppins,
    color: Colors.dark.neutral80,
    fontSize: 14,
    lineHeight: 22,
    letterSpacing: 0.25,
    textAlign: 'center',
  },
  lmsContainer: {
    marginVertical: 12,
  },
  titleValidation: {
    fontWeight: '600',
    fontSize: 16,
    lineHeight: 24,
    fontFamily: Fonts.BoldPoppins,
    color: Colors.black,
    textAlign: 'center',
  },
  descValidation: {
    fontWeight: '400',
    fontSize: 14,
    lineHeight: 22,
    fontFamily: Fonts.RegularPoppins,
    color: Colors.dark.neutral80,
    textAlign: 'center',
  },
  btnSwipeContainer: {
    marginVertical: 18,
    width: '100%',
  },
  ptnUnSubsContainer: {height: 260, padding: 16, alignItems: 'center'},
});
