import Colors from '@constants/colors';
import Fonts from '@constants/fonts';
import {StyleSheet} from 'react-native';

export const styles = StyleSheet.create({
  container: {flex: 1, backgroundColor: 'white'},
  slideImageContainer: {flex: 0.7, alignItems: 'center'},
  slideButtonBackContainer: {
    flex: 0.3,
    justifyContent: 'center',
    alignItems: 'center',
  },
  slideContainer: {
    width: '100%',
    paddingVertical: 15,
    flexDirection: 'row',
    borderBottomWidth: 0.3,
    borderBottomColor: Colors.dark.neutral20,
  },
  slideTitleContainer: {flex: 1, justifyContent: 'center'},
  slideImageEmpty: {
    width: 130,
    height: 75,
    borderRadius: 10,
    backgroundColor: Colors.dark.neutral20,
  },
  mediaContainer: {width: '100%', height: 420, marginBottom: 10},
  headerContainer: {backgroundColor: 'white'},
  headerIconRight: {paddingTop: 10},
  headerIconSave: {marginRight: -30},
  flex1: {flex: 1},
  sliderContainer: {
    flex: 5,
    backgroundColor: Colors.dark.neutral80,
    justifyContent: 'center',
    alignItems: 'center',
  },
  slideTitle: {
    fontFamily: Fonts.RegularPoppins,
    fontSize: 14,
    lineHeight: 18,
    color: Colors.dark.neutral100,
  },
  h600: {height: 600},
  noMediaContainer: {
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: '40%',
  },
  swipeErrorNotFoundTextTop: {
    fontFamily: 'Poppins-SemiBold',
    fontSize: 16,
    lineHeight: 24,
    color: Colors.dark.neutral100,
    marginTop: 10,
  },
  swipeEmptyStateTextTop: {
    fontFamily: 'Poppins-SemiBold',
    fontSize: 16,
    lineHeight: 24,
    color: Colors.dark.neutral100,
    marginTop: 10,
    alignContent: 'center',
    alignItems: 'center',
    alignSelf: 'center',
  },
  swipeErrorNotFoundTextBottom: {
    fontFamily: 'Poppins-Regular',
    fontSize: 14,
    lineHeight: 18,
    color: Colors.dark.neutral60,
    textAlign: 'center',
    marginTop: '2%',
  },
  swipeErrorNotFoundContainer: {
    marginTop: 30,
    width: '100%',
    height: '100%',
    justifyContent: 'center',
    alignItems: 'center',
  },
  swipeButtonBack: {
    width: '90%',
  },
  headerSwiperContainer: {width: '100%', alignItems: 'center', marginTop: '2%'},
  headerSwiperText: {
    fontFamily: 'Poppins-SemiBold',
    fontSize: 20,
    lineHeight: 28,
    color: Colors.dark.neutral100,
  },
  swipeInputText: {
    width: '100%',
    marginTop: '2%',
    paddingHorizontal: '5%',
    paddingBottom: 10,
  },
  presentationContainer: {width: '100%', height: '50%'},
  presentationContainerError: {
    width: '100%',
    height: 1800,
    justifyContent: 'center',
    alignItems: 'center',
  },
  mediaErrorText: {fontSize: 14, fontFamily: 'Poppins-Regular', color: 'white'},
  sliderInfoContainer: {
    flex: 1,
    justifyContent: 'center',
    paddingHorizontal: '5%',
  },
  sliderInfoContentContainer: {
    width: 62,
    height: 20,
    backgroundColor: Colors.primary.light2,
    marginVertical: 20,
    borderRadius: 6,
    alignItems: 'center',
    justifyContent: 'center',
    flexDirection: 'row',
  },
  sliderTitle: {
    fontFamily: 'Poppins-Regular',
    color: Colors.primary.base,
    fontSize: 11,
  },
  sliderCount: {
    fontFamily: 'Poppins-Regular',
    color: Colors.primary.base,
    fontSize: 11,
    marginLeft: '5%',
  },
  descriptionContainer: {flex: 6.5},
  descriptionInnerContainer: {width: '100%', paddingHorizontal: '5%'},
  descriptionTitleContainer: {width: '100%'},
  descriptionTitle: {
    fontFamily: 'Poppins-SemiBold',
    fontSize: 16,
    lineHeight: 24,
    color: Colors.dark.neutral100,
  },
  descriptionBodyContainer: {width: '100%'},
  descriptionBody: {
    fontFamily: 'Poppins-Regular',
    fontSize: 14,
    lineHeight: 22,
    color: Colors.dark.neutral100,
    marginTop: '2%',
  },
  buttonContainer: {
    marginHorizontal: '5%',
    marginBottom: 24,
    height: 46,
  },
  listRow: {
    flexDirection: 'row',
    alignItems: 'center',
    margin: 10,
  },
  text: {
    fontFamily: 'Poppins-Regular',
    fontSize: 16,
    lineHeight: 24,
    textAlign: 'center',
    letterSpacing: 0.01,
    display: 'flex',
    alignItems: 'center',
    color: '#1D252D',
    marginLeft: 10,
  },
});
