import Colors from '@constants/colors';
import Fonts from '@constants/fonts';
import {WINDOW_WIDTH} from '@gorhom/bottom-sheet';
import {StyleSheet} from 'react-native';

export const styles = StyleSheet.create({
  rootContainer: {
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
    paddingTop: 16,
    paddingHorizontal: 16,
    backgroundColor: Colors.white,
    flexGrow: 1,
  },
  flexGrow: {
    flexGrow: 1,
  },
  iconAddMemberContainer: {
    width: 40,
    height: 40,
    borderRadius: 100,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: Colors.primary.base,
    marginRight: 12,
  },
  contentContainerStyle: {
    flexGrow: 1,
  },
  headIconContainer: {
    height: 88,
    width: 88,
    alignSelf: 'center',
    marginBottom: 16,
  },
  headIcon: {
    height: 88,
    width: 88,
    resizeMode: 'contain',
    borderRadius: 100,
  },
  iconCameraWhiteInnerContainer: {
    backgroundColor: Colors.primary.base,
    width: 32,
    height: 32,
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 100,
  },
  iconCameraWhiteOutterContainer: {
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 100,
    width: 38,
    height: 38,
    backgroundColor: Colors.white,
    position: 'absolute',
    bottom: -8,
    right: -8,
  },
  row: {
    flexDirection: 'row',
  },
  rowSpaceBetween: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 16,
  },
  swipeUpButtonContainer: {
    marginTop: 32,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  addMemberContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 16,
  },
  headTextContainer: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 16,
  },
  headTitle: {
    fontWeight: '600',
    fontSize: 16,
    lineHeight: 24,
    textAlign: 'center',
    color: Colors.dark.neutral100,
    fontFamily: Fonts.SemiBoldPoppins,
    marginRight: 4,
  },
  headSubtitle: {
    fontWeight: '600',
    fontSize: 14,
    lineHeight: 22,
    textAlign: 'center',
    color: Colors.dark.neutral60,
    fontFamily: Fonts.SemiBoldPoppins,
  },
  cardTitle: {
    width: WINDOW_WIDTH - 220,
    // backgroundColor: 'red',
    fontWeight: '600',
    fontSize: 16,
    lineHeight: 24,
    color: Colors.dark.neutral100,
    fontFamily: Fonts.SemiBoldPoppins,
  },
  cardRoleTitle: {
    fontWeight: '400',
    fontSize: 12,
    lineHeight: 16,
    color: Colors.dark.neutral60,
    fontFamily: Fonts.RegularPoppins,
  },
  cardOnlineTitle: {
    fontWeight: '400',
    fontSize: 12,
    lineHeight: 16,
    color: Colors.success.base,
    fontFamily: Fonts.RegularPoppins,
  },
  cardIcon: {
    marginRight: 12,
    width: 40,
    height: 40,
    borderRadius: 100,
  },
  container: {
    flex: 1,
    paddingTop: 12,
  },
  swipeUpEditGroupCard: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  swipeUpMoreUserCard: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 16,
  },
  swipeUpEditGroupCardTitle: {
    fontWeight: '400',
    fontSize: 16,
    lineHeight: 24,
    fontFamily: Fonts.RegularPoppins,
    color: Colors.dark.neutral100,
    marginLeft: 12,
  },
  gap: {
    height: 16,
  },
  swipeUpContainer: {
    padding: 16,
  },
  swipeUpHeadTitle: {
    fontWeight: '600',
    fontSize: 20,
    lineHeight: 28,
    textAlign: 'center',
    fontFamily: Fonts.SemiBoldPoppins,
    color: Colors.dark.neutral100,
    marginBottom: 8,
  },
  swipeUpLabelTitle: {
    fontWeight: '400',
    fontSize: 14,
    lineHeight: 22,
    textAlign: 'center',
    fontFamily: Fonts.RegularPoppins,
  },
  styleHeaderLabel: {
    fontWeight: '600',
    fontSize: 16,
    lineHeight: 20,
    textAlign: 'center',
    paddingTop: 10,
  },
  bgBlueOrnament: {
    resizeMode: 'cover',
    width: '100%',
    position: 'absolute',
    zIndex: -1,
    backgroundColor: Colors.primary.background,
  },
  badgeContainer: {
    backgroundColor: Colors.success.light2,
    borderRadius: 20,
    marginRight: 8,
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: 8,
    paddingVertical: 4,
  },
  badgeTitle: {
    fontWeight: '400',
    fontSize: 12,
    lineHeight: 16,
    color: Colors.success.base,
    fontFamily: Fonts.RegularPoppins,
  },
});
