import Colors from '@constants/colors';
import Fonts from '@constants/fonts';
import {StyleSheet} from 'react-native';

export const styles = StyleSheet.create({
  rootContainer: {
    flex: 1,
    backgroundColor: Colors.white,
  },
  contentContainerStyle: {
    flexGrow: 1,
  },
  cardContainer: {
    marginTop: '15%',
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
    backgroundColor: Colors.white,
    paddingHorizontal: 16,
    paddingBottom: 16,
  },
  bgBlueOrnament: {
    resizeMode: 'cover',
    width: '100%',
    height: '50%',
    position: 'absolute',
    zIndex: -1,
  },

  container: {
    flex: 1,
    paddingBottom: 24,
    marginTop: -40,
  },
  imageContainer: {
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 32,
  },
  cameraIconOutterContainer: {
    marginTop: -28,
    marginRight: -50,
    height: 30,
    width: 30,
    backgroundColor: Colors.white,
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 50,
  },
  cameraIconInnerContainer: {
    height: 25,
    width: 25,
    backgroundColor: Colors.primary.base,
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 50,
  },
  imageOutterStudentContainer: {
    padding: 4,
    width: 80,
    height: 80,
    backgroundColor: Colors.yellow,
    borderRadius: 100,
    alignItems: 'center',
    justifyContent: 'center',
    alignSelf: 'center',
  },
  imageOutterParentContainer: {
    padding: 4,
    width: 80,
    height: 80,
    backgroundColor: Colors.success.base,
    borderRadius: 100,
    alignItems: 'center',
    justifyContent: 'center',
    alignSelf: 'center',
  },
  imageOutterTeacherContainer: {
    padding: 4,
    width: 80,
    height: 80,
    backgroundColor: Colors.primary.base,
    borderRadius: 100,
    alignItems: 'center',
    justifyContent: 'center',
    alignSelf: 'center',
  },
  imageOutterAdminContainer: {
    padding: 4,
    width: 80,
    height: 80,
    backgroundColor: Colors.primary.light5,
    borderRadius: 100,
    alignItems: 'center',
    justifyContent: 'center',
    alignSelf: 'center',
  },
  imageInnerContainer: {
    padding: 4,
    width: 72,
    height: 72,
    backgroundColor: Colors.white,
    borderRadius: 100,
    alignItems: 'center',
    justifyContent: 'center',
  },
  imageUser: {
    resizeMode: 'cover',
    width: 70,
    height: 70,
    borderRadius: 100,
  },
  classContainer: {
    marginBottom: 16,
  },
  phoneContainer: {
    marginBottom: 32,
  },
  phoneHeaderTitle: {
    fontSize: 14,
    fontWeight: '400',
    lineHeight: 22,
    fontFamily: 'Poppins-Regular',
    color: Colors.dark.neutral100,
    marginBottom: 8,
  },
  phoneCardContainer: {
    paddingHorizontal: 16,
    paddingVertical: 10,
    borderRadius: 30,
    backgroundColor: Colors.dark.neutral10,
    justifyContent: 'space-between',
    flexDirection: 'row',
  },
  phoneTextContainer: {
    flexDirection: 'row',
  },
  phoneTitle: {
    fontSize: 16,
    fontWeight: '600',
    lineHeight: 24,
    fontFamily: Fonts.SemiBoldPoppins,
  },
  disabledTitle: {
    fontSize: 16,
    fontWeight: '600',
    lineHeight: 24,
    fontFamily: Fonts.SemiBoldPoppins,
    color: Colors.dark.neutral50,
  },
  phoneChangeTitle: {
    fontSize: 14,
    fontWeight: '600',
    lineHeight: 22,
    fontFamily: Fonts.SemiBoldPoppins,
    color: Colors.primary.base,
    paddingRight: 16,
  },
  phoneIconContainer: {
    justifyContent: 'center',
  },
  iconLeft: {
    width: 22,
    height: 22,
    marginRight: 16,
    alignSelf: 'center',
  },
  iconRight: {
    width: 22,
    height: 22,
  },

  swipeUpContainerClass: {
    padding: 16,
    height: 250,
  },
  swipeUpContainer: {
    padding: 16,
  },
  swipeUpIcon: {
    marginRight: 12,
  },
  swipeUpContent: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  swipeUpTitle: {
    paddingVertical: 8,
    fontSize: 16,
    fontWeight: '400',
    lineHeight: 24,
    fontFamily: 'Poppins-Regular',
    color: Colors.dark.neutral100,
  },
  swipeUpHeaderTitle: {
    fontSize: 20,
    lineHeight: 28,
    color: Colors.dark.neutral100,
    fontWeight: '600',
    fontFamily: Fonts.SemiBoldPoppins,
    textAlign: 'center',
    marginBottom: 16,
  },
  swipeUpContentContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 16,
  },
  descriptionSwipeUpActive: {
    fontSize: 16,
    lineHeight: 24,
    color: Colors.primary.base,
    fontWeight: '600',
    fontFamily: Fonts.SemiBoldPoppins,
  },
  descriptionSwipeUpPasive: {
    fontSize: 16,
    lineHeight: 24,
    color: Colors.dark.neutral100,
    fontWeight: '600',
    fontFamily: Fonts.SemiBoldPoppins,
  },
  outterDotActive: {
    borderRadius: 25,
    width: 24,
    height: 24,
    backgroundColor: Colors.primary.base,
    alignItems: 'center',
    justifyContent: 'center',
  },
  outterDotPassive: {
    borderRadius: 25,
    width: 24,
    height: 24,
    backgroundColor: Colors.white,
    borderWidth: 2,
    borderColor: Colors.dark.neutral50,
    alignItems: 'center',
    justifyContent: 'center',
  },
  innerDot: {
    position: 'absolute',
    borderRadius: 25,
    width: 8,
    height: 8,
    backgroundColor: Colors.white,
  },
});
