import Colors from '@constants/colors';
import {Dimensions, StyleSheet} from 'react-native';

const windowHeight = Dimensions.get('window').height;

export const styles = StyleSheet.create({
  container: {
    height: '100%',
    width: '100%',
  },
  rowCenter: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  kpRegularCheckListIcon: {
    position: 'absolute',
    right: -3,
    bottom: 2,
    padding: 5,
  },
  greyArrowContainer: {flex: 0.1, marginLeft: 10},
  mr5p: {marginRight: '5%'},
  checkListIcon: {position: 'absolute', right: -3, bottom: 5},
  checkItem: {marginRight: 15},
  akmQuestionTabContainer: {
    width: '100%',
    height: 90,
    backgroundColor: Colors.primary.background,
    alignItems: 'center',
  },
  mt5: {marginTop: 5},
  mt10: {marginTop: 10},
  headerTitleContainer: {
    position: 'absolute',
    top: '35%',
    alignItems: 'center',
  },
  flex1: {flex: 1},
  mb3p: {marginBottom: '3%'},
  headerTitleStyle: {
    fontFamily: 'Poppins-SemiBold',
    fontSize: 14,
    lineHeight: 22,
    letterSpacing: 0.25,
    color: Colors.white,
  },
  headerSubTitleStyle: {
    fontFamily: 'Poppins-Regular',
    fontSize: 11,
    lineHeight: 16,
    letterSpacing: 0.25,
    color: Colors.white,
  },
  header: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    height: 200,
    zIndex: 1,
  },
  backgroundImage: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    resizeMode: 'cover',
  },
  akmQuestionIconContainer: {
    flex: 1.2,
    justifyContent: 'center',
    alignItems: 'center',
  },
  akmuQuiestionIcon: {width: 35, height: 45},
  akmQuestionMiddlePartContainer: {flex: 6, justifyContent: 'center'},
  akmQuestionCountContainer: {
    fontFamily: 'Poppins-Regular',
    color: Colors.dark.neutral60,
    fontSize: 12,
  },
  akmQuestionArrowIconCOntainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  akmQuestionArrowIconCOntainer2: {
    flex: 0.05,
    justifyContent: 'center',
    alignItems: 'center',
  },
  akmQuestionMiddlePartTitle: {
    fontFamily: 'Poppins-SemiBold',
    color: Colors.dark.neutral100,
    fontSize: 16,
    lineHeight: 24,
  },
  akmQuestionTabInnerContainer: {
    width: '90%',
    height: '90%',
    backgroundColor: Colors.white,
    borderRadius: 10,
    padding: 12,
    gap: 8,
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 1,
    },
    shadowOpacity: 0.22,
    shadowRadius: 2.22,

    elevation: 3,
    flexDirection: 'row',
  },
  gameSublistItemContainer: {flex: 5, alignItems: 'center'},
  soalSublistItemContainer: {flex: 5, alignItems: 'center'},
  shadowProp: {
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
    elevation: 5,
  },
  card: {
    flex: 1,
    alignSelf: 'flex-end',
    backgroundColor: 'white',
    padding: 10,
    borderRadius: 10,
    width: 265,
  },
  card2: {
    alignSelf: 'flex-end',
    backgroundColor: 'white',
    borderRadius: 10,
    width: 265,
  },
  title: {
    fontFamily: 'Poppins-Bold',
    fontSize: 14,
    color: Colors.dark.neutral100,
  },
  title2: {
    fontFamily: 'Poppins-Bold',
    fontSize: 14,
    color: Colors.dark.neutral60,
  },
  gamesTitle2: {fontSize: 14, flex: 1},
  soalTitle2: {fontSize: 14},
  image: {
    width: 32,
    height: 32,
    marginRight: 10,
  },
  mainImage: {
    width: 64,
    height: 64,
    marginRight: 10,
  },
  box: {
    flexDirection: 'row',
    flex: 1,
    alignItems: 'center',
    borderBottomWidth: 1,
    borderColor: '#E7EBEE',
  },
  box2: {
    flexDirection: 'row',
    paddingVertical: 10,
    paddingLeft: 10,
    alignItems: 'center',
    borderBottomWidth: 1,
    borderColor: '#E7EBEE',
  },
  iconContainer: {
    width: 50,
    height: 50,
    backgroundColor: Colors.white,
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 100,
  },
  gamesLineContainer: {flex: 1},
  gamesLineInnerContainer: {marginLeft: 7},
  topContainer: {
    width: '100%',
    height: 200,
    paddingVertical: '5%',
  },
  topContainer2: {
    width: '100%',
    height: windowHeight / 8,
    paddingVertical: '5%',
  },
  topContainerAKM: {
    width: '100%',
    height: windowHeight / 7.5,
    paddingVertical: '5%',
  },
  content: {
    flex: 4,
    backgroundColor: 'white',
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
    marginTop: -20,
  },
  detailHeader: {
    width: '100%',
    paddingVertical: 20,
    justifyContent: 'center',
    flexDirection: 'row',
    backgroundColor: 'transparent',
    borderBottomWidth: 0.3,
    borderBottomColor: Colors.dark.neutral60,
  },
  detailHeaderLeftSection: {
    flex: 1,
    justifyContent: 'center',
    paddingHorizontal: '5%',
  },
  detailHeaderRightSection: {
    flex: 1,
    paddingRight: '15%',
    paddingLeft: '5%',
    justifyContent: 'center',
  },
  detailHeaderLeftContentTop: {
    fontSize: 12,
    lineHeight: 16,
    fontFamily: 'Poppins-Regular',
    color: Colors.dark.neutral60,
  },
  detailHeaderLeftContentBottom: {
    fontSize: 14,
    lineHeight: 22,
    fontFamily: 'Poppins-SemiBold',
    color: Colors.dark.neutral100,
    marginTop: '3%',
  },
  ibHeaderContainer: {
    flex: 1,
    justifyContent: 'center',
    flexDirection: 'row',
    paddingBottom: '2%',
  },
  ibHeaderContainer2: {
    position: 'absolute',
    bottom: '60%',
    justifyContent: 'center',
    flexDirection: 'row',
    paddingBottom: '2%',
  },
  ibHeaderLeftContent: {
    flex: 1,
    justifyContent: 'flex-end',
    paddingLeft: '5%',
  },
  ibHeaderRightContent: {
    flex: 1,
    justifyContent: 'flex-end',
    alignItems: 'flex-end',
    paddingRight: '5%',
  },
  ibHeaderBottomContent: {
    flex: 2.5,
    flexDirection: 'row',
  },
  ibHeaderBottomLeftContent: {
    flex: 1,
    justifyContent: 'center',
    paddingLeft: '5%',
  },
  ibHeaderLessonIcon: {
    width: 70,
    height: 70,
    borderRadius: 100,
    backgroundColor: 'white',
    justifyContent: 'center',
    alignItems: 'center',
  },
  ibHeaderBottomRightContent: {flex: 3, justifyContent: 'center'},
  ibHeaderBottomRightContent2: {
    flex: 3,
    alignItems: 'center',
  },
  ibHeaderTitle1: {
    fontFamily: 'Poppins-SemiBold',
    fontSize: 12,
    lineHeight: 16,
    letterSpacing: 0.25,
    color: Colors.primary.light2,
  },
  ibHeaderTitle1WithMargin: {
    fontFamily: 'Poppins-SemiBold',
    fontSize: 12,
    lineHeight: 16,
    letterSpacing: 0.25,
    marginTop: '1%',
    color: Colors.primary.light2,
  },
  ibHeaderTitle2: {
    fontFamily: 'Poppins-SemiBold',
    fontSize: 18,
    lineHeight: 24,
    letterSpacing: 1,
    color: Colors.white,
    marginTop: '2%',
  },
  modalContainer: {width: '100%', paddingHorizontal: '5%', marginTop: 10},
  modalInnerContainer: {
    width: '100%',
    height: 80,
    backgroundColor: Colors.success.light2,
    borderRadius: 10,
    gap: 16,
    flexDirection: 'row',
  },
  concepCardIconContainer: {
    flex: 2,
    justifyContent: 'center',
    alignItems: 'center',
  },
  conceptCardIconMiddleContainer: {
    flex: 5,
    justifyContent: 'center',
    paddingLeft: 10,
  },
  conceptCardMiddleTitle: {
    fontFamily: 'Poppins-SemiBold',
    fontSize: 16,
    lineHeight: 20,
    color: Colors.dark.neutral100,
  },
  conceptCardMiddleTitle2: {
    fontFamily: 'Poppins-SemiBold',
    fontSize: 12,
    marginTop: '1%',
    lineHeight: 16,
    color: Colors.dark.neutral60,
  },
  conceptCardLeftContainer: {flex: 1, justifyContent: 'center'},
  cardBottomContainer: {width: '100%', flexDirection: 'row', gap: 12},
  cardContainer: {
    width: '100%',
    height: 140,
    marginVertical: 15,
    flexDirection: 'row',
    paddingHorizontal: '4%',
  },
  cardContentLeft: {flex: 1},
  cardContentInnerLeft: {
    width: '100%',
    height: '100%',
    backgroundColor: Colors.primary.light3,
    borderRadius: 10,
    padding: '5%',
    justifyContent: 'space-around',
  },
  cardContentTopTextContainer: {},
  cardContentTopText: {
    fontSize: 12,
    lineHeight: 16,
    fontFamily: 'Poppins-Regular',
    color: Colors.dark.neutral60,
  },
  cardInnerBottomContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    // gap: 8,
  },
  cardInnerIconContainer: {
    // justifyContent: 'center',
    marginRight: 6,
    alignItems: 'flex-start',
  },
  cardInnerTitleContainer: {
    flex: 1,
    height: 40,
    alignItems: 'flex-start',
    justifyContent: 'center',
  },
  cardInnerTitle: {
    fontFamily: 'Poppins-SemiBold',
    color: Colors.dark.neutral100,
    fontSize: 14,
  },
  cardInnerRightIcon: {
    justifyContent: 'center',
    alignItems: 'flex-start',
  },
  lessonListContainer: {width: '100%', paddingHorizontal: '5%'},
  lessonPresentastionContainer: {
    flexDirection: 'row',
    width: '100%',
  },
  lessonProgressContainer: {
    flex: 1.5,
    justifyContent: 'center',
    alignItems: 'center',
  },
  lessonTitleContainer: {flex: 5, justifyContent: 'center', paddingLeft: '5%'},
  lessonTitle: {
    fontFamily: 'Poppins-SemiBold',
    fontSize: 12,
    lineHeight: 16,
    letterSpacing: 0.25,
    color: Colors.dark.neutral50,
  },
  lessonTitle2: {
    fontFamily: 'Poppins-SemiBold',
    fontSize: 16,
    lineHeight: 20,
    letterSpacing: 0.25,
    color: Colors.dark.neutral100,
    marginTop: '1%',
  },
  lessonArrowContainer: {
    flex: 1,
    justifyContent: 'center',
    paddingEnd: 10,
    alignItems: 'center',
    flexDirection: 'row',
  },
  separatorContainer: {
    flexDirection: 'row',
    width: '100%',
    height: 30,
    backgroundColor: 'transparent',
    zIndex: -1,
  },
  separatorLineContainer: {
    flex: 1.5,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'transparent',
  },
  gamesContentContainer: {
    width: '100%',
    height: 300,
    flexDirection: 'row',
  },
  soalContentContainer: {
    width: '100%',
    flexDirection: 'row',
  },
  separatorLine: {
    height: '100%',
    borderLeftWidth: 2,
    borderStyle: 'dotted',
    backgroundColor: 'transparent',
    borderColor: Colors.dark.neutral20,
  },
  separatorPadding: {flex: 6.5},
});
